### ISSUE TITLE
How to distribute Styles?

### ISSUE THREAD

**Issue by lukasmartinelli** [maputnik/editor#10]
An important part of Maputnik will be to share styles with each other. The JSON is perhaps enough - perhaps not and we need a ZIP file for having local fonts and glyphs.

We just need to think about how people can share their styles.

**Comment by orangemug** [comment]
I have also been thinking about offine usage of styles. Basically what I would like is for a styles to define all the assets they require to be functional offline. Basically so     they can be downloaded by

 - A desktop client
 - A server on first deploy
 - A service worker to be put in the browser cache

How about adding a manifest with information about where the different assets are available for download?

**Comment by lukasmartinelli** [comment]
> How about adding a manifest with information about where the different assets are available for download?

Don't have a solution ready... Happy to accept proposals - no opinions on my side yet.
Just that enduser experience matters. Users must be able to share editable styles. Only this way we can get people to play.

With Mapbox Studio Classic there was the `tm2z` format that bundled everything.
In the GL spec the styles just point to the asset URIs (sprites and glyphs). This is already enough to pull down the data (if you want to do caching only).

I am not sure a manifest is necessary. The GL style already has all the information - or you can add metadata there as well. A manifest on the other way would be a bit more generic if later we want to export a OL3 style function (then loading the plugin from #7 is only necessary in the editor).

As long as you would ship the generated glyph PBFs and the sprites it is not so difficult.
But perhaps one wants to ship the source assets with the styles, so it is easy to share and modify.

**Comment by orangemug** [comment]
> I am not sure a manifest is necessary. The GL style already has all the information

I guess only if you can recursively download the assets, which you can't with the following for example

```
"sprite": "http://osm-liberty.lukasmartinelli.ch/sprites/osm-liberty",
"glyphs": "https://orangemug.github.io/font-glyphs/glyphs/{fontstack}/{range}.pbf" 
```

> As long as you would ship the generated glyph PBFs and the sprites it is not so difficult.

This will mean you end up with lots of styles with slightly different versions of typefaces over time

I'll work on a spec of my ideas around the manifest tomorrow you can see what you think

**Comment by klokan** [comment]
Related repo: https://github.com/klokantech/gl-style-package-spec
Feel free to create tickets there to move the ideas forward

**Comment by lukasmartinelli** [comment]
@orangemug [generates the font artefacts](https://github.com/orangemug/font-glyphs/blob/master/deploy.sh) via Travis and stores it in GitHub pages from the repo https://github.com/orangemug/font-glyphs which is a cool idea.

**Comment by orangemug** [comment]
@lukasmartinelli there is also a v2 in the works that supports any font from google fonts (I'll make it public next week)

**Comment by lukasmartinelli** [comment]
From the Maputnik side of view still all I care is a `style.json`.

Fonts and glyphs must be managed externally (yes that is not ideal but these features can only be provided by a hosted platform or a server appication).
