### ISSUE TITLE
Windows version - multiple issues

### ISSUE THREAD

**Issue by Tom-Cuthill** [maputnik/editor#100]
Hi, 

I'm new to Maputnik, but I've run into a problem which has me stuck, pretty well straight away.  I installed the local windows version, and then added a openmaptiles source, using https://free.tilehosting.com/data/v3.json?key=my own key.  Then I added a local source, which can supply mapbox vector tiles for a cadastral layer from geoserver.

I then added the layer matching the cadastral layer in the source.  If I move the map around, in the Google developer tools I can see the cadastral tiles being downloaded without any errors.  The layer is invisible though, and I am not able to get it to render.  I do not see a reference to it in Inspect Mode - it is like it is not there.

I've made sure that in the JSON editor I have set the layout visibility to be visible and the fill-color and the fill-outline-color to appropriate RGBA values.  I still can not see anything.  If I click on the Color, or Outline Color fields in the Paint Properties, there is no popup window letting me choose a colour.  I have to start things off by manually typing in the JSON editor to get anything to display.  Only when I've filled values in the JSON editor, is it possible to get the colour popup to work.  I do see the following errors and warnings in the console:

![image](https://cloud.githubusercontent.com/assets/24502866/23644220/2c0696fa-0341-11e7-991f-2d348b7060ed.png)

Here is what I see in the JSON editor:
![image](https://cloud.githubusercontent.com/assets/24502866/23644326/d307787a-0341-11e7-8815-8dd8f4eef66d.png)

Here is proof the cadastral tiles are coming down:
![image](https://cloud.githubusercontent.com/assets/24502866/23644360/fb1f2e2a-0341-11e7-8d69-1db257ae80a5.png)

I do see error messages from the app itself, from the URL http://localhost:8000/33a8ff5d647ae623da73.vendor.js:43

![image](https://cloud.githubusercontent.com/assets/24502866/23644413/2926a866-0342-11e7-92cf-3c6ad3e1e3fc.png)

Also I am not able to move layers around.  If I try dragging a layer as is shown in your UTube demo, nothing happens.

I'm also curious to know where the windows app persists the changes I make.  It would be good to start over from scratch, but I can't get rid of the previous changes I've made.  I can't use the web version of the app because it is using https and our vector layers are served using http.

Any help or advice would be greatly appreciated!

Tom Cuthill

**Comment by pathmapper** [comment]
> I can't use the web version of the app because it is using https and our vector layers are served using http.

Hi, I am using the web version of Maputnik without any problems with my own vector tiles served using http. What is exactly your problem with the web version?

**Comment by lukasmartinelli** [comment]
> I'm also curious to know where the windows app persists the changes I make. It would be good to start over from scratch, but I can't get rid of the previous changes I've made. I can't use the web version of the app because it is using https and our vector layers are served using http.

Windows is exactly the platform I cannot test myself.
It seems like one vendor file is not bundled up with the Windows EXE.

> Hi, I am using the web version of Maputnik without any problems with my own vector tiles served using http. What is exactly your problem with the web version?

Would be curious whether the problems still persist with the web version.
There is no information shared with anyone - everything is statically hosted on GitHub.

> I'm also curious to know where the windows app persists the changes I make. It would be good to start over from scratch, but I can't get rid of the previous changes I've made. I can't use the web version of the app because it is using https and our vector layers are served using http.

So the local version also supports updating a local style JSON file https://github.com/maputnik/editor/wiki/Maputnik-CLI.

You can also go back and forth between the changes with CTRL+Z and CTRL+Y.

**Comment by Tom-Cuthill** [comment]
I've used the web version and while I no longer see any errors about using http to get the tiles, the tiles still do not render.  Here are all the steps I followed exactly.  First I created the new source, which is a mapbox vector tile source:

![image](https://cloud.githubusercontent.com/assets/24502866/23693548/db65c4da-040f-11e7-9a39-0f3fe583cbbf.png)

Then I added in the cadastral layer using that source:

![image](https://cloud.githubusercontent.com/assets/24502866/23693583/13d466d2-0410-11e7-8f99-8a2a88f50f80.png)

Then I made the layer visible, and set the fill-outline-color to a blue. 

![image](https://cloud.githubusercontent.com/assets/24502866/23693614/3db7270a-0410-11e7-987e-09fc9612b659.png)

I can see the tiles loading properly using Google developer tools:

![image](https://cloud.githubusercontent.com/assets/24502866/23693632/5d50c1fc-0410-11e7-8a14-f454358e542a.png)

But I don't see any styling of the tiles on the map.  The tiles render fine in Openlayers 3.0.  Is there something obvious that I have done incorrectly?  I am still getting the same errors from the javascript:

![image](https://cloud.githubusercontent.com/assets/24502866/23693685/aea24436-0410-11e7-9739-a7013de22ccf.png)

We love the work you have done with Maputnik and we'd really like to use it to style our maps!

Any help much appreciated!
Tom

**Comment by Tom-Cuthill** [comment]
Are the cadastral tiles not displaying possibly because the gridset is EPSG:900913?  Would a geojson source work better than using mapbox compressed binary files?

We have a project starting up next week and we were really hoping to use Maputnik for our styling.  Any ideas would be greatly appreciated!

Cheers,
Tom

**Comment by lukasmartinelli** [comment]
> Are the cadastral tiles not displaying possibly because the gridset is EPSG:900913? Would a geojson source work better than using mapbox compressed binary files?

You should try to get it working with plain Mapbox GL JS like https://www.mapbox.com/mapbox-gl-js/example/vector-source/ and then go from there.
If that works it will work in Maputnik as well.

The error message looks like the tileserver is returning something fishy.

**Comment by Tom-Cuthill** [comment]
I followed your advice and I'm seeing the same behaviour in Mapbox GL JS.  I understand what is going on.  Geoserver serves tiles in TMS, where the tiles start counting from the bottom left corner like a mathematician would.  Google/OSM/Mapbox counts tiles starting from the top left (see https://alastaira.wordpress.com/2011/07/06/converting-tms-tile-coordinates-to-googlebingosm-tile-coordinates/).  As a result the y coordinate is not correct, which results in tiles which have no data.

This is not a problem in open layers, because it is clever enough to recognize that TMS is being used if there is a minus sign before the y value.

            var cadastralTileURL = this.powerOnMapURL +
                "/Western_Power_Demo:cadastre2" +
                "@EPSG%3A" + "900913" +
                "@pbf/{z}/{x}/{-y}.pbf";
            var cadastralTileOptions = {
                format: new ol.format.MVT({
                    featureClass: ol.Feature
                }),
                projection: 'EPSG:3857',
                cacheSize: 4096,
                tileGrid: ol.tilegrid.createXYZ({ maxZoom: 19 }),
                tilePixelRatio: 1,
                url: cadastralTileURL,
                crossOrigin: 'anonymous'
            };

It appears that mapbox is not as flexible.  There may be a way around this by using WMTS in geoserver instead of WTS.  I haven't had much luck getting this to work so far, but people should be warned that Maputnik won't work on tiles being served from Geoserver using WTS.

I'll let you know if I find a work around.

Cheers,
Tom

**Comment by Tom-Cuthill** [comment]
Only two lines of javascript would be needed to support the TMS standard, as it is done in Open Layers.  If the template for the y parameter has a 'minus' sign, then do the following:

var ymax - 1 << zoom;
var y = ymax - y - 1;

**Comment by orangemug** [comment]
Hey @Tom-Cuthill I'm a little confused of the status of this issue. Is this an issue with maputnik or mapbox-gl-js?

**Comment by lukasmartinelli** [comment]
No this is about using Mapbox GL JS :) ❤️
