### ISSUE TITLE
Add option for object literal style output instead of JSON style output

### ISSUE THREAD

**Issue by chriswhong** [maputnik/editor#103]
Maputnik is awesome, thanks for everyone's hard work.  

I am finding myself having to spend a lot of time cleaning up the style text when I copy and paste it into my codebase because I am not storing it as JSON, but rather as an object literal.  To avoid linting errors in javascript, I need to remove all of the double quotes from the keys, etc.

I propose adding the ability to toggle the output style between JSON and object literal so it can be more quickly pasted into projects.

**Comment by lukasmartinelli** [comment]
> I am finding myself having to spend a lot of time cleaning up the style text when I copy and paste it into my codebase because I am not storing it as JSON, but rather as an object literal. To avoid linting errors in javascript, I need to remove all of the double quotes from the keys, etc.

Isn't a JSON literal semantically the same as a object literal? But then the linter complains.

> I propose adding the ability to toggle the output style between JSON and object literal so it can be more quickly pasted into projects.

For me that's a feature too much. However you can work around this with your own tools.

1. Copy the object
2. Past it into the dev console and assign to a variable
3. JSON.stringify that variable 
4. Replace the quotes `JSON.stringify(obj, null, ' ').replace(/\"([^(\")"]+)\":/g,"$1:")`
5. Copy the cleaned up text

![aipprtjeyt](https://cloud.githubusercontent.com/assets/1288339/23662438/906c1332-031d-11e7-8c9d-959badbabb63.gif)

Check here http://stackoverflow.com/questions/11233498/json-stringify-without-quotes-on-properties

**Comment by orangemug** [comment]
@chriswhong also you can get most linters to ignore certain files or blocks of code. See http://stackoverflow.com/questions/12977661/is-there-a-way-to-suppress-jshint-warning-for-one-given-line

**Comment by orangemug** [comment]
This looks to be resolved, closing the issue.

**Comment by chriswhong** [comment]
Sorry for not responding to this one, thanks @lukasmartinelli for the tip on a quick regex in the console!
