### ISSUE TITLE
Can't add external Geojson

### ISSUE THREAD

**Issue by VoyteckPL** [maputnik/editor#106]
Here's my Geojson File.
http://mapaszlakow.eu/szlaki.geojson
when I add it as geojson source nothing happends. I tested it on geojson.io and it works fine.
Thanks in advance!

**Comment by SegFault0x0** [comment]
Remove the semi-colon from the end of your JSON file.

**Comment by orangemug** [comment]
It looks like @SegFault0x0 has mentioned the fix, closing the issue. 

Note: Once issue #54 is merged you'll get some feedback on errors.
