### ISSUE TITLE
Failing to serve maputnik through a reverse proxy

### ISSUE THREAD

**Issue by kalxas** [maputnik/editor#11]
Hi,

I have tried to proxy localhost:8888 to localhost/maputnik under apache and I am getting an empty page with "Loading..." message.
When building and moving to a static folder to serve from, I am getting the following error:
"Reference error: r is not defined"

Any ideas?
Thanks,
Angelos

**Comment by lukasmartinelli** [comment]
> I have tried to proxy localhost:8888 to localhost/maputnik under apache and I am getting an empty page with "Loading..." message.
> When building and moving to a static folder to serve from, I am getting the following error:
> "Reference error: r is not defined"

It is very early days but you can see how I do the hosting for the demo page here: https://github.com/maputnik/website

Check the demo folder: https://github.com/maputnik/website/tree/master/demo

**Comment by kalxas** [comment]
Thanks Lukas
Will try this and let you know

**Comment by lukasmartinelli** [comment]
@kalxas Is that still the case?
Try the public.zip HTML distribution otherwise in https://github.com/maputnik/editor/releases

**Comment by kalxas** [comment]
@lukasmartinelli thanks, I have not tested yet the latest version, on my todo list
