### ISSUE TITLE
Handle mapbox-gl-style-spec recently merged into mapbox-gl-js' repo

### ISSUE THREAD

**Issue by phiphou** [maputnik/editor#110]
[mapbox-gl-style-spec repo](https://github.com/mapbox/mapbox-gl-style-spec) has recently been merged with [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js)'s one. The last update of the style-specs are in this repo, so #108 still not working. 

Hope my explanations are clear and will make you find a way to correct this ;)

**Comment by lukasmartinelli** [comment]
Yeah we need to handle this big merge..

**Comment by lukasmartinelli** [comment]
If someone else wants to jump on this welcome!!!

**Comment by orangemug** [comment]
I have a working branch of this  https://github.com/maputnik/editor/compare/master...orangemug:fix/issue-110-update-mapbox-style-spec I still need to verify a few things before I raise a PR.

Note this still doesn't fix #108 because we'll need to make alterations to the ColorField component to make that work correctly.

**Comment by lukasmartinelli** [comment]
> I have a working branch of this master...orangemug:fix/issue-110-update-mapbox-style-spec I still need to verify a few things before I raise a PR.
> 
> Note this still doesn't fix #108 because we'll need to make alterations to the ColorField component to make that work correctly.

![giphy](https://cloud.githubusercontent.com/assets/1288339/24204800/eb77c07c-0eef-11e7-9bf8-5a35a4d76418.gif)

**Comment by orangemug** [comment]
I'll do this in 2 parts updating to the new style spec initially. @lukasmartinelli can you merge https://github.com/lukasmartinelli/mapbox-gl-inspect/pull/6 so I can update the current branch and make a PR

**Comment by lukasmartinelli** [comment]
> I'll do this in 2 parts updating to the new style spec initially. @lukasmartinelli can you merge lukasmartinelli/mapbox-gl-inspect#6 so I can update the current branch and make a PR

Done!

**Comment by orangemug** [comment]
PR #124

**Comment by orangemug** [comment]
PR #124 merged
