### ISSUE TITLE
"Upload file" crashes if "glyphs" is not set

### ISSUE THREAD

**Issue by nyurik** [maputnik/editor#113]
Trying to upload a style file to Maputnik causes an error in the console and silently gets ignored. Adding "glyphs": "https://free.tilehosting.com/fonts/{fontstack}/{range}.pbf?key={key}", to the style file solves the issue.
```
app.6759815ceb317e692c4a.js:54 Uncaught TypeError: Cannot read property 'replace' of undefined
    at e.value (app.6759815ceb317e692c4a.js:54)
    at e.value (app.6759815ceb317e692c4a.js:54)
    at FileReader.n.onload (app.6759815ceb317e692c4a.js:57)
```
File (I use it for the local installation): https://gist.githubusercontent.com/anonymous/b72a7d9cb286f92bef42477f1ce77c10/raw/39ad427812d10418e567622cb3ec9a27a61dc418/style.json
```js
key: "updateFonts",
value: function(t) {
    var e = this
      , o = this.state.mapStyle.metadata || {}
      , r = o["maputnik:openmaptiles_access_token"] || $.default.openmaptiles;
    (0,
    R.downloadGlyphsMetadata)(t.replace("{key}", r), function(t) {     // <<<<<<<<<<<<<<<<
        e.setState({
            spec: i(e.state.spec, "glyphs", t)
        })
    })
}
```

**Comment by orangemug** [comment]
It looks like @lukasmartinelli has fixed this, closing the issue.

**Comment by frodrigo** [comment]
Issue still present on version running at http://editor.openmaptiles.org

**Comment by pathmapper** [comment]
@frodrigo don't know how up-to-date http://editor.openmaptiles.org/ is.

Did you try it also with https://maputnik.github.io/releases/v1.1.0-beta4 ?

See also: https://github.com/maputnik/editor/issues/220

**Comment by frodrigo** [comment]
I use editor.openmaptiles.org because sometime my sources are not in httpS. And maputnik.github.io run only in httpS.
