### ISSUE TITLE
Unable to enter zoom field

### ISSUE THREAD

**Issue by nyurik** [maputnik/editor#116]
if my first zoom is set to 2, it is not possible to enter a second zoom above 10, because typing 1 automatically treats it as an error (it is lower than 2), and resets it to 10. I think the field should not reset on error, but instead show a red border/background, and wait for the user to leave the field. Once left, then you can reset the value.  Also, invalid field should be excluded from automatic refresh until it becomes valid again (either after leave+reset, or once the value is valid again)

**Comment by stevage** [comment]
It's annoying, but you can usually work around it with the right sequence of keystrokes. In this case, you could:

- type `9` in the second box, 
- then type a "1" before the `9`: `19`
- then select the `9` and change it to a `2`: `12`

**Comment by lukasmartinelli** [comment]
^ I usually work mostly in JSON mode for this kind of stuff.

**Comment by orangemug** [comment]
There is a work in progress branch here (waiting on #192 to be merged first). <https://github.com/orangemug/editor/compare/orangemug:fix/update-deps...fix/issue-116-zoom-field-v2?expand=1> this works by reordering the stops as you type. 

There is a demo here <https://48-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.572Crjw/build/index.html>. The current code breaks the data functions, I'll fix them if people are happy with the approach and submit a PR.

**Comment by nyurik** [comment]
Per @pjsier, this issue still exists for the function/data property fields. The #200 solves only a part of this issue.  See https://github.com/maputnik/editor/pull/200#issuecomment-348357952

**Comment by pathmapper** [comment]
The input bug is fixed, tracking the input ordering issue mentioned in https://github.com/maputnik/editor/pull/200#issuecomment-348357952 in #535.
