### ISSUE TITLE
Is possible to change source to local mbtiles?

### ISSUE THREAD

**Issue by joaokho** [maputnik/editor#12]
Maputnik editor > Source is "url": "https://osm2vectortiles.tileserver.com/v2.json"
It's possible to change to point to mbtiles file ?

**Comment by lukasmartinelli** [comment]
Well you still need to serve the MBTiles somewhere.
But it is totally possible to switch it to a localhost TileJSON URL! (well not from the online demo page).

We can think about building a small tileserver into https://github.com/maputnik/desktop.
To make it as easy as drop in a MBTiles into the same folder.

**Comment by lukasmartinelli** [comment]
@joaokho I think this will have low prio for now.
I might be confusing to understand the distinction between tileserver and editor if I build tileserving capabilities into the Maputnik binary.

You will need a tileserver if you host your own tiles anyway (like Tegola, T-Rex or Tileserver GL) and if you use a public tileset (thoughts in #17) you can still get started with a style. So for now this will have lower prio.

**Comment by muesliq** [comment]
I would see a tileserver beyond scope for an editor. Maybe a tutorial how to use it with existing tileserver software would be cool, though.

**Comment by lukasmartinelli** [comment]
> I would see a tileserver beyond scope for an editor. Maybe a tutorial how to use it with existing tileserver software would be cool, though.

I agree Helge.
