### ISSUE TITLE
Need an easy way to share styles

### ISSUE THREAD

**Issue by nyurik** [maputnik/editor#120]
Whenever I work with styles, I constantly need to share my style with others.  While it would be awesome to have git integration, pull requests, etc, available, the very basic usecase is to be able to send someone my work in progress, so that they can take a look at a specific issue / modify data source / recommend style change / file a bug with a permanent link to a style.

How can we make it so that uploading to GIST (for example) can be auto-loadable, without requiring the user to save the gist to a file and upload the file to the same editor?

**Comment by lukasmartinelli** [comment]
> Whenever I work with styles, I constantly need to share my style with others. While it would be awesome to have git integration, pull requests, etc, available, the very basic usecase is to be able to send someone my work in progress, so that they can take a look at a specific issue / modify data source / recommend style change / file a bug with a permanent link to a style.

I worked on the openmaptiles styles using the git mode. Encourage you to try it out https://github.com/maputnik/editor/wiki/Maputnik-CLI

> How can we make it so that uploading to GIST (for example) can be auto-loadable, without requiring the user to save the gist to a file and upload the file to the same editor?

You can already export a style to gist as implemented in https://github.com/maputnik/editor/pull/86!

**Comment by nyurik** [comment]
Thanks, I didn't see the CLI option!  But the main use case remains--am easy way to share work in progress. I saw that export is available, but there is no easy "import" -- user has to download the gist to their machine, and upload it to the editor

**Comment by lukasmartinelli** [comment]
You could append the URL to the gist to the `style` query param:

http://maputnik.com/editor/?style=https://rawgit.com/openmaptiles/dark-matter-gl-style/master/style.json#3.81/50.40/20.75

**Comment by orangemug** [comment]
Hey @nyurik is there anything we still need to discuss or can we close the issue?

**Comment by nyurik** [comment]
@orangemug I guess we can close this for now.  Ideally, loading from gist or url should be possible from the UI.

**Comment by orangemug** [comment]
That's a good point @nyurik, we'll leave it open then and add that to the open modal as a part of this ticket.

**Comment by muesliq** [comment]
Somehow related: #50
