### ISSUE TITLE
Per branch builds

### ISSUE THREAD

**Issue by orangemug** [maputnik/editor#123]
I would like per branch (or per commit) builds to allow users not familiar with the command line node, npm etc... to be able to try out features and fixes before they get merged.

I suggest we switch CI environments to <http://circleci.com> because it can serve up build artifacts. This is similar to https://github.com/tmcw/docbox (see the demo docs https://67-53007065-gh.circle-artifacts.com/0/tmp/circle-artifacts.NCC9T6a/index.html#our-api)

I'm also open to other suggestions if anyone is aware of any other services/tools.

Does anybody have any thoughts on this?

**Comment by lukasmartinelli** [comment]
> I would like per branch (or per commit) builds to allow users not familiar with the command line node, npm etc... to be able to try out features and fixes before they get merged.

I think one could even be able to configure this in Travis.
I like CircleCI too. No opinions there.

BTW. I usually publish the files for new releases to https://github.com/maputnik/website so they are on the online version of Maputnik.

**Comment by orangemug** [comment]
I looked to see if travis can serve up artifacts, but couldn't find that anywhere.

**Comment by lukasmartinelli** [comment]
> I looked to see if travis can serve up artifacts, but couldn't find that anywhere.

Oh you can. But you need a S3 bucket:

https://github.com/maputnik/desktop/blob/master/.travis.yml#L7-L10

**Comment by orangemug** [comment]
We are most of the way there now, Circle CI builds to the artifacts directory and you can get a link via the artifacts for a particular build see https://circleci.com/gh/orangemug/editor/4#artifacts/containers/0 for an example.

We just need to enable circle CI on the main repo, as its currently only enabled on my fork (@lukasmartinelli you should have a request to for perms via github)

The next stage is posting that link to the pull request comments via the github API.

**Comment by orangemug** [comment]
Hey @lukasmartinelli could you enable circleCI if you have the time. It would really help to quickly review pull requests like #161.

**Comment by orangemug** [comment]
> @orangemug no problem! Is there an issue out there for automating deployments with Travis? And, out of curiosity, is editor.openmaptiles.org pulling from the same source or is that updated separately?

@pjsier moving the convo from the other issue #164. So with the circleci (a slight hack but works great) we have per branch builds. See above

I would also like per tag builds to a the maputnik/website repo. The reason being that I always want a user to be able to revert to the previous version if we make a mistake. The number of devs on the project is quite small at the moment and I don't want non-developers to be stuck without a editor for days at a time.

I have no knowledge of editor.openmaptiles.org maybe @klokan knows???

Please feel free to raise a ticket for the auto deploy

**Comment by orangemug** [comment]
CircleCI and hence per branch builds are now enabled. You need to be logged in to see the build. You can see an example at <https://circleci.com/gh/maputnik/editor/1>
