### ISSUE TITLE
Text layout properties - add/remove font

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#129]
For adding optional fallback font(s) for a layer, one has to use the JSON editor at the moment. Maybe it would be possible to implement it directly in "Text layout properties", e.g. a "+" button that adds 
```
,
""
```
to the JSON style.

A "&#8722;" button could be used to delete an existing fallback font.
Current situation: When deleting the name of a fallback font in "Text layout properties", then 
```
,
""
```
remains in the JSON style.

**Comment by stevage** [comment]
Another motivating problem: every symbol layer has two fonts by default, and you can't remove the second one. That means you can't use orangemug's [excellent Github repo](https://github.com/orangemug/font-glyphs-v2/tree/gh-pages) because it doesn't support fetching multiple fonts at once (".../Open Sans,Arial Unicode/....").

(I'm not really clear why one needs fallback fonts, when all the glyphs are being fetched from the same server - why would the first one fail?)

**Comment by orangemug** [comment]
@stevage it's not really fallback fonts but rather fallback characters (glyphs). Its a little confusing let me explain.

Typefaces only support a part of the unicode character range, this support varies I believe https://www.google.com/get/noto is the only typeface to support it all. So when we are saying `Open Sans,Arial Unicode` what we're looking for is `Open Sans` if the character isn't supported then the glyph for `Arial Unicode` will be returned instead.

However the client (mapbox-gl-js) knows nothing about this but instead just sends a request for the font stack and the glyph range it's looking for. An example request might be `http://example.com/fonts/Open Sans,Arial Unicode/0-255.pbf` the server that deals with that request merges the glyphs from the font stack in the response.

There is support for this in https://github.com/klokantech/tileserver-gl and for more info on how they did that look at https://github.com/klokantech/tileserver-gl/blob/master/src/utils.js#L104

**Comment by orangemug** [comment]
As for the issue, although it would be nice to have multiple fonts supported until we have a public server that implements the above we are unable to implement this feature.

Note: For future reference we might be able to do an ugly hack once the [Service Worker API](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) is widely supported by intercepting the request.

**Comment by pathmapper** [comment]
> until we have a public server that implements the above we are unable to implement this feature.

[Maptiler](https://www.maptiler.com/cloud/) supports this: 
- https://maps.tilehosting.com/fonts/{fontstack}/{range}.pbf?key={key}

And there is also a hack available for hosting from static directory:
- https://github.com/apollo-mapping/ap-tilezen-mapbox-styles#deploying-and-generating-glyphsfonts
- https://github.com/m-abboud/fonts/commit/563f0dfc4519ae9ebbd7c2dbc9ae81ecd9ce078a

**Comment by pathmapper** [comment]
Fixed in #531
