### ISSUE TITLE
Confusing icons

### ISSUE THREAD

**Issue by severak** [maputnik/editor#13]
Up and down icons are bit confusing for the first time users.

Consider using classic open (suitcase) and save (floppy) icons instead.

**Comment by lukasmartinelli** [comment]
> Up and down icons are bit confusing for the first time users.
> 
> Consider using classic open (suitcase) and save (floppy) icons instead.

Agree. I want to always also provide text for the actions as well.
Only icons is a bad idea.

I like the action bar of Tangram Play.

![tangram_play](https://cloud.githubusercontent.com/assets/1288339/20595560/a7fb01cc-b23a-11e6-8890-522e570b0a27.png)

**Comment by lukasmartinelli** [comment]
I never only show icons now (except for the actions in the layers).

![screenshot from 2016-12-23 15-01-04](https://cloud.githubusercontent.com/assets/1288339/21455495/e6a306fc-c920-11e6-85a0-169211fc3406.png)
![screenshot from 2016-12-23 15-01-51](https://cloud.githubusercontent.com/assets/1288339/21455494/e6a2b42c-c920-11e6-827d-86dcc357ec09.png)
