### ISSUE TITLE
expand/collapse all layer groups

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#130]
It would be useful to be able to expand/collapse all layer groups with one click or keyboard shortcut. 

Current situation example: 
If you want to work on all symbol layers within a style, you have to expand all layer groups manually not to miss one of them.

**Comment by gregorywolanski** [comment]
I don't know where the icons used in Maputnik come from (@lukasmartinelli? @orangemug?) so I allowed myself to use text label.

What do you think about it working and looking like on the attached GIF?

I’m open to feedback before creating a pull request. :)

![2017-10-24 20_45_34](https://user-images.githubusercontent.com/787518/31961927-7f10b83c-b8fc-11e7-9059-8943812eeb96.gif)

**Comment by pathmapper** [comment]
@gregorywolanski wow, very nice! 

I like the place where you put the icon and I think your text label (Expand/Collapse) fits very well with the "Add Layer" button.

Thanks a lot!

**Comment by orangemug** [comment]
Merged @gregorywolanski PR #185 released in `v1.1.0-beta2` https://maputnik.github.io/releases/v1.1.0-beta2

Note: I'll release v1.1.0 properly (to https://maputnik.github.io/editor) once I've given everybody a change to raise any further issues.
