### ISSUE TITLE
source layer doesn't show drop down list

### ISSUE THREAD

**Issue by mapsgeek** [maputnik/editor#131]
i see in a video tutorial (Maputnik - Design Map Style from Scratch) that the source layer should give a list of the available layers in a source but this is not working for me and not even in the hosted version of the application when i choose (openmaptiles) as a source or any other source such as mapbox streets.
i'm also having a problem adding my own hosted vector-tiles as a source with .{x}/{y}/{z}.pbf end point

**Comment by lukasmartinelli** [comment]
The detecting layers in the source is kind of a hack. In order to know the layers we first need to look at the tiles and request them until we can populate the dropdown.

So when adding a brand new source that is not used in any layer - the dropdown sometimes stays empty.

**Comment by mapsgeek** [comment]
ok can you please give any hints about adding a source from a .pdf endpoint which comes that way
http://..../services/vector-tiles/KenyaCounties/{z}/{x}/{y}.pbf
nothing shows even in inspect mode

**Comment by orangemug** [comment]
@lukasmartinelli I think we can just grab the _source layers_ from the source definition json file.

There is a working branch here <https://github.com/orangemug/editor/compare/orangemug:fix/update-deps...orangemug:fix/source-layer-autocomplete> I'll submit a PR once https://github.com/maputnik/editor/pull/192 is merged.
