### ISSUE TITLE
CLI, --file not working

### ISSUE THREAD

**Issue by andreasflind** [maputnik/editor#137]
I've tried to set up a local CLI and wanted it to load my style. It says "style.json is accessible via Maputnik".
But when i access maputnik it just loads the basic style.

Im launching it with ./maputnik --file style.json

I've tried with different versions of maputnik and different styles.

**Comment by mathieudebrito** [comment]
I Have the same issue !
Any idea please ?

**Comment by stevage** [comment]
FWIW, that works ok for me with v1.0.1 on OSX. (There doesn't seem to be a downloadable binary for v1.0.2)

**Comment by mmuelder** [comment]
I'm having the same issue (1.0.1 linux)

**Comment by orangemug** [comment]
@lukasmartinelli archived the desktop repository, so I'm closing this issue. If anybody that wants [maputnik/desktop](https://github.com/maputnik/desktop) to live on, feel free to fork the repository.
