### ISSUE TITLE
Icon and font

### ISSUE THREAD

**Issue by exotfboy** [maputnik/editor#143]
How can I add custom icons for a layer, also I found that maputnik use custom glyphs instead of mapbox.

How do you build the glyphs(fonts)?

**Comment by orangemug** [comment]
You'll need to change the urls in the style settings modal

 - Sprite URL
 - Glyphs URL

I haven't used any friendly tools to do this myself. But the following look like a good place to start to generate the assets

 - https://github.com/sabas/genfontgl
 - https://github.com/mapbox/spritezero

I also created a little experiment to create typefaces and host on github pages see https://github.com/orangemug/font-glyphs ... although I'm not entirely sure I'd recommend that as they can get quite large.

**Comment by danger89** [comment]
A friendly tool to change the URL would be:
https://editor.openmaptiles.org/

**Comment by homa-varamin** [comment]
> A friendly tool to change the URL would be: https://editor.openmaptiles.org/
Thank You very much. 

New URL of maptiler online editor is :
https://cloud.maptiler.com/maps/editor
