### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by bartvde** [maputnik/editor#148]
As initially discussed here: https://github.com/maputnik/editor/pull/145#issuecomment-311118030

this ticket describes my use case for wanting to publish maputnik to npm.

So in my React-Redux based project I plan to integrate the LayerEditor component of Maputnik to facilitate symbology editing without having to write it from scratch. I can use a git connection string for now, but better would be to have actual releases get pushed to npmjs as well

**Comment by orangemug** [comment]
> So in my React-Redux based project I plan to integrate the LayerEditor component of Maputnik

@bartvde it would be great to get details of this if you are able to share. I've been meaning to raise a ticket for a while to ask everybody where all our (mainly @lukasmartinelli) hard work is getting put to good use.

**Comment by bartvde** [comment]
sure, it is still work in progress (prototype stages), but once we have it hammered out we will definitely share it

**Comment by bartvde** [comment]
We have an SDK (https://github.com/boundlessgeo/sdk) which we are porting over to use redux (it was still flux based) and want to use maputnik style editing components later on, my small prototype is here: https://github.com/bartvde/layerstore-test

**Comment by orangemug** [comment]
Maybe we should add a 'used by these people' section to our readme / new website.

Thoughts @lukasmartinelli ?

**Comment by orangemug** [comment]
Ok anyway back to npm publishing. We should definitely do this. I'll look to automate it via travis so tagged commits get auto published to npm, I think I've done this before... I'll have to dig through some old code and take a look. I think I'll need @lukasmartinelli to configure the private keys on travis also.

I'll have a look and report back.

**Comment by orangemug** [comment]
From <https://github.com/maputnik/editor/issues/164#issuecomment-335490639> 

> we have actually taken a different approach since and are not using maputnik anymore

Closing the issue for now if anyone needs this, please shout and we'll reopen.
