### ISSUE TITLE
Background doesn't change for OL 3

### ISSUE THREAD

**Issue by mimiqkz** [maputnik/editor#150]
I tried to change the color of the landscape in OL 3 through Background, but nothing seems to work.

**Comment by orangemug** [comment]
This is an old issue and is now fixed.

Note however that OpenLayers is somewhat still unsupported in Maputnik. There are bugs in https://github.com/boundlessgeo/ol-mapbox-style (which we use) and the editor itself. See [issues:"is:issue is:open label:openlayers"](https://github.com/maputnik/editor/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aopenlayers+) for an overview.
