### ISSUE TITLE
Mapzen tiles URL incorrect

### ISSUE THREAD

**Issue by stevage** [maputnik/editor#153]
When adding the Mapzen tiles as a data source, it proposes this URL:

`http://tile.mapzen.com/mapzen/vector/v1/{layers}/{z}/{x}/{y}.pbf?api_key=mapzen-RVcyVL7`

Two issues:

1. `{layers}` should be replaced, probably by `all`
2. `.pbf` should be `.mvt`

Hence:

http://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.mvt?api_key=mapzen-RVcyVL7

**Comment by lukasmartinelli** [comment]
Could you make a PR to fix this? You can search for mapzen in the code.

**Comment by pjsier** [comment]
@orangemug just to clarify, weren't we thinking of keeping this open as a reference for people? I'm fine with closing it since it's removed, but wanted to check

**Comment by orangemug** [comment]
@pjsier good spot, I've reopened the issue

If anyone would like to fix Mapzen please submit a PR.

**Comment by orangemug** [comment]
> Mapzen will cease operations at the end of January 2018

https://mapzen.com/blog/shutdown 😢

**Comment by lukasmartinelli** [comment]
Did we remove the mapzen tileset from the presets?

**Comment by pathmapper** [comment]
https://mapzen.com/blog/long-term-support-mapzen-maps/

**Comment by orangemug** [comment]
Thanks @pathmapper I've reopened this

**Comment by orangemug** [comment]
The first stage is to dig into the AWS 'Requester Pays' stuff. What changes would need to be made to Maputnik to integrate this?

Additionally I wonder if it would it be possible to get a sponsor to pay for requests made from `maputnik.github.io` so you'd only need to auth/pay when a user exports their style?

**Comment by orangemug** [comment]
I'm going to close this issue. I don't think getting a 'a sponsor to pay for requests made from maputnik.github.io' is likely to happen. Also these tiles will quickly get out of date, see

> archival December 2017 vector tiles for the entire world

If anyone disagrees please comment, and we'll reopen the ticket.
