### ISSUE TITLE
How to change the default editor map

### ISSUE THREAD

**Issue by DragonSuper** [maputnik/editor#154]
I open http://localhost:8888/ , will show default editor map。
But, I want to open  http://localhost:8888/,  will show my editor map .
And I can modify edited object  ，For example, I can edit AAA map，then I can edit BBBB map

**Comment by orangemug** [comment]
Hi @DragonSuper you can launch the editor with a `style` param if that helps. For example

```
http://maputnik.com/editor/?style=https://rawgit.com/openmaptiles/dark-matter-gl-style/master/style.json
```

There is some more discussion of that in issue #120. Does that solve your issue?
