### ISSUE TITLE
UI enhancement 

### ISSUE THREAD

**Issue by mapsgeek** [maputnik/editor#156]
in the add source panel, it should have a scrolling, because once you add a new source the close button disappear out of the screen and i find my self have to zoom out of the browser so i can see it again, and the more sources  you add the worth it gets.

![capture](https://user-images.githubusercontent.com/10188264/29620353-0368f406-881e-11e7-93ba-679438ec0678.JPG)
![capture2](https://user-images.githubusercontent.com/10188264/29620355-038cea46-881e-11e7-9592-3c2056fcd77f.JPG)

**Comment by lukasmartinelli** [comment]
Yes the source panel needs some rework to function properly when adding many sources.

**Comment by pjsier** [comment]
This was closed by #165. @orangemug I'm just going through and doing some housekeeping on issues that have been resolved

**Comment by orangemug** [comment]
Thanks @pjsier
