### ISSUE TITLE
Filter by relation

### ISSUE THREAD

**Issue by gorn** [maputnik/editor#157]
How can I filter ways which are in relation with type=route; route=hiking? I would like to style them differently.

**Comment by orangemug** [comment]
There is a 'filter' section in the UI

<img width="351" alt="157" src="https://user-images.githubusercontent.com/235915/31392963-79a3a178-add2-11e7-8cb8-e35fb5ae3b64.png">

If you load the [osm-liberty](https://github.com/lukasmartinelli/osm-liberty) style you should see lots of examples of its usage.

**Comment by gorn** [comment]
Is it checking tags from relation or the way itself?

I need to filter out 

- any way which belongs to relation 
- such that the relation has tags type=route & route=hiking

**Comment by tomass** [comment]
Maputnik (styling) works with vector tiles, which are produced by using geographic (for example OpenStreetMap) data. That is relations/ways and their tags are processed during the creation of vector tiles - **before** styling/maputnik comes into the picture.
That is information about routes has to be used in vector tile creation mechanism. There is nothing Maputnik can do about it. Choose vector tiles which provide you the information you need or build your own vector tile production server.

**Comment by orangemug** [comment]
Thanks @tomass, I didn't even consider this. @gorn if it's not in the vector tile data then maputnik can't see it. To check you can just enter the inspect mode and see what's available.

Does that make sense?

**Comment by orangemug** [comment]
I'm assuming the issue was that it wasn't in the underlying data source, closing the issue. @gorn if you have any more problems just leave a comment and we'll reopen the issue.
