### ISSUE TITLE
http://maputnik.com/editor/ site is not working

### ISSUE THREAD

**Issue by keum** [maputnik/editor#158]
Hello there, I'm not sure if this is a domain issue or something else is that's preventing from Maputnik site to work. 
thank you for looking into this.

**Comment by pathmapper** [comment]
Looks like the previous registry expiry date of the domain has been yesterday:

`Registry Expiry Date: 2017-09-20T11:30:39Z`

Currently maputnik.com shows:

![image](https://user-images.githubusercontent.com/20856381/30680648-2e5b5eda-9ea1-11e7-86fd-30ef34257a89.png)

@lukasmartinelli Did you extend the domain registry for maputnik.com?

**Comment by orangemug** [comment]
@lukasmartinelli I suggest we just remove the CNAME and use <http://maputnik.github.io> instead thoughts?

**Comment by luckydonald** [comment]
Now is one of _them_ sites:
![grafik](https://user-images.githubusercontent.com/2737108/30888720-5a1bf6e4-a322-11e7-9c4f-37969ac1f91f.png)

**Comment by lukasmartinelli** [comment]
Yup https://maputnik.github.io/ seems to work now. Will try to reactivate old domain in the meantime we can replace the links.

I like https://maputnik.github.io/ better. I just don't want to make maputnik.com a broken link though.

**Comment by orangemug** [comment]
> I like https://maputnik.github.io/ better. I just don't want to make maputnik.com a broken link though.

I think if you reactivate `https://maputnik.com` it'll start redirecting `https://maputnik.github.io -> https://maputnik.com` so I think we need to pick either one or the other. I think `maputnik.com` is everywhere so ideally we'd stick with that. @lukasmartinelli any luck with the domain?

**Comment by orangemug** [comment]
Hi @lukasmartinelli sorry it's me again. So I'd like to get maputnik working again, it's a little broken at the moment. I'm guessing the services are setup to have `https://maputnik.com` as the domain and are hence failing is an `403 unauthorized` and since `https://maputnik.com` is various places over the internet it'd be good to get this fixed.

Is there anything I can do to help? If payment is an issue I'm happy to pay for the next year.

If you're too busy, feel free to ignore this. I'll start to change over the urls if I don't hear anything on Thursday/Friday on the website and app to `https://maputnik.github.io/editor`.

**Comment by lukasmartinelli** [comment]
> If you're too busy, feel free to ignore this. I'll start to change over the urls if I don't hear anything on Thursday/Friday on the website and app to https://maputnik.github.io/editor.
>  👍 3

I want to move everything over to https://maputnik.github.io/editor.
I also don't like I bought the .com domain initially instead of .org.
If I get it back I will redirect to https://maputnik.github.io

**Comment by orangemug** [comment]
With #175 merged I think its changed everywhere except the https://github.com/maputnik/maputnik.github.io header

<img width="635" src="https://user-images.githubusercontent.com/235915/31616932-f28957b0-b285-11e7-9189-321e35e725ba.png">

@lukasmartinelli you're the only one with perms to change that. On that note any chance I can get admin perms to the repos?

**Comment by lukasmartinelli** [comment]
Finally got all 2FA recovered. Purchased domain back and will set up a redirect once done to https://maputnik.github.io.
<img width="633" alt="order_details" src="https://user-images.githubusercontent.com/1288339/31673105-58fefac6-b32c-11e7-98d5-00e99dcc05fc.png">


@orangemug done, changed link!

**Comment by orangemug** [comment]
Thanks @lukasmartinelli, I think we can close this issue now. Yay!

**Comment by lukasmartinelli** [comment]
http://maputnik.com/ now redirects! @orangemug @keum @pathmapper

**Comment by gregorywolanski** [comment]
http://maputnik.com redirects, but Google remembers the HTTPS (http**s**://maputnik.com) address. It’s high in the results for “maputnik”. When you click it, you get (in Chrome):

<img width="734" alt="1" src="https://user-images.githubusercontent.com/787518/40735163-c355a54a-643a-11e8-9a70-6d48e82320fb.png">

What can we do about it?

**Comment by pathmapper** [comment]
Currently the redirect is not working. @lukasmartinelli @orangemug 

Whoever is paying for the domain, is this still OK?

![image](https://user-images.githubusercontent.com/20856381/45913077-842a4000-be2c-11e8-9ab1-e86d411f9928.png)


whois maputnik.com
   ```
Domain Name: MAPUTNIK.COM
   Registry Domain ID: 2060580905_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.namecheap.com
   Registrar URL: http://www.namecheap.com
   Updated Date: 2018-09-21T07:20:29Z
   Creation Date: 2016-09-20T11:30:39Z
   Registry Expiry Date: 2019-09-20T11:30:39Z
   Registrar: NameCheap Inc.
   Registrar IANA ID: 1068
   Registrar Abuse Contact Email: abuse@namecheap.com
   Registrar Abuse Contact Phone: +1.6613102107
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: DNS101.REGISTRAR-SERVERS.COM
   Name Server: DNS102.REGISTRAR-SERVERS.COM
   DNSSEC: unsigned
   URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of whois database: 2018-09-22T03:52:47Z <<<

```

**Comment by orangemug** [comment]
@lukasmartinelli owns the maputnik.com domain

**Comment by lukasmartinelli** [comment]
On it! Trying to reactivate and bough it back. Checking in a bit again if nameservers updated 🙈 .

**Comment by pathmapper** [comment]
The redirect is working again, thanks @lukasmartinelli !

**Comment by pathmapper** [comment]
It's not working again, I guess it's the same issue as every year.

Would you mind having a look @lukasmartinelli?

**Comment by pathmapper** [comment]
Looks like someone took over http://www.maputnik.com/, there is now a Wordpress site running.

Given that 

>  I also don't like I bought the .com domain initially instead of .org.

this is not that bad :)

Closing here. Please leave a comment or reopen if the domain is still available for Maputnik.
