### ISSUE TITLE
Rasters with `tiles` defined throwing errors

### ISSUE THREAD

**Issue by chriswhong** [maputnik/editor#160]
When loading Maputnik with a complete style JSON via the `style` query param, my raster layers are throwing errors.

The sources are defined as 
```
aerials16: {
  type: "raster",
  tiles: [
    "https://domain/path/{z}/{x}/{y}.png"
  ],
  tileSize: 256,
},
```
Each raster source I try to load with configs like the above yields the following 3 errors:

<img width="700" alt="maputnik_" src="https://user-images.githubusercontent.com/1833820/31040434-6884a76e-a555-11e7-9ea5-e49f34d5f367.png">

It looks like it's expecting the `url` property to exist and that's causing problems.  I'll try to investigate more soon.

**Comment by orangemug** [comment]
@chriswhong this might be related to #124 give that branch a try, I'll also try and test / merge that PR over the weekend.

**Comment by chriswhong** [comment]
I tried #124 but saw the same issue.  FYI the rasters load as expected, it's just a bunch of errors that don't seem to actually break anything.

On further investigation, at some point my style, which has valid raster sources, is replaced with the invalid ones (raster sources with both a `url`(undefined) and a `tiles` value.

So I noticed the following warnings
<img width="463" alt="maputnik" src="https://user-images.githubusercontent.com/1833820/31212181-eab99620-a96c-11e7-8381-9d8b721f031c.png">
:

<img width="752" alt="maputnik" src="https://user-images.githubusercontent.com/1833820/31212092-4f2613fa-a96c-11e7-80a8-960cff64b88c.png">

The first warnings are where `App.jsx` tries to run `updateFonts()` and `updateGlyphs()`, I don't really get what these are doing, but they end up failing with mapbox:// urls

I believe that this "Rebuilding the style from scratch" is where the raster sources are being modified, and afterwards they throw errors.  So I guess the "Rebuilding the style from scratch" thing is a mapboxGL bug, but it's being triggered because it's trying to diff the "empty style" which has no fonts or glyphs with the new style which does.

**Comment by orangemug** [comment]
@chriswhong do you have a minimal test case that shows the issue?

**Comment by orangemug** [comment]
Hi @chriswhong did you get any further with this and is this still an issue?

**Comment by chriswhong** [comment]
No, It never caused a problem, just wanted to report the weird errors

**Comment by orangemug** [comment]
Ok thanks @chriswhong I've tracked down the lines in the mapbox-gl-js source

https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/map.js#L902
https://github.com/mapbox/mapbox-gl-js/blob/master/src/style/style.js#L440

I'll keep an eye out for this happening in the console.

**Comment by orangemug** [comment]
So the `Unable to perform style diff: Unimplemented: setSprite, setGlyphs` is valid see <https://github.com/mapbox/mapbox-gl-js/blob/b00d7e07c52a299190c2cd1c6c2d0cc6879e8e28/src/style/style.js#L37-L51>

@chriswhong you could try bumping mapbox-gl dep

**Comment by orangemug** [comment]
Can anybody still reproduce this issue? Or can we close it

**Comment by chriswhong** [comment]
Close it, hasn't bothered me lately
