### ISSUE TITLE
Add "Related Projects" links somewhere?

### ISSUE THREAD

**Issue by chriswhong** [maputnik/editor#162]
Hi, 

Our team at NYC Planning Labs (NYC Department of City Planning) has developed `maputnik-dev-server`, which we use to instantly open mapboxGL maps from our in-development apps in Maputnik.

https://github.com/nycplanning/labs-maputnik-dev-server

We wanted to share it with the community of Maputnik users, and are wondering if there is a good place to link to it from the wiki or perhaps the README.  

If there's a good spot for it, let me know and we'll do a pull request.

**Comment by orangemug** [comment]
@chriswhong `maputnik-dev-server` looks great! Definitely add a "Related Projects" section to the README. Above the sponsors seems like a good place to me.
