### ISSUE TITLE
Choose Fonts and Glyphs Endpoints

### ISSUE THREAD

**Issue by lukasmartinelli** [maputnik/editor#18]
For at least Mapbox GL you will need to choose your font/glyphs endpoint. 
https://www.mapbox.com/mapbox-gl-style-spec/#glyphs

Example:

Via HTTP

```
"glyphs": "https://orangemug.github.io/font-glyphs/glyphs/{fontstack}/{range}.pbf"
```

## Font Metadata Endpoint

It is not just enough to know the endpoint of the glyphs but one also wants to know which *fontstacks* are available.
Therefore everyone who hosts fonts needs to provide a font metadata endpoint delivering information in a format similar to this.

*Think more about format..*

```javascript
{
  "fonts": {
    //font family as keys and all fontstacks in array
    "Open Sans": ["Open Sans Bold Italic", "Open Sans Bold", ...]
}
```

@orangemug Would you like to think about a metadata endpoint and deploy it to your repo so we have a working implementation? You have already digged into fonts quite a bit :wink:

## Serve Fonts

Public fonts can be hosted via GitHub pages (where the metadata JSON file can be stored as well).

@orangemug has done some nice work on how to provide a fonts metadata endpoint from GitHub and serve the fonts through GitHub pages (more info in #10  and  https://github.com/lukasmartinelli/osm-liberty/issues/1).

- Repo is at https://github.com/orangemug/font-glyphs one can use the fonts like that `https://orangemug.github.io/font-glyphs/glyphs/{fontstack}/{range}.pbf`.
- I have started half a year back [back on something similar](http://glfonts.lukasmartinelli.ch/) https://github.com/lukasmartinelli/glfonts
- Petr has also worked on a merged Noto font one can use https://github.com/klokantech/klokantech-gl-fonts

## Choosing your Font Endpoint

Then in the settings you can choose your font endpoint.
**80% of the users will never need to change their font endpoint** - they will be just fine choosing
fonts from the default endpoint.

![font endpoint](https://cloud.githubusercontent.com/assets/1288339/20595287/a5b27a5e-b239-11e6-80fa-3e9bce84a382.png)

## Choose Font

In fields like `text-font` https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-text-font you will then choose the font. This is where the font endpoint comes into play to display all available fonts.

![choose font](https://cloud.githubusercontent.com/assets/1288339/20595469/4438ca84-b23a-11e6-94e5-5f4040f23d80.png)

**Comment by orangemug** [comment]
With regards to the font metadata endpoint, v2 of font-glyphs has implemented something similar https://orangemug.github.io/font-glyphs-v2/glyphs/index.json. 

Also apologies for the delay

**Comment by lukasmartinelli** [comment]
Font and glyph endpoint is done through the normal `glyphs` and `sprite` url of the style.
Optionally these endpoints can provide metadata.

If sprite url is `https://openmaptiles.github.io/fiord-color-gl-style/sprite` then we request the https://openmaptiles.github.io/fiord-color-gl-style/sprite.json file for the icons.

If glyphs url is `http://fonts.openmaptiles.org/{fontstack}/{range}.pbf` we request a http://fonts.openmaptiles.org/fontstacks.json file.
