### ISSUE TITLE
Most current version of software?

### ISSUE THREAD

**Issue by keum** [maputnik/editor#181]
Hello there, 
I'm curious as to what version of software running on the web https://maputnik.github.io/editor/#1.39/-0.0/0.4
Is this same as v1.0.2 from download page here? https://github.com/maputnik/editor/releases/tag/v1.0.2

thanks

**Comment by orangemug** [comment]
Hey @keum yeah it should be v1.0.2. I'm waiting for a response to #173 then we should have automated releases. If I don't get a response I'll push a release manually next week, we've had quite a few updates since that release.

I'll also look into putting in a version number somewhere in the UI. I'll leave this ticket open until those things are complete.

**Comment by keum** [comment]
thanks @orangemug!  also with update release, would it accompany with description of feature changes if there are any?  Really looking forward to it!

**Comment by orangemug** [comment]
@keum sure I'll try to write a changelog. A couple of questions for you

 1. Do you have any time to do some manual testing? Basically I need someone (other than me) to quickly check over the new release (when its ready) to check I haven't broken anything.
 2. If you'd like to share what you're using maputnik for in ticket #164 that'd be awesome.

If you have time for either it'd be very much appreciated, but I totally understand if you don't.   

**Note:** I'll try to add some automated functional tests next week

**Comment by keum** [comment]
Sure, I would love to test it out and use Maptunik to create some maps.  I don't really do any production work w/ maptunik...mostly trying to create various demos for folks to see the usefulness of maptunik and using various work flow.

**Comment by orangemug** [comment]
> mostly trying to create various demos for folks to see the usefulness of maptunik and using various work flow

I'd love to see anything you create, if you'd like to share #164 is the place
