### ISSUE TITLE
Changing order of layers in the editor

### ISSUE THREAD

**Issue by fawick** [maputnik/editor#182]
Not sure whether this should already be possible, i.e. whether this is bug or a feature request.

As a user, I would like to change the order of the styling rules by moving layers up or down in the list.

At the moment I edit my style with [maputnik/desktop](github.com/maputnik/desktop) and using `--file style-json --watch`, kill the Go-executable, order layers with `vim style.json`, and restart Maputnik.

**Comment by tomass** [comment]
When you move a mouse pointer over the layer type icon on the left side, pointer changes to direction-arrows. You can then move layer up or down while you hold the mouse button.
Does this work for you?

**Comment by fawick** [comment]
Thank you, that does indeed work on Linux/Firefox   I'm currently on. I wrote the issue from a Windows/Chrome box that I need to check  tomorrow. If it does work there, too, I'll close the issue. Otherwise I try to investigate and report back here.

**Comment by fawick** [comment]
So I tested and of course it works in Chrome, too. I was just too thick to find this interaction on my own.

**Comment by orangemug** [comment]
@fawick I totally missed this interaction the first couple of times using the editor also. It's not very obvious. If anyone else finds this ticket with the same issue please leave a comment and we'll try to make it a bit more obvious.
