### ISSUE TITLE
desktop: Add parameter for serving static files

### ISSUE THREAD

**Issue by fawick** [maputnik/editor#183]
This is in regard to [maputnik/desktop](https://github.com/maputnik/desktop).

I like to propose a parameter `--static` for maputnik/desktop](https://github.com/maputnik/desktop) that takes a directory  (e.g. `--static ./foo/bar`) and serves the contents of that directory with  [`http.FileServer`](https://golang.org/pkg/net/http/#FileServer)`(`[`http.Dir`](https://golang.org/pkg/net/http/#Dir)`(...))` under `/static`.

The intended purpose for `--static` is to be able to serve assets for the style that is designed, such as sprites and glyphs with the `http.Server` that maputnik needs to spawn anyway. For example, it would be possible to edit the sprites JSON file and/or the sprites PNG on the local disk and simply reload (F5) Maputnik in the browser to refresh the icons used in the style. (For the initial implementation I'd not include file watches for static assets, maybe these could be added later, too.)

If this is of intereset to the maintainers I'd be happy to contribute a PR to [maputnik/desktop](https://github.com/maputnik/desktop).

**Comment by fawick** [comment]
Dear @orangemug and @lukasmartinelli, I would really love to get your feedback on this issue, too.

**Comment by orangemug** [comment]
@lukasmartinelli archived the desktop repository, so I'm closing this issue. If anybody wants [maputnik/desktop](https://github.com/maputnik/desktop) to live on, feel free to fork the repository.

**Comment by zstadler** [comment]
> @lukasmartinelli archived the desktop repository, so I'm closing this issue. If anybody wants [maputnik/desktop](https://github.com/maputnik/desktop) to live on, feel free to fork the repository.

@orangemug,

It looks like Maputnik is still [alive](https://github.com/maputnik/desktop/commits/master) and [released](https://github.com/maputnik/editor/releases) by you. 

I would really like to see the https://github.com/maputnik/desktop/pull/2 PR merged in order to be able to use local sprite files with Maputnik Desktop.

**Comment by pathmapper** [comment]
Right @zstadler, Maputnik Desktop is alive again since some time (https://github.com/maputnik/editor/issues/360 for context).

Didn't had a closer look at https://github.com/maputnik/desktop/pull/2 until now, but there's some discussion so it looks like it's not ready to merge. 

Do you have any insights?

**Comment by zstadler** [comment]
As far as I can see, looking at https://github.com/maputnik/desktop/pull/2, there was a proposal to
1. Replace the `--static` flag with separate `--sprite` and `--glyphs` flags.
2. Each flag will serve a directory as `/sprite/` and `/glyphs/` respectively.
3. If Maputnik Desktop is invoked with a `--file` flag and any of these flags, override the `sprite` and `glyphs` definitions in the style with the respective flag's value.

The above proposal was not implemented.

It seems like 1 and 2 above are relatively easy to implement using the approach used for the `--static` flag.
I don't know about 3.

@pathmapper,
It would be great if the above proposal is implemented, but if it cannot, then please merge the existing implementation.

Integrating and tweaking new sprites into a style is very difficult without this feature.

**Comment by pathmapper** [comment]
@zstadler thanks, had a look, fresh PR in https://github.com/maputnik/desktop/pull/16.

If you want to try it out, you could download CLI binaries from https://github.com/maputnik/desktop/runs/903892411

![grafik](https://user-images.githubusercontent.com/20856381/88326199-169c1300-cd26-11ea-9d7a-9a25229bf8ea.png)

**Comment by zstadler** [comment]
@pathmapper 
Thanks for implementing this feature!
Sorry I was unable to test it before the merge.

**Comment by pathmapper** [comment]
@zstadler no worries, I tried it and didn't find any issues. If you'll see anything not working as expected, please open an issue to report.

Updated the binaries [here](https://github.com/maputnik/editor/releases/tag/v1.7.0) and moved the idea regarding params for sprite/glyphs to https://github.com/maputnik/editor/issues/715.
