### ISSUE TITLE
desktop: Integrate consbio/mbtilesserver

### ISSUE THREAD

**Issue by fawick** [maputnik/editor#184]
/cc @brendan-ward @consbio

This is in regard to [maputnik/desktop](https://github.com/maputnik/desktop).

I'd like to propose to vendor and integrate https://github.com/consbio/mbtileserver/ and use it in  [maputnik/desktop](https://github.com/maputnik/desktop) to serve `.mbtiles` sources directly with the Go HTTP server of [maputnik/desktop](https://github.com/maputnik/desktop). 

Basically, this would mean to refactor [mbtileserver](https://github.com/consbio/mbtileserver) so that it consists of a main- and a non-main-package, first, but that should not be too hard. I am going to create an issue for this at [mbtileserver](https://github.com/consbio/mbtileserver) as well.

Together with #183 this would basically make Maputnik a standalone tool for composing styles for data on the local machine.

**Comment by fawick** [comment]
I forgot to mention, [mbtileserver](https://github.com/consbio/mbtileserver)  is [licensed under ISC license](https://github.com/consbio/mbtileserver/blob/master/LICENSE) , which would be compatible with the MIT license used for Maputnik.

**Comment by fawick** [comment]
Dear @orangemug and @lukasmartinelli, I would really love to get your feedback on this issue.

**Comment by orangemug** [comment]
Hey @fawick I don't actually use or develop for maputnik/desktop I'm also not a golang developer, so I'll leave this up to others to comment.

**Comment by orangemug** [comment]
@lukasmartinelli archived the desktop repository, so I'm closing this issue. If anybody that wants [maputnik/desktop](https://github.com/maputnik/desktop) to live on, feel free to fork the repository.
