### ISSUE TITLE
Can get http://maputnik.github.io/editor/ to work

### ISSUE THREAD

**Issue by drenkan** [maputnik/editor#194]
Any thoughts why?

**Comment by orangemug** [comment]
It loads fine for me. If you're referring to http over https github pages doesn't allow http and auto redirects to https.

Do you have any more details?

**Comment by orangemug** [comment]
Although openmaptiles is also `http 522: Connection timed out` (`https://free.tilehosting.com/data/v3.json`) so if you're style is using that source the map won't be loading.

**Comment by drenkan** [comment]
Yes, I think it's the connection to https://free.tilehosting.com/data/v3.json thats not working for me. Can't seem to replace it with an alternative either, or do you think it will come live again? I can't get any map to show with presets on http://editor.openmaptiles.org/

**Comment by orangemug** [comment]
@drenkan they seem to have fixed it now. Closing issue, just add a comment if you get any further issues and we'll reopen.
