### ISSUE TITLE
when specific data will be available to view.

### ISSUE THREAD

**Issue by CraigglesO** [maputnik/editor#198]
Sorry if I am wasting your time, I just don't know who exactly to ask this question.

This doesn't really seem like a maputnik issue, but when I use mapbox studio styler, I can get national parks to show up at view 5, however with openmaptiles and maputnik, it won't show up till 6. These little nuances matter to me. And I don't know how to change it. I feel like it is a construct made when designing the map data itself?

I noticed when using tippecanoe, you can specify when data is viewable as well, so I guess I need to make edits at the database level?

**Comment by orangemug** [comment]
Hey @CraigglesO this looks correct to me. OpenMapTiles supports park polygons for zoom level 6+ you can see this in the docs here <https://openmaptiles.org/schema/#park> (click "Show Diagrams")

**Comment by CraigglesO** [comment]
Ah! I understand a little better now. Thank you for pointing this out, One more question, is it possible for me to edit parks to show up on z5? If I edit the file:
https://github.com/openmaptiles/openmaptiles/blob/master/layers/park/layer.sql
add:
```
        SELECT osm_id, geometry, leisure, boundary, NULL::int as scalerank
        FROM osm_park_polygon_gen8
        WHERE zoom_level = 5
        UNION ALL
```

Would this work?
Are there any tutorials. I realize this is not your problem, so feel free to close this if you don't have an easy answer.

Thanks for the help so far.

Craig.

**Comment by orangemug** [comment]
No problem, glad to help. The SQL question is probably one for the https://github.com/openmaptiles/openmaptiles issue tracker (I also don't really have many skills in that area)
