### ISSUE TITLE
Option to display the tile boundaries

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#202]
It would be useful to have an option to display the tile boundaries (https://www.mapbox.com/mapbox-gl-js/api/#map#showtileboundaries). See also: https://github.com/maputnik/editor/issues/41#issuecomment-338492789

**Comment by justenPalmer** [comment]
Where do you guys think this should be implemented in the interface? One potential option would be to automatically show tile boundaries when in inspect mode.

**Comment by pathmapper** [comment]
> automatically show tile boundaries when in inspect mode

I like your idea @justenPalmer. Personally I wouldn't need a toggle to switch them on/off.

**Comment by orangemug** [comment]
Would showing tile boundaries by default be confusing? I'm thinking that there are a number of straight lines and right angles on the map already, the US state boundaries for example.

Tile boundaries are not a thing you have to consider most of the time, I think it might just clutter the inspect view if enabled by default. Thoughts?

**Comment by pathmapper** [comment]
> Would showing tile boundaries by default be confusing?

You're right @orangemug . It really depends on the specific use case and the data.

A toggle to switch them on/off could be placed somewhere in the near of the existing controls, but I would be happy with any implementation.

![image](https://user-images.githubusercontent.com/20856381/35765390-efd78526-08c2-11e8-85f9-d9754ffe9c9b.png)

**Comment by pathmapper** [comment]
Or what about a context menu which opens on a right-click?

There could be also other settings located in such a context menu, e.g. a toggle to switch on/off the zoom control buttons on the map.

**Comment by orangemug** [comment]
@pathmapper In issue #252 I've outlined a small change to the UI. We could include a general 'debug' panel in that proposed UI in which you could turn on things like 'tile boundaries', thoughts?

**Comment by pathmapper** [comment]
:+1: for your suggestion @orangemug!

Maybe in such a 'debug' panel it could be also possible to turn on/off the map navigation controls and the zoom level information (default: on):


![auswahl_110](https://user-images.githubusercontent.com/20856381/38688207-d82ce4c0-3e78-11e8-8207-29cc0af31cbf.png)

Personally I don't use the navigation controls and the hash zoom level is sufficient for me. Having the ability to turn them off, it would be possible to have more of the map visible which would be useful on low resolution screens.

**Comment by orangemug** [comment]
@pathmapper the `master` branch now supports `?show-tile-boundaries` querystring parameter. I'll release a new version towards the end of the week.

This is a partial solution before we get around to a 'debug settings panel'

**Comment by kateler** [comment]
Is there an explanation somewhere for how to use this new feature? I tried tacking "?show-tile-boundaries" on to the end of the URL but it did nothing.

**Comment by orangemug** [comment]
No docs as it was intended to be a first pass, towards a UI. For those that need this feature https://maputnik.github.io/editor/?show-tile-boundaries=true#4.87/55.33/0.07 should give you want to need.

**Comment by kateler** [comment]
Thanks! Once I included the "=true" it worked.

**Comment by pathmapper** [comment]
> no debugging (tile boundaries/collision boxes/overdraw)

These three options are available now using a query parameter, closing here in favor of #460.
