### ISSUE TITLE
Add support for text-rotate property functions

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#203]
When opening a style with Maputnik using data-driven style property for text-rotate like

```
"text-rotate": {
                    "type": "identity",
                    "property": "ANGLE"
                }
```

the following error is displayed:

layers[_number_].layout.text-rotate: property functions not supported

Maybe also other property functions implemented in GL JS are not supported by Maputnik.

**Comment by orangemug** [comment]
@pathmapper do you have a link to a style showing the issue?

**Comment by pathmapper** [comment]
@orangemug here it is: [text-rotate.json.zip](https://github.com/maputnik/editor/files/1513979/text-rotate.json.zip)

I experienced it with the online version of Maputnik.

**Comment by pathmapper** [comment]
@orangemug thanks for the beta!
With https://maputnik.github.io/editor-v1.1.0-beta the error is gone, looks like the update to GL JS v.0.43.0 solved it.
