### ISSUE TITLE
localhost vector tiles support?

### ISSUE THREAD

**Issue by cdqrain** [maputnik/editor#208]
I have a Vector Tiles server on my native enviroment. The Address like this `http://localhost:5000/VectorTiles/layer/{z}/{x}/{y}`, it return mapbox spec vectortiles. How to add it as a Source ?

**Comment by pathmapper** [comment]
**Sources** -> **Add New Source**

![image](https://user-images.githubusercontent.com/20856381/33483733-825fab54-d69f-11e7-9504-30b6cb02029d.png)

**Comment by cdqrain** [comment]
I know, but after add the source, I can not see the map. when zoom in/out, the chrome Network can not capture request url.

**Comment by ImreSamu** [comment]
@cdqrain :  some debugging tips:
* vector is XYZ URL , so your link is not OK    ( "/{z}/{x}/{y}.pbf"  )
* Check in "Inspect Mode" 
*  [OSMLab QA Tiles (Mapbox )](http://osmlab.github.io/osm-qa-tiles/)   has only 1 zoom level [ z=12 ]  - so zoom in - zoom out is not working.

**Comment by orangemug** [comment]
This might be the http/https issue as described in #177. If you using `maputnik.github.io` I believe you'll only be able to use `https` tile sources due to the same-origin policy.

You should see warnings in the browsers inspector

**Comment by cdqrain** [comment]
@orangemug  I use maputnik in my local machine, should I change the tile server from HTTP to HTTPS?

**Comment by cdqrain** [comment]
@ImreSamu  I serve the vector tile from .NET Core WebAPI, the URL **MUST** be ended with `.pbf` ?

**Comment by orangemug** [comment]
@cdqrain if maputnik is served locally over `http://` then you can ignore my suggestion.

**Comment by cdqrain** [comment]
@orangemug But why maputnik can not request the source URL that I added?

**Comment by orangemug** [comment]
It'll probably be one of 2 things

 - The url you provide isn't returning the any of the correct data
 - Some permissions issue with the request

As @ImreSamu suggested, console and network logs from the browsers inspector will help diagnose the issue

**Comment by ImreSamu** [comment]
@cdqrain :  
>I serve the vector tile from .NET Core WebAPI, the URL MUST be ended with .pbf ?

Your vector tile URL should work from the browser or via wget.
see more (.mvt , .vector.pbf, .pbf): https://github.com/mapbox/vector-tile-spec/issues/69

You can replace manually the z/x/y values in your url, and you can test - it is working or not.

Sometimes it is a special link like `http://localhost:3000/my-test-data/14/4823/6160.vector.pbf?access_token=my-top-secret-key`, so you have to double check your server.

* Is it a static or dynamic server?  
* Is it working with other vector tiles viewer?

**Comment by cdqrain** [comment]
@ImreSamu  The issue is maputnik can not request the Vector Tiles. Chrome Network inspector is empty. 
I'm sure the tile server is working. I had used Leaflet.VectorGrid to view the tiles.

**Comment by orangemug** [comment]
Ok so a few more things that might help. Maputnik is really just a JSON editor so lets work backwards from that

 1. `Export -> Download` the style and check that the vector x/y/z source you expect is present the sources section of that JSON file.
 2. Have you created a layer that uses the source in your style?

**Comment by cdqrain** [comment]
@orangemug When I add a layer, it gives me some error
`warning.js:33 Warning: Failed prop type: The prop `value` is marked as required in `MinZoomBlock`, but its value is `undefined`.
    in MinZoomBlock (created by LayerEditor)
    in LayerEditor (created by App)
    in div (created by ScrollContainer)
    in ScrollContainer (created by AppLayout)
    in div (created by AppLayout)
    in div (created by AppLayout)
    in AppLayout (created by App)
    in App

 warning.js:33 Warning: Failed prop type: The prop `value` is marked as required in `MaxZoomBlock`, but its value is `undefined`.
    in MaxZoomBlock (created by LayerEditor)
    in LayerEditor (created by App)
    in div (created by ScrollContainer)
    in ScrollContainer (created by AppLayout)
    in div (created by AppLayout)
    in div (created by AppLayout)
    in AppLayout (created by App)
    in App

warning.js:33 Warning: Failed prop type: Invalid prop `value` supplied to `ZoomSpecProperty`.
    in ZoomSpecProperty (created by PropertyGroup)
    in PropertyGroup (created by LayerEditor)
    in div (created by Unknown)
    in Unknown (created by Collapse)
    in div (created by Unknown)
    in Unknown (created by Collapse)
    in Collapse (created by LayerEditorGroup)
    in div (created by LayerEditorGroup)
    in LayerEditorGroup (created by LayerEditor)
    in div (created by LayerEditor)
    in LayerEditor (created by App)
    in div (created by ScrollContainer)
    in ScrollContainer (created by AppLayout)
    in div (created by AppLayout)
    in div (created by AppLayout)
    in AppLayout (created by App)
    in App

Warning: Failed prop type: Invalid prop `value` supplied to `SpecField`.
    in SpecField (created by ZoomSpecProperty)
    in ZoomSpecProperty (created by PropertyGroup)
    in div (created by PropertyGroup)
    in PropertyGroup (created by LayerEditor)
    in div (created by Unknown)
    in Unknown (created by Collapse)
    in div (created by Unknown)
    in Unknown (created by Collapse)
    in Collapse (created by LayerEditorGroup)
    in div (created by LayerEditorGroup)
    in LayerEditorGroup (created by LayerEditor)
    in div (created by LayerEditor)
    in LayerEditor (created by App)
    in div (created by ScrollContainer)
    in ScrollContainer (created by AppLayout)
    in div (created by AppLayout)
    in div (created by AppLayout)
    in AppLayout (created by App)
    in App

mapbox-gl.js:233 [object ProgressEvent]
Evented.fire @ mapbox-gl.js:233
Evented.fire @ mapbox-gl.js:233
Evented.fire @ mapbox-gl.js:233
o._tileLoaded @ mapbox-gl.js:99
i @ mapbox-gl.js:105
Actor.receive @ mapbox-gl.js:213
`

**Comment by orangemug** [comment]
@cdqrain they are just warnings and look fine to me. Can you also provide the details requested in <https://github.com/maputnik/editor/issues/208#issuecomment-348887341>

**Comment by cdqrain** [comment]
@orangemug  Hi, Maputnik can request my VectorTiles when I add layer. But for my VT projection is EPSG:4326 that Mapbox GL does't support. So I still can not view the data. Is it possible that Mapbox GL can use EPSG4326?

**Comment by pathmapper** [comment]
@cdqrain 

> Maputnik can request my VectorTiles when I add layer

Good to hear, sounds like your issue here is solved.

> Is it possible that Mapbox GL can use EPSG4326

Never tried the following, but maybe they are good starting points:

- https://github.com/openmaptiles/openmaptiles/issues/179#issuecomment-283120867
- https://www.developmentseed.org/blog/2016/12/15/dirty-reprojectors/

**Comment by orangemug** [comment]
> Is it possible that Mapbox GL can use EPSG4326?

For anybody else finding this ticket, this comment provides a good answer  https://github.com/mapbox/mapbox-gl-js/issues/3184#issuecomment-321530150

**Comment by orangemug** [comment]
This looks to be resolved. Closing the ticket, just shout if I've missed something and I'll reopen.
