### ISSUE TITLE
Wiki: Link for for online version needs to be updated

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#211]
On all 6 wiki pages, e.g.:

![image](https://user-images.githubusercontent.com/20856381/33833803-2719c5d8-de81-11e7-95bd-27268fa638ed.png)

**Comment by orangemug** [comment]
I discussed this with @lukasmartinelli over xmas, we decided we're going to move back to http://maputnik.com. I'll close this ticket when that is complete.

**Comment by orangemug** [comment]
Updated links on wiki as I'm not going to move to `http://maputnik.com` any time soon. The initial use case was allowing loading sources via `http://`. However now we need to allow github login to export gists (see #269) which will require us to use `https://`
