### ISSUE TITLE
Preview Export to bl.ocks.org not working

### ISSUE THREAD

**Issue by keum** [maputnik/editor#212]
I'm trying to Preview stylized map using Export feature with Tilehosting https://www.tilehosting.com/ API and got it to work few weeks ago but now getting blank screen at bl.ocks.org site now. Anyone having similar issue?

**Comment by keum** [comment]
Currently using Export style option save to Gist preview link shows blank map as stated above, in our testing to downloaded file to display locally, we were able to show the basemap by changing 
https://api.mapbox.com/mapbox-gl-js/v0.28.0/mapbox-gl.js
https://api.mapbox.com/mapbox-gl-js/v0.28.0/mapbox-gl.css
v0.28.0 -> v0.43.0 
we would like this to be updated so upcoming Maputnik demonstration, people can display their map on-line using Export to preview function. 
Please help.

**Comment by orangemug** [comment]
> upcoming Maputnik demonstration
@keum I'll try find some time to sort it out. When is your demonstration?

**Comment by keum** [comment]
thanks @orangemug in two weeks. One solution is to download locally and change those api version to 0.43.0 and spin local web machine and open the map that way but...it's so much nicer w/ bl.ocks.org site and easier to share w/ other participants. thanks!

**Comment by keum** [comment]
@orangemug here is screen shots to tell what i'm describing in case it's not too clear. 

![image](https://user-images.githubusercontent.com/1133652/34616664-c65f34be-f1ed-11e7-9fc5-ebf734fcfa1f.png)

**Comment by keum** [comment]
@orangemug oops..forgot to add second image
![image](https://user-images.githubusercontent.com/1133652/34616734-f3156f6e-f1ed-11e7-8737-88b0a4bc7702.png)

thanks for looking into it. really appreciate it.

**Comment by orangemug** [comment]
Hey @keum I've made a beta v1.1.0 release with that changes you asked for, it is available at https://maputnik.github.io/editor-v1.1.0-beta I'll let some people give it a test before I release to `/editor` feel free to use <https://maputnik.github.io/editor-v1.1.0-beta> for your demo.

Sorry it took so long, I've been a little under the weather and haven't found any time. Hopefully I've got these to you just in time, for your demo.

**Comment by pkgeo** [comment]
hi @orangemug, thank you much! Yes, it works to export into blocks.org to preview fine. But i found another issue in your beta version.  In add layer dialog box, it appears that you can not select the source nor able to type in the source (only first letter shows up).  Thanks for all your work, really appreciate it!
![screen shot 2018-01-18 at 5 20 44 pm](https://user-images.githubusercontent.com/19844895/35130107-0247a16a-fc74-11e7-8ad8-1ae4914a49e6.png)

**Comment by orangemug** [comment]
@pkgeo thanks for the report, interestingly enough it does work use keyboard up down to select the source... Looking into this now.

If you have any spare time, a general test of the beta version would be much appreciated.

**Comment by orangemug** [comment]
The issues @pkgeo reported have been fixed. Released in `v1.1.0-beta2` see https://maputnik.github.io/releases/v1.1.0-beta2/

Note for @keum use https://maputnik.github.io/releases/v1.1.0-beta2
