### ISSUE TITLE
Still struggling with editing GeoJSON files

### ISSUE THREAD

**Issue by chebourne** [maputnik/editor#215]
Re: Adding GeoJSON files example video https://github.com/maputnik/editor/issues/210

Just got back to trying this again and still no luck. I even downloaded the example geojson files from geojson.xyz. stored them on a local web server (on port 80), ran Maputnik locally (on port 8000), added the geojson sources from the local server e.g. http://localhost/GeoJSON/ne_50m_ocean.geojson. So nothing on https, all on http and still no luck - nothing showing when entering inspect mode - geojson files appear to load ok:
![screenshot](https://user-images.githubusercontent.com/20801744/35049502-23d47ea2-fb98-11e7-89f3-f3aa01a47d04.png)
Style file resulting from this is attached as well - seems to be ok?
[1ng3z2vmw.zip](https://github.com/maputnik/editor/files/1639448/1ng3z2vmw.zip)
It seems people have replicated this problem - can anyone else take a look?

**Comment by keum** [comment]
Hi @chebourne, 
I had something similar when I was trying to load my own geojson file using http-server locally. I tracked this email I wrote while back. Hopefully this helps. I know it's not the actual solution but  solved the issue and I got it to display my own geojson(small enough file) to display locally run Maputnik for testing data purpose. Let me know if this works. 
*Try to add test.geojson --> test.geojson.txt then start http-server -p 9000 from that directory and get the url link http://localhost:9000/test.geojson.txt
and load that into your maptunik. Let me know if this works for you. 

>After wrestling it for few days, we've finally figured out why local geojson file wasn't showing up in locally run Maputnik.
>1. Using local data of facility.geojson did not loaded into Maptunik after using Http-Server w/ address like http://localhost:8080/facility.geojson
>2. After examining the header, we found that Http-server gives Content-Type:application/octet-stream;
>Conclusion:
We've changed the file name to facility.geojson.txt and served locally
as http://localhost:8080/facility.geojson.txt  IT LOADED beautifully into local Maputnik. 
so I'm going to rename my geojson file locally to add txt syntax and serve up to add Maputnik then stylize it.

**Comment by chebourne** [comment]
Hi @keum ,
Thanks for the advice but it did not make a difference - I couldn't even get the geojson.xyz URL's to work let alone local server.

However, I think I have solved the problem:

I use various privacy and tracking addons, particularly in Firefox, like Cookie Autodelete, Privacy Badger and uBlock Origin.

Disabling these for the sites concerned - not just the Maputnik editor site but local server AND geojson.xyz - solved the problem.

I'm not sure about the details of why - i'll try to look into that. Privacy Badger reported no tracking on any site so I don't think it's that. I suspect uBlock Origin is doing something odd due to all the cross site linkages.

I can now see geojson.xyz json files and my own json files within the online editor - hurrah!

**Comment by orangemug** [comment]
@chebourne sounds like your issue is solved. Closing the issue.

**Comment by JanC** [comment]
Hi,
I have the same problem. I'm running Maputnik on `127.0.0.1:8888` and a local apache on `localhost:8000` and when I add a local geojson source, I can see the following logs on the JavaScript console:

```
[Error] Origin http://127.0.0.1:8888 is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin http://127.0.0.1:8888 is not allowed by Access-Control-Allow-Origin. (ne_50m_ocean.json.txt, line 0)
[Error] XMLHttpRequest cannot load http://127.0.0.1:8000/ne_50m_ocean.json.txt due to access control checks.
[Error] Error: Error — mapbox-gl.js:526
	fire (bundle.js:40181:1250)
	fire (bundle.js:40181:1091)
	fire (bundle.js:40181:1091)
	(anonymous function) (bundle.js:39843:1335)
	(anonymous function) (bundle.js:39843:2026)
	receive (bundle.js:40161:894)
	(anonymous function)
[Error] Origin http://127.0.0.1:8888 is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin http://127.0.0.1:8888 is not allowed by Access-Control-Allow-Origin. (airspaces.json, line 0)
[Error] XMLHttpRequest cannot load http://127.0.0.1:8000/airspaces.json due to access control checks.
```
I do see the request to `"GET /ne_50m_ocean.json.txt HTTP/1.1" 200 2327565` in the Apache server though ..

I tried different browsers with all ad blocking disabled, renaming the json files but it does not help. Remote geojson work fine

**Comment by JanC** [comment]
ok solved: It looks like a server setting that needs to be changed .. or use this 

https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en%5D%5B1%5D

**Comment by AndyHuska** [comment]
if you're using a basic http server on localhost then this is an easy python solution, just run this script in the folder of your geojson files and customize the port in the script to meet your needs.
source- https://gist.github.com/acdha/925e9ffc3d74ad59c3ea

```
#!/usr/bin/env python3
# encoding: utf-8
"""Use instead of `python3 -m http.server` when you need CORS"""

from http.server import HTTPServer, SimpleHTTPRequestHandler


class CORSRequestHandler(SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET')
        self.send_header('Cache-Control', 'no-store, no-cache, must-revalidate')
        return super(CORSRequestHandler, self).end_headers()


httpd = HTTPServer(('localhost', 8003), CORSRequestHandler)
httpd.serve_forever()
```
