### ISSUE TITLE
Add support for expressions

### ISSUE THREAD

**Issue by orangemug** [maputnik/editor#223]
This ticket is here to start discussions around [expressions](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions). See <https://blog.mapbox.com/announcing-expressions-in-gl-js-a72b55d0a6af> for a good introduction to the subject.

Questions we need to answer

 - How are users currently using expressions, is the JSON editor sufficient?
 - If not how would you like to see expressions implemented?

Currently unsupported features, due to lack of expression support

 - `line-gradient`
 - `*-sort-key`

**Comment by orangemug** [comment]
I did a little bit of exploration around creating a mini language for the new expression syntax over in another repository <https://github.com/orangemug/simple-expr> you can see discussion in <https://github.com/orangemug/simple-expr/issues/1>

**Comment by pjsier** [comment]
I think it could be nice to have smaller JSON fields for authoring individual expressions, but that doesn't add a ton of value and could be a decent amount of effort. The mini-language could be interesting to try if people are interested, but in general I think the editor covers it

**Comment by orangemug** [comment]
Thanks @pjsier I expect you're right on this one. I'll leave the ticket open for others to comment

**Comment by justenPalmer** [comment]
![maplayers](https://user-images.githubusercontent.com/1915862/36048573-802dce7a-0d94-11e8-9034-b43c04125919.png)

Here's a quick UX comp for expressions I've been working on.

Expressions UI ideas:

- use color to separate types of expressions into categories
- use of lines and nodes to demonstrate relationships between expressions and their children
- values returned by expressions float right to make them stand out
- expressions are expandable and collapsable (click arrow to left of expression)
- use icons on values to define their type (" in example for strings)

Looking to open discussion about this UX

**Comment by orangemug** [comment]
So if I've got it right it's kind of a [scratch](https://scratch.mit.edu) like interface. I'd love to see a prototype, see how it feels to edit an expression. I think anything we develop in this area we'd need to see a prototyped out version first, outside the editor to see if it works (something like <https://orangemug.github.io/simple-expr/>)

Would you aim to support the entire syntax or a partial subset. Also things to consider/questions I have

 - "values returned by expressions float right to make them stand out" - I don't think this is possible. Expressions are based on the context of the map feature so couldn't be displayed in the UI.
 - The nesting could go pretty deep in an expression, how would that UI cope with that.
 - Why a language like UI rather than a mini language? I'm considering the popularity of spreadsheet formulas for example

**Comment by justenPalmer** [comment]
@orangemug, yeah I'll build a prototype to demonstrate the functionality.

Addressing your points:

- I would be aiming to support all expression functionality.
- As for the values returned by the expression, I'm referring to potential values that will be returned if the given conditions are met. For example, in the comp above, the color values that might be returned by the expression are "#FFFFFF" and "#FF0000". The expression will evaluate to one or the other depending on the layer features. We can align the potential values to the right to give the designer an at a glance idea of which colors could be returned by the expression.
- The design above does make good use of the horizontal space to allow for a lot of nesting, however, we do have to consider that nesting might go really deep. I've got some ideas on how the interface might handle deep trees, but will need to prototype them to see if they could work.
- As for UI vs mini-language - it comes down to usability. I do believe the expression syntax out of the box is difficult to use. Therefore, there is some opportunity to create an interface which makes expressions easier to understand and write. I'm striving to do just that with this interface, but until I have a working prototype I cannot prove that it will be easier in practice.

**Comment by orangemug** [comment]
> As for the values returned by the expression, I'm referring to potential values that will be returned if the given conditions are met. For example, in the comp above, the color values that might be returned by the expression are "#FFFFFF" and "#FF0000". The expression will evaluate to one or the other depending on the layer features. We can align the potential values to the right to give the designer an at a glance idea of which colors could be returned by the expression.

Yeah but you couldn't do that for an expression like the following. Or anything with values from the feature. This is the major usecase for mgl expressions (in my opinion)   

```
[
    "rgb",
    ["get", "score"],
    0,
    0
  ]
```

**Comment by orangemug** [comment]
> I'm striving to do just that with this interface, but until I have a working prototype I cannot prove that it will be easier in practice.

Can you point towards another applications where this type of approach has been successful? It might be useful to research products where this type interface exists currently.

**Comment by justenPalmer** [comment]
> Yeah but you couldn't do that for an expression like the following. Or anything with values from the feature. This is the major usecase for mgl expressions (in my opinion)

Good point. I didn't consider this use case in my comp. I'll take this into consideration when putting together future comps and the prototype.

> Can you point towards another applications where this type of approach has been successful? It might be useful to research products where this type interface exists currently.

I actually haven't found much in other applications that I can point to for this type of functionality. It is a complex tree of relationships which will require an innovative approach to make accessible. I do have extensive experience in the private sector designing and building applications which manage high levels of complexity and I look forward to applying my skills to tackle this challenge.

**Comment by justenPalmer** [comment]
@orangemug, ok I've got the first cut of an expression editor. You can see it and interact with it [here](https://justenpalmer.github.io/expression-editor/). Keep in mind this is still pretty rough and is missing some critical functionality (like JSON parse error notifications).

**Comment by sanjin-saric** [comment]
Whats the status on this? How can i help?

**Comment by orangemug** [comment]
Hey @sanjin-saric we basically just need to work out what we want from this feature. There are multiple ways we can do this, my suggestion is a tiny language see

 - https://orangemug.github.io/simple-expr/
 - https://orangemug.github.io/simple-expr/fmt.html

Others prefer a UI or simple code editor to enter JSON.

Basically what I'd like is some feedback from people who use the editor as to what they want. Since creating this ticket mapbox-gl expressions are are requirement for some fields. I believe [`line-gradient`](https://github.com/maputnik/editor/issues/292) is not very useful without an _interpolate expression_ for example. So maybe more important to get sorted than it was previously.

So to answer how you can help.

 - Get involved with discussion in this ticket to come up with a proposed solution of how we'd support expressions
 - Do research into other types of editor that have a similar requirements

**Comment by sanjin-saric** [comment]
Hmmm. I am also torn. On one hand I like the UI that the @justenPalmer came up with, I believe it can be really helpful. On the other, I'd like to see a raw text editor to begin with. 

Although I like the notion of a more semantic approach to adding expressions, I believe it will introduce issues and I would be more work to maintain when mapbox updates its expressions.

I am going to do a UX research on filters like this and try to add my two cents on the UI provided above.

**Comment by pathmapper** [comment]
Another option:

https://github.com/mapbox/expression-jamsession/

"Write Mapbox GL expressions in a more familiar, handwritable, spreadsheet-like, programming-like syntax. This library translates these handwritten formulas into valid spec-compliant Mapbox GL expressions that you can use in a Mapbox style."

**Comment by orangemug** [comment]
That looks very familiar to https://orangemug.github.io/simple-expr/ 😄 

Given that it's on the mapbox organisation account, it'll probably be the one that sticks. Let's monitor the repo for a couple of weeks see how it progresses.

**Comment by Benni5K** [comment]
As I worked a lot with nested (nasty) expressions the last days  I would like to add some words here. I think for expressions the mini language solution @orangemug promoted and the guys from mapbox propose is the more feasable one. This aproach is also the one that's used in common GIS software like QGIS to create rule based styling. Looking at one of my expressions pasted into @justenPalmer's prototype still gives me a light headache, even though it's a remarkable improvement compared to looking at it in a text editor. :-)
![unbenannt](https://user-images.githubusercontent.com/25839469/43839793-5412f40a-9b1f-11e8-9e9e-d3a6e74d0c23.PNG)

None the less @justenPalmer's solution could be a great solution to visualize nested filters on the UI as the syntax is less complex here with only a few comparision operators.

**Comment by gregorywolanski** [comment]
This issue appears in the answers to question “What annoys you about Maputnik?” in the survey (original spelling):

- No UI tool to generate expressions

**Comment by pathmapper** [comment]
> Let's monitor the repo for a couple of weeks see how it progresses.

No progress so far: https://github.com/mapbox/expression-jamsession/

I'm :+1: for https://orangemug.github.io/simple-expr/

**Comment by nspringer-alk** [comment]
For me the biggest benefit with Maputnik is the ability to adjust colors interactively with a color palette.  The biggest downside for me with expressions has been losing this ability.  Editing expressions for other properties in code is pretty straight forward.  I vote for any solution that preserves the ability to change colors interactively.

**Comment by sk1p** [comment]
> For me the biggest benefit with Maputnik is the ability to adjust colors interactively with a color palette. The biggest downside for me with expressions has been losing this ability

Maybe [something like the vs code color picker](https://mspoweruser.com/visual-studio-code-now-really-useful-color-picker-built/) could be useful inspiration?

> Can you point towards another applications where this type of approach has been successful? It might be useful to research products where this type interface exists currently.

The [blender node editor](https://docs.blender.org/manual/en/latest/editors/node_editor/introduction.html#introduction) comes to mind, although most nodes there are more high-level than those of the mapbox style spec.

**Comment by jonahadkins** [comment]
Hi! Thanks for keeping Maputnik **awesome**! I've been able to use some of the new filter syntax ( "get" )in the maputnik editor, but running into issues with on a large project trying to implement an expression.
```
[
          ">=",
          [
            "length",
            [
              "get",
              "ref"
            ]
          ],
            5
        ]
```

this expression allows me to filter based on the number of characters in the `"ref"` field for shield labeling. This is currently getting stripped out of my style when I load into Maputnik with the error `string expected, array found` . Judging by this issue, im guessing it's not supported yet. Just wanted to throw my use case in the mix and hoping it will be supported soon 🤞 .

**Comment by orangemug** [comment]
Hey all, so I mocked up a very basic expression UI keeping it as simple as possible 

Demo <https://2045-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html?style=https://s3-eu-west-1.amazonaws.com/tiles.os.uk/v2/styles/open-zoomstack-outdoor/style.json> - the 'town names' layer has some expressions.

A little walkthrough 

I've added a `Fx` button which turns the literal value into a textarea with the expression `["literal", "VALUE"]`, you can also revert this back to the original value (even it edited in the expression)    

<img width="349" alt="Screenshot 2020-01-29 at 09 03 18" src="https://user-images.githubusercontent.com/235915/73342458-84371d00-4276-11ea-81e8-0a981f124531.png">
<img width="350" alt="Screenshot 2020-01-29 at 09 03 29" src="https://user-images.githubusercontent.com/235915/73342465-88633a80-4276-11ea-93cc-10f4f35979ac.png">
<img width="348" alt="Screenshot 2020-01-29 at 09 03 04" src="https://user-images.githubusercontent.com/235915/73342453-80a39600-4276-11ea-98c6-f3a3f144590a.png">

I've also added inline errors because writing expressions is a little awkward so errors by the field seemed to make more sense. Note that this applies to normal fields also
 
<img width="347" alt="Screenshot 2020-01-29 at 09 02 29" src="https://user-images.githubusercontent.com/235915/73342446-7c777880-4276-11ea-8948-ecc2af8ad407.png">

Note that I'm aware there are lots of bugs at the moment, I'm interested in getting the simpliest UI initially then we can build from there. Things to fix

 - The expression textarea should be a codemirror editor (and probably full width)
 - The inline errors currently also display in the map UI
 - Bug with expressions

Problems I'm having which I could use some help with. The UI works out what to display based on the value of the property, this is where I'm a little stuck. I can't just check for an array (`["literal", "foo"]`) because that could also be a valid value for `text-font` and not an expression. I'm having difficulty defining the rules for what is an expression. I'm guessing the answer is to dig into the mapbox-gl-js codebase and see how it make the decision, but if anybody knows the rules or where to look it'd be a massive help.

Apart from that would this be an acceptable first pass of the UI if the bugs were fixed?

(working branch https://github.com/orangemug/editor/tree/feature/ui-errors-and-expressions)

**Comment by nspringer** [comment]
@orangemug this is a good UX solution.  While it requires knowledge of the MB expressions rather than an expression builder it is a great first step and something that is badly needed in Maputnik.  I wish I knew more React and could help, but I fully support this solution.

**Comment by orangemug** [comment]
There's a new build to try out https://2095-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html

Most of the bugs are fixed, still a few styling issues to fix and undo/redo is a little odd at the moment (I'll explain that later). Bugs listed from before

 - ~~The expression textarea should be a codemirror editor (and probably full width)~~
 - The inline errors currently also display in the map UI
 - ~~Various bugs with entering expressions~~

Any feedback is welcome and encouraged

**Comment by pathmapper** [comment]
Thanks for starting this @orangemug, some feedback

- for filters there is no possibility to use expressions
![grafik](https://user-images.githubusercontent.com/20856381/73609006-bc699300-45c9-11ea-9386-8e65e4400fb8.png)

- I find the `Fx` button intuitive for switching to "expression mode", but would favor something else than the trash can for switching back. This could also mean you want to delete the whole value.
![switch_expression](https://user-images.githubusercontent.com/20856381/73609051-2c781900-45ca-11ea-81c4-f37ba1f4f8e3.gif)

**Comment by orangemug** [comment]
> for filters there is no possibility to use expressions

Yeah that's probably quite important :). Let's get the rest of the UI solid and something we're happy with, then I'll add this.

> I find the Fx button intuitive for switching to "expression mode", but would favor something else than the trash can for switching back. This could also mean you want to delete the whole value.

How about 2 buttons a 'revert' button and a 'trash' button. Because we can only 'revert' if the value is a plain `['literal', VALUE]`, that however is really useful if you've just pressed the `Fx` button because you can have a 'revert' button near where the `Fx` button just was in the UI. Once the value differs from `["literal", VALUE]` we can disable the revert button in the UI. Thoughts?

**Comment by pathmapper** [comment]
> How about 2 buttons a 'revert' button and a 'trash' button.

Sounds good

**Comment by orangemug** [comment]
I've added a 'reset/undo' alongside the 'trash' button.

<img width="367" alt="Screenshot 2020-02-08 at 10 45 56" src="https://user-images.githubusercontent.com/235915/74083829-3a151f00-4a60-11ea-8803-40cd60b8ac7b.png">


Demo <https://2118-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.36/0/0> 

Does that UI make sense?

**Comment by orangemug** [comment]
Added `fx` button into layer filter.

<img width="367" alt="Screenshot 2020-02-09 at 17 13 15" src="https://user-images.githubusercontent.com/235915/74106502-7d09ec00-4b5f-11ea-8b1e-895f24799ea4.png">
<img width="366" alt="Screenshot 2020-02-09 at 17 10 48" src="https://user-images.githubusercontent.com/235915/74106500-7c715580-4b5f-11ea-87e7-b7f9d49a2711.png">

Updated build <https://2139-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.36/0/0>

**Comment by pathmapper** [comment]
Thanks @orangemug, currently playing around with it.

If you hover directly over the "disabled" reset/undo button, the mouser pointer changes and the disabled symbol is not visible anymore.

![undo_button](https://user-images.githubusercontent.com/20856381/74230195-2e299700-4cc4-11ea-997d-e6d56dad1ab3.gif)

**Comment by orangemug** [comment]
Hey @pathmapper, so I think I've landed on a solution that feels more 'correct'. The editor now has one 'map style' which it uses for all the editor UI (except for the map surface), this 'map style' can _valid_ or _invalid_. An _invalid_ 'map style' shows error messages in the UI as before.

The change is that the map surface, in the case of an _invalid_ style tries to render what it can. So with the attached [`broken_osm_liberty.json`](https://github.com/maputnik/editor/files/4210544/broken_osm_liberty.json.zip) the map will render everything but the invalid property showing an error both in the _layers_/_layer_ panel and the _error bar_ at the bottom of the map. Now the user can fix map style issues one by one and the map surface will update as these are fixed.     

The undo/redo functionality has been fixed with these changes because we're now using a single authoritative 'map style' as we were previously. This also means undo/redo works on an invalid style, so if you're fixing a style with multiple issues, you can undo during the process of fixing the style. 

Also, fixed the disabled button styling issue raised previously

Demo <https://2152-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.25/0/0>

**Comment by orangemug** [comment]
I've also just added inline errors for data/zoom functions

<img width="365" alt="Screenshot 2020-02-16 at 21 37 30" src="https://user-images.githubusercontent.com/235915/74613283-c7154380-5104-11ea-9762-f356700d4e43.png">
<img width="364" alt="Screenshot 2020-02-16 at 21 38 05" src="https://user-images.githubusercontent.com/235915/74613285-c7adda00-5104-11ea-9e3f-ca592a7127d5.png">

Note, that I'm aware the CSS is a bit off for data functions, that's next on my list

Demo <https://2179-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.25/0/0>
