### ISSUE TITLE
fetchSource has error

### ISSUE THREAD

**Issue by wxqqq** [maputnik/editor#224]
when i add a mapbox style
it include 
```source:{
   type:'vector',
  url:'mapbox://mapbox.mapbox-streets-v7',
....
}
```
the App.jsx 
fetchSources(){
}
![image](https://user-images.githubusercontent.com/8252997/35313503-ab178996-00fb-11e8-8340-2ac7507cb629.png)

fetch can't request like 'mapbox://'

**Comment by orangemug** [comment]
Thanks @xiaoq07. I think we need this function https://github.com/mapbox/mapbox-gl-js/blob/decea3f0b137953c1f8c3fa3d3b18cb61bb8469a/src/style/style.js#L159

**Comment by xiaoq07** [comment]
you are right!

**Comment by orangemug** [comment]
I've got a working solution for this, I'll make a PR shortly.

**Comment by orangemug** [comment]
@wxqqq branch build is here <https://201-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.BY8Bso5/build/index.html#0/0/0> if you'd like to test

**Comment by wxqqq** [comment]
it‘s  great, i will pull it
