### ISSUE TITLE
[v1.1.0 - beta 3: safari] Clicking open creates overlay which blocks the user from subsequent actions [screenshot]

### ISSUE THREAD

**Issue by ARolek** [maputnik/editor#225]
I'm using Safari version: 11.0.2. When clicking "Open" to load a style, the overlay does not appear to load correctly blocking the user for subsequent actions. 

<img width="1562" alt="screen shot 2018-01-24 at 4 02 00 pm" src="https://user-images.githubusercontent.com/667850/35363902-48e98406-0121-11e8-9ca3-11d16678f65d.png">

**Comment by orangemug** [comment]
Thanks @ARolek. This is fixed in PR #226. You can give it test here <https://199-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.4B9143b/build/index.html>. I'll release a beta4 when we have resolved the other outstanding issue.
