### ISSUE TITLE
Adding a style without Glyphs defined throws an exception with no feedback in interface

### ISSUE THREAD

**Issue by justenPalmer** [maputnik/editor#229]
To replicate, upload a style.json file without a property "glyph". Nothing happens in the interface and console logs the following exception:

Uncaught TypeError: Cannot read property 'replace' of undefined

**Comment by pathmapper** [comment]
@justenPalmer just to be sure: 
Does your style contains a layer which uses the `text-field` layout property?

From the [style-spec](https://www.mapbox.com/mapbox-gl-js/style-spec/#root-glyphs):

> This property is required if any layer uses the `text-field` layout property.

**Comment by justenPalmer** [comment]
Actually the style.json file I am using only has one layer defined which is the `background` layer. It has no `text-field` thus should not require the `glyph` property according to the spec.

**Comment by orangemug** [comment]
Fixed by @justenPalmer in #231
