### ISSUE TITLE
Uncaught TypeError: fs.readFileSync is not a function in mapbox index.js

### ISSUE THREAD

**Issue by coyotey** [maputnik/editor#23]
var fs = require('fs');
var path = require('path');

// readFileSync calls must be written out long-form for brfs.
module.exports = {
  debug: {
    **fragmentSource: fs.readFileSync(path.join(__dirname, 'src/debug.fragment.glsl'), 'utf8'),   //Uncaught TypeError: fs.readFileSync is not a function**
    vertexSource: fs.readFileSync(path.join(__dirname, 'src/debug.vertex.glsl'), 'utf8')
  },

**Comment by lukasmartinelli** [comment]
> var fs = require('fs');
> var path = require('path');
> 
> // readFileSync calls must be written out long-form for brfs.
> module.exports = {
> debug: {
> fragmentSource: fs.readFileSync(path.join(__dirname, 'src/debug.fragment.glsl'), 'utf8'), //Uncaught TypeError: fs.readFileSync is not a function
> vertexSource: fs.readFileSync(path.join(__dirname, 'src/debug.vertex.glsl'), 'utf8')
> },

Can you post your platform, Node version etc?
Node 4,5,6 and Linux, Windows, OSX are all working in continous integration.

**Comment by coyotey** [comment]
node  v4.6.0
Windows 10 X64

**Comment by lukasmartinelli** [comment]
> node v4.6.0
> Windows 10 X64

I can only test on Windows Server 2012 R2 (x64) via continous integration.

Do the following commands work?

```
md public
npm install
npm run build
```

I guess it's a build issue of Mapbox GL. But supporting everything on Windows is a bit difficult - that's why I will provide it as downloadable exe in the end.

**Comment by topwood** [comment]
I meet the same problem.

> node v4.2.3
> mac

**Comment by topwood** [comment]
I meet the same problem.

> node v4.2.3
> mac

it seems that node.js code has been bundled in the brower's javascript file

**Comment by lukasmartinelli** [comment]
With the newest Mapbox GL package this should be solved now.
