### ISSUE TITLE
Display version number in the UI

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#232]
Taken from https://github.com/maputnik/editor/issues/181#issuecomment-342886184 .

**Comment by orangemug** [comment]
What do you think? https://206-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.kK8mzg8/build/index.html

So it could either be visible like the above or hidden in a modal somewhere.

**Comment by pathmapper** [comment]
Wow, this was fast, thanks!

I really like it like this:

![image](https://user-images.githubusercontent.com/20856381/35651050-92ebb8f4-06de-11e8-84b0-e98da5b33fab.png)

> hidden in a modal somewhere.

Sorry, don't know what you mean exactly :-)

**Comment by orangemug** [comment]
> I really like it like this

That'll do then :)
