### ISSUE TITLE
Add option to export to a secret gist

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#238]
Currently the export to a gist is creating a public one: https://github.com/maputnik/editor/blob/32d808b2308c98e43cc30fc219f005b8bd1be87a/src/components/modals/ExportModal.jsx#L93

It would be nice to have also the option to create a [secret gist](https://help.github.com/articles/about-gists/#secret-gists).

**Comment by orangemug** [comment]
Pull request #241. See build here <https://211-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.ZbtmOiH/build/index.html>

Note that I made it private by default as that seems a better default. I think it'd be way to easy at the moment to publish sensitive data.

Thoughts?

**Comment by pathmapper** [comment]
Perfect! Thanks @orangemug !

>  I think it'd be way to easy at the moment to publish sensitive data.

Yeah, these were also my thoughts when making this proposal. Good you made it secret by default.

From the [docs](https://help.github.com/articles/about-gists/#secret-gists):

> Secret gists aren't private. If you send the URL of a secret gist to a friend, they'll be able to see it. However, if someone you don't know discovers the URL, they'll also be able to see your gist. If you need to keep your code away from prying eyes, you may want to create a private repository instead.

Therefore also the proposal in https://github.com/maputnik/editor/issues/239 to be able to delete a gist without contacting the GitHub support.
