### ISSUE TITLE
Would love to version number display

### ISSUE THREAD

**Issue by keum** [maputnik/editor#243]
Hello, It would be great to see current version number display on the header perhaps. 
This will be helpful in giving user support(folks using around our group) and any issue tracking w/ the version.  Thanks!
![maputnik-header](https://user-images.githubusercontent.com/1133652/35747941-0cd4b86e-0801-11e8-898f-6d0d7c3e070b.jpg)

**Comment by orangemug** [comment]
Already done in #232 😁

FYI I'm going to aim to release at most once every week. Mainly due to time constraints, but also the release is a nice opportunity to explain to people what's changed in the editor.

**Comment by keum** [comment]
Hi @orangemug, I'm sorry but I must be missing something, when i open my maputnik from here https://maputnik.github.io/ and launch Editor, where do you see it? mine doesn't display like the one from your example #232

**Comment by pathmapper** [comment]
Hi @keum, 
the PR https://github.com/maputnik/editor/pull/233 regarding the version number is merged and will be part of the next release.

This means it is not part of the current release v1.1.0 which is live here https://maputnik.github.io/editor/ but you are able to have a look a this demo https://206-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.kK8mzg8/build/index.html how it'll look like in the next release (then with a different version number of course).

**Comment by orangemug** [comment]
Hey @keum yeah @pathmapper is correct. My aim is moving forward to release every couple of weeks. Although I'd like to make it obvious for users of Maputnik the status of upcoming features/fixes. If anyone has any ideas of how we could communicate that please open a new ticket and add your thoughts.
