### ISSUE TITLE
Filtering more attributes

### ISSUE THREAD

**Issue by crazyingen** [maputnik/editor#250]
How can I filter the mtb:scale attribute?

**Comment by crazyingen** [comment]
Hello @pathmapper

Yes.

I am a newbee. I search a map, which show the surface or mtb:scale attribute. I found https://maputnik.github.io/. But the filter doesn't work.

**Comment by pathmapper** [comment]
@crazyingen https://maputnik.github.io/ is

> A free and open visual editor for the Mapbox GL styles targeted at developers and map designers.

See also: https://github.com/maputnik/editor#maputnik

I don't know your use case, but if you are searching for a map which shows `mtb:scale` you could have a look at:
https://openmtbmap.org/
https://openmtbmap.org/about-2/map-legend/

**Comment by crazyingen** [comment]
I found QGIS. With this program, I can do exactly what I want to do.
