### ISSUE TITLE
get name from package.json 

### ISSUE THREAD

**Issue by wxqqq** [maputnik/editor#251]
https://github.com/maputnik/editor/blob/df3a42accea53e1eaf2619c5bfe1497ae26eb7cd/src/components/Toolbar.jsx#L140

 you  can  set name to {pkgJson.name}, i think it's better

**Comment by orangemug** [comment]
You'd also need to add `text-transform: capitalize;` to a css class and add it to the containing element (see <https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform>)
