### ISSUE TITLE
Zoom snapping

### ISSUE THREAD

**Issue by orangemug** [maputnik/editor#256]
From @kateler in issue #252. Moved to a new ticket so we can track separately.

> As a frequent user of Maputnik, a feature I'd really like is two additional zoom buttons. Right now, the zoom buttons go up or down exactly one zoom level (e.g. from 15.43 to 16.43). I'd like the new buttons to go up or down to the next even zoom (e.g. from 15.43 to 16). Settings are usually made for the even zoom numbers, so I often want to get back to those after freely zooming with my scroll wheel.

**Comment by orangemug** [comment]
Hi @kateler thanks for raising the issue. That sounds like a great idea, although I'm a bit concerned about adding more buttons to the map UI (there's already another button on the way in another ticket).

As this seems like a power user feature how about using the modifier key instead. Something like `SHIFT + click` the zoom button to alter the zoom behaviour.

Thoughts? Any other ideas are welcome also, my main aim is to keep buttons on the map to a minimum.

**Comment by orangemug** [comment]
@kateler also if you would like to share what you've been using Maputnik for over in #164 it'd be very much appreciated (no pressure though)

**Comment by kateler** [comment]
I like the idea of a shift+click on the zoom buttons to save on screen real estate. Anything to save me from having to click into the URL and manually editing the zoom level! 

I can't share what I'm working on right now... maybe in the future.

**Comment by orangemug** [comment]
So @kateler it turns out that mapbox-gl supports this by default. Just press `+` or `-`when focused on the map interface.

**Comment by kateler** [comment]
That's perfect! Thanks for finding that out and sharing.

**Comment by orangemug** [comment]
No problem glad to help, closing issue.
