### ISSUE TITLE
Inspection Mode

### ISSUE THREAD

**Issue by lukasmartinelli** [maputnik/editor#26]
As proposed in #24 

> Inspect: I want to be able to choose a layer by clicking onto the map. This could be onclick (interferes with zoom though, so we'd need +/- controls on the map) or on right click (context menu) or behind an "Inspect" button. (I had expected this behind the current inspect button.) Despite the zoom interference I'd probably prefer onclick.

- [x] Assign different colors for each layer
- [x] On click feature detection to show popup
- [x] Show properties and vector layers
- [x] Show style layers

**Comment by lukasmartinelli** [comment]
If one click on "Inspect" now it switches to a view where each layer has a random color and one can inspect features.

![screenshot from 2016-12-24 23-09-39](https://cloud.githubusercontent.com/assets/1288339/21468906/21cdb3d6-ca2e-11e6-955e-0e83b096fdba.png)

This also works on the normal map when clicking on something (no clicking and automatically switching to that layer though).

![screenshot from 2016-12-24 23-11-09](https://cloud.githubusercontent.com/assets/1288339/21468908/44631cce-ca2e-11e6-801d-ce84459085dd.png)

**Comment by lukasmartinelli** [comment]
Improved the popups.

![screenshot from 2016-12-25 17-47-14](https://cloud.githubusercontent.com/assets/1288339/21472103/5ab1dbe0-caca-11e6-873d-e0975f662a0e.png)
![screenshot from 2016-12-25 17-47-01](https://cloud.githubusercontent.com/assets/1288339/21472104/5ab39fc0-caca-11e6-88c0-11e29baead44.png)

**Comment by lukasmartinelli** [comment]
The inspection mode is now contextual. With the current layer being highlighted and all others are much more transparent.

![screenshot from 2016-12-29 17-37-29](https://cloud.githubusercontent.com/assets/1288339/21548592/7e46f15a-cded-11e6-9c3f-8a7d4731ddef.png)
![screenshot from 2016-12-29 17-37-17](https://cloud.githubusercontent.com/assets/1288339/21548591/7e46b456-cded-11e6-8ff2-a73d67dbf277.png)
![screenshot from 2016-12-29 17-36-47](https://cloud.githubusercontent.com/assets/1288339/21548593/7e480d4c-cded-11e6-8dfb-f4e8a26c4274.png)

**Comment by Yahia1018** [comment]
Hi !

First of all, thanks for this incredible tool, it is very ergonomic and pleasant to use !

I just have a question, is it possible to select multiple layers when we are in Inspect mode ? If not, could it be possible to add this functionality ?

Thanks already !
