### ISSUE TITLE
Update "Latest Release"?

### ISSUE THREAD

**Issue by ARolek** [maputnik/editor#261]
Currently v1.0.2 is set as the "Latest Release" under the [Releases Tab](https://github.com/maputnik/editor/releases). Maybe change the tag to point to the v1.1.0 release?

**Comment by loicgasser** [comment]
Yes that would be useful. I saw you had tags, but a release creates a zip and tar.gz people can easily download and then build.
Having the tags it shouldn't be too long. Thanks in advance!
ping @orangemug

**Comment by orangemug** [comment]
Apologies for taking so long to get to this. `v1.2.0` is now released see

 - https://github.com/maputnik/editor/releases
 - https://maputnik.github.io/blog/2018/05/08/release-v1.2.0
