### ISSUE TITLE
Maputnik as talk at SOTM International 2018

### ISSUE THREAD

**Issue by lukasmartinelli** [maputnik/editor#264]
@orangemug I encourage you to submit a proposal for a talk for Maputnik on SOTM this year.
https://blog.openstreetmap.org/2018/01/11/session-proposals-sotm-2018/

Call for proposals ends this sunday.

**Comment by orangemug** [comment]
Hey @lukasmartinelli thanks for the heads up. Unfortunately I'm not a good public speaker, so it's not really something for me.

Although if anyone else would like to do a talk about Maputnik I'd love to see it

**Comment by orangemug** [comment]
The deadline for talk proposals was yesterday so I'm going to close this issue. I've got a few things to move about but I'm going to try to get along to the event (as a non-speaker).
