### ISSUE TITLE
March 19, 2018: GitHub disables anonymous gist creation

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#269]
https://github.com/blog/2503-deprecation-notice-removing-anonymous-gist-creation

So the currently implemented export to gist will only work until this date.

Possible replacement: https://github.com/maputnik/editor/issues/239

**Comment by orangemug** [comment]
Thanks @pathmapper that sets a target to sort out GitHub integration then 😁

**Comment by keum** [comment]
So has there been any changes to accommodate GitHub to disable anonymous gist creation?  I can still use using Blockbuilder.org under my own account to share the map and the style with others but it's more cumbersome but works for me.

**Comment by pathmapper** [comment]
Gist export was disabled in #290. 

Closing here, gist export is tracked in https://github.com/maputnik/editor/issues/239.
