### ISSUE TITLE
Interpolate values

### ISSUE THREAD

**Issue by tomass** [maputnik/editor#276]
It would be nice to be able to add/edit exponential values like these:
```
"paint": {
    "line-color": {
      "property": "basin",
      "stops": [
        [-300, "#66d4ff"],
        [-200, "#222222"],
        [-100, "#6687ff"],
        [ -99, "#bf66ff"]
      ],
      "type": "exponential"
    },
```

If such code is added manually in json editor, maputnik displays values (colours in this example):
![paveikslas](https://user-images.githubusercontent.com/969513/38493705-bb8254d8-3bfb-11e8-9273-a4bd55afd45f.png)

But I'm unable to see/change stop value and even trying to change colour gives an error:

> layers[2].paint.line-color.stops[0]: object stop key must have zoom
> layers[2].paint.line-color.stops[1]: object expected, number found

This is very usefull when creating different thematic maps. For example river basin maps where one property contains basin number and you want to visualise different basins with different colours without creating a different layer for different basin (which could mean a lot of layers).

**Comment by orangemug** [comment]
It looks like Maputnik requires you to provide a zoom level, which is incorrect as per the spec. I think the following will work... ish, not sure 🤔

```
"paint": {
    "line-color": {
      "property": "basin",
      "stops": [
        [{"zoom": 0, "value": -300}, "#66d4ff"],
        [{"zoom": 0, "value": -200}, "#222222"],
        [{"zoom": 0, "value": -100}, "#6687ff"],
        [{"zoom": 0, "value": -99}, "#bf66ff"]
      ],
      "type": "exponential"
    }
}
```

I believe the issue is that the UI doesn't support "Property functions" see <https://www.mapbox.com/mapbox-gl-js/style-spec/#other-function>

Pinging @pjsier as the original author, for any further insight (incase I'm getting this entirely wrong)

**Comment by orangemug** [comment]
Actually looking at it if you set `{"zoom": 0, ...}` seems to work as a slightly hacky workaround. @tomass can you confirm

**Comment by tomass** [comment]
@orangemug yes, confirmed! I can add, remove and change values.
