### ISSUE TITLE
Layer Comments

### ISSUE THREAD

**Issue by lukasmartinelli** [maputnik/editor#28]
As proposed in #24 

> > And one special wish: JSON doesn't support code comments, yet it would be nice to be able to save a comment within layers, so I'll later remember what I was thinking when deciding for specific values. This could be achieved via the metadata property:

- [ ] Add a new group for comments
- [ ] New component to modify the comment field in the metadata

**Comment by orangemug** [comment]
I thought'd I'd give this one a go. The diff is here https://github.com/maputnik/editor/compare/master...orangemug:feature/layer-comments 

It looks like this

<img width="344" alt="field" src="https://cloud.githubusercontent.com/assets/235915/23656576/2dfc84ba-0332-11e7-9e0c-6849df4c64b4.png">
<img width="343" alt="json" src="https://cloud.githubusercontent.com/assets/235915/23656577/2fdc60ca-0332-11e7-9a99-b20093685c72.png">

If it's on the right track let me know and I'll open a PR

**Comment by lukasmartinelli** [comment]
> If it's on the right track let me know and I'll open a PR

Hey you totally get the code!! Good stuff. This is a great entry level feature and looks good.
I like that you actually implement 👍 

I don't need this feature. It is up to you and @muesliq whether you want to merge that.
It seems definitely useful if one ever wants to generate docs out of a style spec.
I gave you write access to the repo.

**Comment by orangemug** [comment]
@muesliq is this what you had in mind? Is there anything wrong/missing?

**Comment by muesliq** [comment]
Great @orangemug!! Exactly like I thought. I'll merge it into master.
