### ISSUE TITLE
Creating similar to public.zip file

### ISSUE THREAD

**Issue by keum** [maputnik/editor#294]
Hi @orangemug I'm doing vector tiles to web mapping using Maputnik workshop http://sched.co/DQV0 and would like students to download Maputnik locally similar to V. 1.0.2 public.zip for the latest V.1.2.0.  Is it possible to have simple download zip file without building to be used in workshop?

**Comment by orangemug** [comment]
> I'm doing vector tiles to web mapping using Maputnik workshop http://sched.co/DQV0

That's so awesome! I'll publish to [releases](https://github.com/maputnik/editor/releases) later on today. If there is anything else you need (or would like) for the workshop feel free to comment in an existing ticket or raise a new ticket and I'll try to find some time to fix/dev anything you need.

Really cool to see Maputnik used in workshop 😁

**Comment by orangemug** [comment]
Released https://github.com/maputnik/editor/releases

**Comment by keum** [comment]
thanks! @orangemug for your help! i want people to understand the power of open source tool and show folks how one can do things without internet (no basemap) but you'll be able to grab all your data locally to stylize and build basemap with your own data, which is very important to gov't agencies. 
thanks again for pushing 1.2.0 and coordinating and making go with this project! i'll keep you posted on the workshop and will send out the link to the workshop once it's finalized.

**Comment by keum** [comment]
@orangemug thank you for publishing Public.zip file. just downloaded and ran it on my local machine without any problem and looks perfect! I'm hoping to create additional documentation on how to use Maputnik "easy user guide" after the workshop during the summer. Thanks again for all your work and having that file available..we'll be appreciate it during the workshop. will send some pics from it for sure :) cheers..
pk
