### ISSUE TITLE
Load & save from GitHub (repo / gist)

### ISSUE THREAD

**Issue by klokan** [maputnik/editor#3]
It would be really great to have a possibility to load / save from GitHub (repo or gist).

This gives the tool the most open and free online storage with complete editing history!

The complete functionality can be extracted from GeoJSON.io - http://geojson.io/ which is 100% open-source: https://github.com/mapbox/geojson.io (see [src/source](https://github.com/mapbox/geojson.io/tree/gh-pages/src/source))

It is pretty easy to implement with the GitHub API and authentication via GateKeeper (https://github.com/prose/gatekeeper - where geojson.io uses https://geojsonioauth.herokuapp.com).

**Comment by lukasmartinelli** [comment]
> It would be really great to have a possibility to load / save from GitHub (repo or gist).
> 
> This gives the tool the most open and free online storage with complete editing history!

Good idea for the online version!!

Want to think more about storage options - would also be possible to support a local filesystem if I wrap it in Electron.
So perhaps there are 3 storage options:

- local storage
- gist storage
- file storage (if a filesystem is available aka running in electron)

**Comment by stirringhalo** [comment]
To add onto this as I'm not sure if you're touching on it, I'd love to see it so that it also uses the webhooks of github to auto-update on push. For example, with http://45.56.99.211/, the style is auto-updated the second a push happens to the watched repo. With the editor, I have it simply triggered so that on push, it reboots the entire editor with the latest style from the repo.

**Comment by klokan** [comment]
The best-practice for how to store the GL styles and it's assets in editable form inside of GitHub repo / Gist is now defined at https://github.com/klokantech/gl-style-package-spec (implemented by @jirik)
Examples of such "gl-style" repos exist now - we have spent quite a lot of time on this already...

I am keen to have a web instance of the editor (ideally hosted on OpenMapTiles domain) with ability to load & edit & save in this format with GitHub as the storage.

**Comment by muesliq** [comment]
Would this mean that every keystroke (or field unfocus) becomes a GitHub commit?

**Comment by lukasmartinelli** [comment]
> Would this mean that every keystroke (or field unfocus) becomes a GitHub commit?

That would not be desirable - then we indeed need a Save/Export/Publish button. I do like the implicit saving though (and with the CTRL-Z/CTRL-Y you can always go back and forth).

**Comment by muesliq** [comment]
+1 for the save/export/publish/commit button ;-)

**Comment by lukasmartinelli** [comment]
@jirik completed this in https://github.com/maputnik/editor/pull/86

**Comment by klokan** [comment]
Only the anonymous gist is implemented.

The main target on this ticket was saving edits into a repository like https://github.com/openmaptiles/osm-bright-gl-style
