### ISSUE TITLE
Docker image shows "Invalid host header" 

### ISSUE THREAD

**Issue by Namec** [maputnik/editor#301]
Hello

my Maputnik Docker image was mount and runing wonderfully, and when trying to acess the UI from a dns name it won't work and shows "Invalid host header" , but when putting an ip adress instead of the dns it works !!

**Comment by claustres** [comment]
Maputnik uses https://webpack.js.org/configuration/dev-server/, so you have different options to solve this depending on your security and deployment concerns:
* https://webpack.js.org/configuration/dev-server/#devserver-disablehostcheck
* https://webpack.js.org/configuration/dev-server/#devserver-public
* https://webpack.js.org/configuration/dev-server/#devserver-allowedhosts

But you will need to override the default docker image, e.g. see [our own image](https://github.com/kalisio/k-maputnik).

**Comment by pathmapper** [comment]
@claustres thanks for your input!

Closing this issue, because I think we don't want to use `disablehostcheck` for our dockerfile, see https://github.com/maputnik/editor/issues/478#issuecomment-473512809.

If anyone disagrees, please leave a comment.
