### ISSUE TITLE
Text Offset Categorical

### ISSUE THREAD

**Issue by chebourne** [maputnik/editor#311]
Hi, I'm trying to offset some text on a symbol layer according to a field in the JSON source file. Here is the style code:
`    "text-field": {
      "stops": [
        [
          12,
          ""
        ],
        [
          13,
          "{name_en}"
        ],
        [
          14,
          "{name_en}"
        ]
      ]
    },
    "visibility": "visible",
    "text-anchor": "top",
    "text-offset": {
      "property": "{href}",
      "type": "categorical",
      "stops": [
        [
          {
            "zoom": 13,
            "value": 1
          },
          [
            0,
            0.6
          ]
        ],
        [
          {
            "zoom": 14,
            "value": 2
          },
          [
            0,
            2.5
          ]
        ]
      ],
      "default": [
        0,
        0.6
      ]
    },
    "text-size": {
      "stops": [
        [
          13,
          10
        ],
        [
          14,
          12
        ]
      ]
    },`

The 'href' field in the json is either 1 or 2 (referring to height of icons). The text is offset by 0.6 vertically but it does not offset to 2.5 at zoom level 14 - it just stays as 0.6. No errors are occurring.

Should this be working? Have I missed something to achieve this offset at zoom 14?

**Comment by orangemug** [comment]
Hey @chebourne I think you want to change `{href}` -> `href`

```
"text-offset": {
  "property": "href", 
  "type": "categorical",
  "stops": [
    [
      { "zoom": 13, "value": 1 },
      [ 0, 0.6 ]
    ],
    [
      { "zoom": 14, "value": 2 },
      [ 0, 2.5 ]
    ]
  ],
  "default": [ 0, 0.6 ]
},
```

**Comment by chebourne** [comment]
Orangemug, nope, that does not make any difference. Does anyone have an example where this works?

**Comment by orangemug** [comment]
So this is probably more of a _mapbox-gl-js_ spec question. As long as Maputnik is generating the correct JSON that's all Maputnik is really responsible for.

Saying that lets leave this open and get it sorted. So I tried a similar thing modifying the osm-liberty style to see if it works. The comment https://github.com/maputnik/editor/issues/311#issuecomment-394271619 was the result of that. Maybe try creating a reduced test case that you can share.

The easiest way is to take an existing open source style apply the change that doesn't see to work. Then export and share the style in the issue.

**Comment by orangemug** [comment]
There hasn't been any activity in this ticket for a while, so closing the issue. If you need further help, add a command and we'll reopen the issue.
