### ISSUE TITLE
A place to ask general Maputnik mapping questions 

### ISSUE THREAD

**Issue by orangemug** [maputnik/editor#325]
I'd like a better place to ask general Maputnik map creation questions, that are not features or bugs in the Maputnik editor.

@keum was interested in a place to ask these sort of questions (from #308)

> I have separate question about styling by data type, wonder if i need to write a ticket to the community and ask for it? want to catagorize symbol by field value. let me know how i should go about asking this of how-to?

I also believe that #311 falls into this category.

So hi everybody, some questions. Is there:

 - Something that already exists that we can point people towards
 - An existing service which we could setup for this purpose

Ideally something thats minimal to setup and easy to maintain.

**Comment by orangemug** [comment]
An initial idea from me. Setup another empty repository called `maputnik/questions` and point people towards the _issues_ in the repository. Thoughts?

**Comment by pathmapper** [comment]
What about using stackoverflow or gis.stackexchange?

There are already a few posts where maputnik is mentioned:
https://stackoverflow.com/search?q=maputnik
https://gis.stackexchange.com/search?q=maputnik

Someone could create a `maputnik` tag and we could users encourage to ask their questions there.
Maybe this way Maputnik gets also some more attention.

**Comment by orangemug** [comment]
@pathmapper I like the idea of <https://gis.stackexchange.com>. So I guess that would be for concrete questions?

> Question: How do I do [something] with Maputnik

From what I know from using stackoverflow they tend to close anything too general or not specific. Things like

> Question: How do I make [something] better
> Question: Are there any tools for doing [something]

Although that might be different for <https://gis.stackexchange.com>, are you an active user of <https://gis.stackexchange.com> if so what are your experiences?

**Comment by pathmapper** [comment]
I just started using it, so I'm not having any useful experiences.

Maybe @stevage could share his experiences?

**Comment by orangemug** [comment]
I think we should go with @pathmapper suggestion. Lets create a [CONTRIBUTING.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) and nudge anybody with a general questions there.
 
I had a little read and it looks like you need over 1500 reputation points to create tags. If anybody who has that many reputation points wants to create a maputnik tag on https://gis.stackexchange.com that be helpful

**Comment by stevage** [comment]
First, yeah, gis.se is the natural place to ask certain kinds of questions (but not all). I have the rep to create a tag, but usually you don't create a tag until there are already questions to tag. There don't seem to currently be any Maputnik questions for me to tag.

**Comment by orangemug** [comment]
Thanks @stevage 

> but usually you don't create a tag until there are already questions to tag

That makes sense, I'll create a `CONTRIBUTING.md` pushing users towards https://gis.stackexchange.com

**Comment by stevage** [comment]
Cool. Tell them to read https://gis.stackexchange.com/help/how-to-ask before they do, and to be mindful that they're asking in a general GIS forum, not a dedicated support channel. The mods of GIS.SE can be somewhat pedantic, so it's important they follow all the rules carefully.

**Comment by pathmapper** [comment]
Added a comment to our new issue template in https://github.com/maputnik/editor/pull/694/commits/9dad53e4449a4e20a3c8dc32f5e4c507af3920c5

> I'll create a CONTRIBUTING.md

@orangemug do you still want to create a `CONTRIBUTING.md` ? Otherwise we could close this issue here.

**Comment by orangemug** [comment]
I think issue template makes more sense, lets close this issue.
