### ISSUE TITLE
How client render tilemap image ?

### ISSUE THREAD

**Issue by phainv88** [maputnik/editor#327]
Hi Guy,
I am new about Maputnik. As i know, Maputnik read a source geojson which hosted in http://localhost:3000/geojson.json, and map style json. So i wonder how client request maptile images from  server
I expected Maputnik can render maptile images or MBTile

Thank you for reading

**Comment by pathmapper** [comment]
Hi @phainv88,

I'm not sure what you mean. You are able to select the Source Type here: 

![auswahl_124](https://user-images.githubusercontent.com/20856381/41350641-1f2e9ae6-6f14-11e8-9ed1-cdb7979ea013.png)

Does this answer your question?

**Comment by phainv88** [comment]
Thank you for your fast reply. My question is how can i export maptile after finish styling

**Comment by pathmapper** [comment]
Maputnik is a visual editor for Mapbox GL styles, so you are able to export the style but not the sources.

**Comment by phainv88** [comment]
Thanks, but i have some problems, pls help me
1. I have shapefile data, how can i use it in Mapuknit ?
2. After finish styling, what next i do for rendering maptiles?

**Comment by orangemug** [comment]
Hey @phainv88 the docs at <https://github.com/maputnik/editor/wiki> might help

**Comment by pathmapper** [comment]
There hasn't been any activity in this ticket for a while, so closing the issue. If you need further help, add a command and we'll reopen the issue.
