### ISSUE TITLE
Survey

### ISSUE THREAD

**Issue by gregorywolanski** [maputnik/editor#328]
I believe that Maputnik needs more contact with its users.

# The goal

To bring us, the makers of Maputnik, together with the users.

# The prototype

[Prototype of the survey](https://gregorywolanski.typeform.com/to/cPgaSY)

You can fill it out and submit it, it’s just a prototype. I’ll remove the test responses.

# How I want to promote the survey 

1. https://maputnik.github.io/editor
2. https://twitter.com/maputnik
3. https://twitter.com/lukmartinelli (?) CC @lukasmartinelli 
4. The next version of Maputnik?

# How I want to promote the survey inside Maputnik

![1](https://user-images.githubusercontent.com/787518/41369200-884c9ff2-6f44-11e8-84dd-75a07f831f54.png)

![2](https://user-images.githubusercontent.com/787518/41369207-8cfa1548-6f44-11e8-8ca8-5cb7b8e69ba0.png)

![4](https://user-images.githubusercontent.com/787518/41367560-aba4bd04-6f3f-11e8-9fcd-369d68164cc6.png)

![3](https://user-images.githubusercontent.com/787518/41367556-a8668fa0-6f3f-11e8-9ae2-9bee3c0fe96d.png)

The text from the modal window:

> You + Maputnik = Maputnik better for you
> 
> We don’t track you, so we don’t know how you use Maputnik. Help us make Maputnik better for you by completing a 7–minute survey carried out by our contributing designer.
> 
> Take the Maputnik Survey
> 
> It takes 7 minutes, tops! Every question is optional.

# What I need from you

It would be nice to see some answers to the following questions (you don’t have to answer all of them):

**a)** Do you think any of the questions are unnecessary?

**b)** Are there some questions I should add?

**c)** Do the words I chose work?

**d)** Do you want to know anything more about Maputnik users?

**e)** Do you think the method I’ve proposed for promoting the survey in Maputnik is both visible and non–invasive?*

\* The modal window for the survey will appear to users only once.

**Comment by orangemug** [comment]
Really nice survey @gregorywolanski

Answers to the questions

> a) Do you think any of the questions are unnecessary?

No

> b) Are there some questions I should add?

I'm unsure if this should be a new question or a modification of 'What do you use Maputnik for?'. What I'd like to find out it whether people use Maputnik for 

 - datavis
 - base maps
 - web or print
 - private in company or public on the internet

I just wonder if 'What do you use Maputnik for?' people are going to answer 'style maps' and it there is a way we can lead them into answering more specifically.

> c) Do the words I chose work?

The question

> What Maputnik alternatives do you know?

It is a little unclear what we're asking for here. Do we want to know what the participant has heard of or which ones they use? Maybe it should be either 'What Maputnik alternatives do you know of?' or 'What Maputnik alternatives do you use?', or maybe both, thoughts?


> d) Do you want to know anything more about Maputnik users?

Just what's outlined in `(b)` above


> e) Do you think the method I’ve proposed for promoting the survey in Maputnik is both visible and non–invasive?*

Yup I'm happy with the proposed promotion.

**Comment by gregorywolanski** [comment]
Thank you, @orangemug! :)

>> b) Are there some questions I should add?
> 
> I'm unsure if this should be a new question or a modification of 'What do you use Maputnik for?'. What I'd like to find out it whether people use Maputnik for
> 
> datavis
> base maps
> web or print
> private in company or public on the internet
> I just wonder if 'What do you use Maputnik for?' people are going to answer 'style maps' and it there is a way we can lead them into answering more specifically.

I read you. I believe we will be able to read it from the answers for the “What do you use Maputnik for?” question.

I could add your questions as a description to the “What do you use Maputnik for?” question, but I’m afraid that it could make the quality of the answers for this open question worse (directed, biased). What do you think?

>> What Maputnik alternatives do you know?
> 
> It is a little unclear what we're asking for here. Do we want to know what the participant has heard of or which ones they use? Maybe it should be either 'What Maputnik alternatives do you know of?' or 'What Maputnik alternatives do you use?', or maybe both, thoughts?

At this point, I want to know what the participant has heard of. 

“What Maputnik alternatives do you know of?” might be better here, but I’m not a native speaker to assess. :)

**Comment by orangemug** [comment]
> I could add your questions as a description to the “What do you use Maputnik for?” question, but I’m afraid that it could make the quality of the answers for this open question worse (directed, biased). What do you think?

Good point. It was a minor thing anyway, I'm happy if you're happy :)

> At this point, I want to know what the participant has heard of.
> 
> “What Maputnik alternatives do you know of?” might be better here, but I’m not a native speaker to assess. :)

To me "What Maputnik alternatives do you know?" read as "what do I know" in the same way someone would say "I know javascript" it hints at you have a deeper knowledge of the subject. "What Maputnik alternatives do you know of?" seems better to me

**Comment by gregorywolanski** [comment]
@orangemug 

> To me "What Maputnik alternatives do you know?" read as "what do I know" in the same way someone would say "I know javascript" it hints at you have a deeper knowledge of the subject. "What Maputnik alternatives do you know of?" seems better to me

The question updated in the [prototype](https://gregorywolanski.typeform.com/to/cPgaSY). :)

Thanks for your feedback!

**Comment by gregorywolanski** [comment]
@lukasmartinelli? @pjsier? @jirik? @bartvde? @tbarsballe? @oterral? @justenPalmer? @tschaub? @tobinbradley? @cmarqu? @chriswhong? @nyurik? @albertov? @muesliq? @PetersonGIS? @chrissng? @tmcw? @tyrasd? @alicoding?

**Comment by alicoding** [comment]
Probably got wrong Ali here? :)

**Comment by gregorywolanski** [comment]
@alicoding I mentioned you because of [commit](https://github.com/maputnik/editor/commit/d5c252ee54ea860830fe71fc9ffc20eca7d6d853). :)

**Comment by alicoding** [comment]
@gregorywolanski gotcha :D It was probably a commit from my starter project there. 👍

**Comment by muesliq** [comment]
I'd add open questions like:

What is the one thing that nearly keeps/kept you from using Maputnik?

**Comment by gregorywolanski** [comment]
Thanks, @muesliq! :) I’m super excited that you joined the discussion! :D

>I'd add open questions like:
>
>What is the one thing that nearly keeps/kept you from using Maputnik?

Could you please write more about your motivation for adding this question? Is this your case? Do you know someone in this scenario?

**Comment by muesliq** [comment]
> Could you please write more about your motivation for adding this question?

In my experience this question is the one most valuable question (no matter which product) when collecting feedback. Asking "What features would you like to have" will get people creative and they will tell you their ideas, regardless if those features will *really* matter to them. But finding out what (almost) kept somebody from using/buying your product will get you feedback that matters.

> Is this your case?

Our customers can choose between Maputnik and our own, self-made code-based editor. I prefer the latter but that's more of a power-user option. What personally keeps me from using Maputnik is: Too much GUI ;-) But I appreciate Maputnik for that very reason as an option for less code-savvy customers of ours.

**Comment by orangemug** [comment]
> What is the one thing that nearly keeps/kept you from using Maputnik?

I like this idea. I know from my own experience, I keep returning to tools over the years again and again. I like them in principal but they've never quite done what I want/need.

**Comment by gregorywolanski** [comment]
> What is the one thing that nearly keeps/kept you from using Maputnik?

Three thoughts:

1. The survey is addressed to the Maputnik users. I don’t think that we are going to reach with it many almost–Maputnik–users – that’s a little bit outside of the scope of this particular survey. Survey for almost–Maputnik–users is a great idea for another survey. :)

2. It’s my personal impression: I sense a negative vibe from this question. :/ I tried to rewrite it a few times, without luck. :(

3. Do you (@muesliq, @orangemug, others) believe that “What is the one thing that nearly keeps/kept you from using Maputnik?” is different enough from “What annoys you about Maputnik?” in a such short survey to add the first question?

**Comment by gregorywolanski** [comment]
Update:

- 82 responses so far

- 336 unique visits

- I just added [issues, comments, and labels from the survey](https://github.com/maputnik/editor/issues?q=label%3A%22mentioned+in+the+1st+survey%22)

- I will publish results on https://maputnik.github.io/blog/ once I collect 100 responses

**Comment by pathmapper** [comment]
Hi @gregorywolanski ,

I've read your story :smile:: https://www.gregorywolanski.com/portfolio/maputnik

I wonder what the following means:

> so this survey ends my involvement in the project

Do you still get and evaluate the responses from the current survey or is there no more action from your side in this regard?

**Comment by gregorywolanski** [comment]
@orangemug gets the responses. :)

**Comment by pathmapper** [comment]
OK, cool, thanks for your quick reply and all your help!

**Comment by pathmapper** [comment]
@gregorywolanski if we would like to create a new survey (e.g. with different questions) some day in the future, it would be really nice if we would be able to do this based on your impressive design work if you agree.

Would you mind if we store e.g. the background image and maybe other assets needed for such a typeform survey on https://github.com/maputnik/design?

If you don't feel comfortable doing so, that's fine. I just wanted to ask with the aim to preserve your work for the future (and make it easier for Maputnik maintainer and contributors of course :smile:).

**Comment by gregorywolanski** [comment]
Thank you for your kind words, @pathmapper, but the background image is one of the default backgrounds from typeform.com. :)

I haven't created any assets around the survey – just ideas, code & execution.

**Comment by kylebarron** [comment]
By the way, a link to the survey still shows up on the editor, but it looks like the survey has closed:
![image](https://user-images.githubusercontent.com/15164633/70826934-5de01f80-1da5-11ea-9b50-401e7fa87039.png)

**Comment by pathmapper** [comment]
Thanks for reporting @kylebarron.

@orangemug @gregorywolanski any idea what's the reason for this? Should we remove the survey from the editor or will it be available again?

**Comment by nextstopsun** [comment]
How can I take a survey? :)

**Comment by orangemug** [comment]
Thanks everybody sorry for the slow response, this is now fixed. So get to filling out your responses ✍️

Also be aware you can publicly share your project via our show and tell in issue #164  

So what went wrong. Typeform have changed their free plan, there is now a max of ten questions allowed (we had 11), I've collapsed the last question from

 - Do you have a website you would like to show off?
 - Do you have any further comments?

To 

 - Do you have any further comments, or a website you would like to show off?

With the idea being that it's pretty easy to spot and pull out urls from free text.

Their paid plan was $30/pm which is a little expensive for me. Also note that this is my mistake (not Typeforms) as they did send me an email letting me know, I just missed it in a busy period pre-xmas.
