### ISSUE TITLE
How to build vector tile from shapefiles

### ISSUE THREAD

**Issue by phainv88** [maputnik/editor#332]
Dear all,
I am very new in map. I have some problems, i need your help:
Now i have shapefile data, and i want to build vector tile, then styling the vector tile data using maputnik, then host vector tile and style json on server. And now i am not clear how to start, pls help  

**shortly what i want: shapefile->vector tile->styling->hosting**

Thanks all

**Comment by pathmapper** [comment]
Hi @phainv88,

here is a tutorial which shows you how to build vector tiles from shapefiles:

https://openmaptiles.org/docs/generate/custom-vector-from-shapefile-geojson/

Does this resolves also your other open issue (https://github.com/maputnik/editor/issues/327)?

**Comment by pathmapper** [comment]
On Windows you may use QGIS (www.qgis.org) to [convert your shapefile to GeoJSON ](https://gis.stackexchange.com/a/94960/105333)and here is a [step-by-step guide to install tippecanoe on Windows](https://github.com/GISupportICRC/ArcGIS2Mapbox#installing-tippecanoe-on-windows).

Or you could use https://github.com/mapbox/mapbox-studio-classic to convert your shapefile directly to vector tiles.

**Comment by klaukh** [comment]
I can also vouch for using a Linux VM on a Windows host to build openmaptiles.

**Comment by phainv88** [comment]
I hosted geojson on localhost:3000/land.geojson, then i set data source as below, but there show nothing
![2018-07-04 17_54_43-window](https://user-images.githubusercontent.com/40235807/42273605-d502c612-7fb3-11e8-9761-effd66693ecc.png)

**Comment by orangemug** [comment]
Your data source `localhost:3000/land.geojson` also needs CORS enabled, see <https://enable-cors.org/>

**Comment by keum** [comment]
Hello @phainv88, not sure if you have sorted out converting your shape file into vector tiles. We put together a workshop creating your own vector tiles from shape file. https://pkgeo-org.github.io/category/vector-tiles.html  here is the workshop. You can select the instruction depending on your platform (windows 10, windows 10 home edition, MacOS). sorry don't have for linux specifically but MacOS should be very similar.  Hope that explains the steps to get you started. 

pk

**Comment by orangemug** [comment]
There hasn't been any activity in this ticket for a while, so closing the issue. If you need further help, add a command and we'll reopen the issue.
