### ISSUE TITLE
How to publish data

### ISSUE THREAD

**Issue by phainv88** [maputnik/editor#336]
Dear all,
after doing some steps:
- host geojson data source at localhost:3000/areas.geojson
- connect geojson source from maputnik 
- styling data
now i have areas.geojson and style.json
So what can i do next to show tile map on web
I try using leaflet but i don't know how. Please help me

**Comment by orangemug** [comment]
So Maputnik creates mapbox-gl-js styles (see <https://www.mapbox.com/mapbox-gl-js/style-spec/>)

Follow this example <https://www.mapbox.com/mapbox-gl-js/example/simple-map/> replacing `style: 'mapbox://styles/mapbox/streets-v9'` with the url to your stylesheet.

**Comment by orangemug** [comment]
There hasn't been any activity in this ticket for a while, so closing the issue. If you need further help, add a command and we'll reopen the issue.
