### ISSUE TITLE
Map view is always blank

### ISSUE THREAD

**Issue by russss** [maputnik/editor#347]
I'm very confused why this only seems to be happening to me, but I'm unable to use Maputnik with any stylesheet, either from the website or by running the dev version from git locally. The map area is completely blank. This happens with both Chrome and Firefox (both beta channel), in incognito mode.

The issue seems to be that the MapboxGL container div has `style="filter: url("#undefined");"`. Removing this attribute with the web inspector makes it work.

**Comment by orangemug** [comment]
@russss what operating system are you using?

**Comment by russss** [comment]
OS X. It turns out it works in Safari, which is what the other person I'm working with was using.

**Comment by russss** [comment]
Yup, that works fine.

**Comment by orangemug** [comment]
If you have a moment, can you do me one more favour, does this fail on the first load for you? <https://664-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.36/0/0>

**Comment by russss** [comment]
No, that works on first load for me.

**Comment by orangemug** [comment]
Thanks for checking, there's a fix #348, which I'll merge shortly and probably release tomorrow.

Also hi, and welcome to Maputnik, thanks for raising the issue. Also please remember to fill out the survey in the app.

**Comment by muesliq** [comment]
Is there a workaround for older versions? Have the same problem, but just for one style. Must be something within that style that is causing this.

**Comment by orangemug** [comment]
Apologies, I totally forgot to actually release the fix. It's now released, see blog post <https://maputnik.github.io/blog/2018/07/27/release-v1.4.0>

Also note that we host previous versions of Maputnik at <https://github.com/maputnik/maputnik.github.io/tree/master/releases>, so for example to get to `v1.2.0` you can use https://maputnik.github.io/releases/v1.2.0/. My intent for this was that if we break something users can just use the previous version of Maputnik. 

I'll write this up in the help section, so users aren't left with a broken Maputnik and no options when we mess up.

Sorry all, I'll try to be more responsive in future.
