### ISSUE TITLE
How to run a filter with "LIKE" parameter?

### ISSUE THREAD

**Issue by dmitrykinakh** [maputnik/editor#350]
In QGIS I'm able to style my data by filtering them into several categories. On the screenshot, I'm showing that I want to filter in Maputnik all of the layers that start with "A %". How I can repeat the same in Maputnik?

![image](https://user-images.githubusercontent.com/8025637/43182975-2928f200-8fec-11e8-8bd3-1d4c19309136.png)

**Comment by dmitrykinakh** [comment]
@orangemug - could you please take a look on this?

**Comment by orangemug** [comment]
I'm not 100% sure about this, but I don't think mapbox-gl-js supports this. Take a read of the spec at <https://www.mapbox.com/mapbox-gl-js/style-spec>, I think your best bet would be to add a extra field to your data, something like `type`, and match on that instead.

**Comment by dmitrykinakh** [comment]
@orangemug, thanks!

**Comment by orangemug** [comment]
No worries, also welcome to Maputnik!

If you have time please fill out the survey in the app, and/or tell us what you're using Maputnik for over in issue #164
