### ISSUE TITLE
MULTIPOINT is not displaying on the map

### ISSUE THREAD

**Issue by dmitrykinakh** [maputnik/editor#351]
I've tried to display transit stops (circles) on my mao but before I wanted to style them.
I was surprised that type the of data for some reason are not displaying on the map (the same area shows data in QGIS)
QGIS: 
![image](https://user-images.githubusercontent.com/8025637/43257499-a393a1ce-90d8-11e8-8aae-e695e61301f3.png)

Maputnik: 
![image](https://user-images.githubusercontent.com/8025637/43257382-57d8dd26-90d8-11e8-8696-0e64ebeba4c4.png)

Same happens for other my data set which is also MULTIPOINT.

I'm attaching one row from the table from where I'm loading transit stop data to give you an idea what might be wrong.
[example.txt](https://github.com/maputnik/editor/files/2231576/example.txt)

**Comment by dmitrykinakh** [comment]
@orangemug - could you please take a look on this?

**Comment by orangemug** [comment]
@dmitrykinakh ah, sorry you have access now <https://github.com/orangemug/debug-styles>

**Comment by dmitrykinakh** [comment]
Hi @orangemug, thanks for your example, that works pretty well! But unfortunately, I still have the issue with my data. I've recorded a short video for you which might give you more data about the possible issue in my case - https://monosnap.com/file/aGQnjAhtFeps0Y8wRS9hrrosMrDWWb

I'm open to call (hangouts/skype whatever) since that issue is pretty much critical for my project.

**Comment by orangemug** [comment]
Hey @dmitrykinakh I haven't got time to look into it right now. However here are some suggestions

 - The version of Mapuntik in the video is an old one, update to v1.4.0
 - Export the style JSON from the editor and check that it is correct as per the [mapbox-gl-js style spec](https://www.mapbox.com/mapbox-gl-js/style-spec/). That should tell you if it's an issue with Maputnik or not
 - Also try the exported style in an example outside Maputnik, for example https://www.mapbox.com/mapbox-gl-js/example/simple-map/. Note that Maputnik is currently on `v0.45.0` so this will also allow you to check `v0.47.0` of mapbox-gl-js 
 - If it's not an issue with the editor (the style JSON is correct as per the spec) then it will either be an problem with
   1. Your data, mapbox-gl-js doesn't support something you're using.
   2. It's an bug in mapbox-gl-js, have a search though https://github.com/mapbox/mapbox-gl-js/issues see if anybody has reported an issue already.   

Report back your findings, if I get the time I take a look later in the week. Or someone else might be able to help.

**Comment by orangemug** [comment]
Hey @dmitrykinakh did you get anywhere with the above?

**Comment by orangemug** [comment]
@dmitrykinakh glad you worked it out, closing the issue.

If you have the time, please let us what you're using Maputnik for over in #164
