### ISSUE TITLE
Allow invalid styles and show errors

### ISSUE THREAD

**Issue by orangemug** [maputnik/editor#353]
Editing a Maputnik style can be a pain right now. In many places entering an invalid value will cause the input to get in a funny state or just refuse to let you complete the action. For example changing a color input with the value `rgba(255, 0, 0, 1)` to `rgb(255, 0, 0)` and you'll see the issue.

Also editing a style via the JSON editor is next to impossible at the moment for similar reasons. 

I think we should allow errors to be present in the style, and indicate what layers have errors.

Here's a prototype <https://696-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.26/0/0> (working branch https://github.com/maputnik/editor/compare/master...orangemug:feature/allow-invalid-values)

Below is an example where I've modified a layer `type` to be invalid, `backgroun` instead of `background`

<img width="593" alt="screen shot 2018-07-27 at 17 02 13" src="https://user-images.githubusercontent.com/235915/43332100-4373f27a-91bf-11e8-8d5d-bc12a3736731.png">

Below is an example where I am part way through modifying a color from `hsl` to `hsla` and am still missing the forth argument.

<img width="564" alt="screen shot 2018-07-27 at 17 02 39" src="https://user-images.githubusercontent.com/235915/43332113-4a46f746-91bf-11e8-8656-6b22dad3fff3.png">
 
Any thoughts or feedback welcome and encouraged 😄

**Comment by gregorywolanski** [comment]
This issue appears in the answers to question “What annoys you about Maputnik?” in the survey (original spelling):

- sometimes ctl+v doesnt work if theres is mismatch,it should give error by underline or something

- Black Screen with often no error messge once you make a mistake editing the local style file.

- Bugs to refresh style (I need to play with JSON to fix issues)

**Comment by pathmapper** [comment]
There is already something similar to indicate parse errors:

![auswahl_426](https://user-images.githubusercontent.com/20856381/46808841-874e8700-cd6d-11e8-9f34-274cd78dea11.png)

**Comment by sk1p** [comment]
> Any thoughts or feedback welcome and encouraged

I like it! Maybe in addition to the layer-wide error, also highlight the field that is currently invalid.

**Comment by pathmapper** [comment]
There two regressions in `master` since `v1.5.0` which are likely related: https://github.com/maputnik/editor/issues/484, https://github.com/maputnik/editor/issues/488

**Comment by orangemug** [comment]
Closed by PR #620
