### ISSUE TITLE
latest release as CLI / edit local files with latest release

### ISSUE THREAD

**Issue by Benni5K** [maputnik/editor#360]
Is v1.0.1 the last release where a cli was provided? I'm looking for a way to edit local style files with the latest release version. Currently I help myself by starting the maputnik_windows.exe with watch flag on my style file and subsequently starting the dev server with the latest release. For some (black magic ;) reasons, I can edit the local file with the dev server version as long as the cli runs. Anyhow that doesn't feel like a proper solution, so I'm wondering if there's another way to edit local files with the latest version.

**Comment by orangemug** [comment]
Hey @Benni5K we _archived_ [maputnik/desktop](https://github.com/maputnik/desktop) when we changed maintainers (to me), I wasn't really interested in maintaining it. Although if people still use it I can probably _unarchive_ and update it. I'll take a look sometime this week at it what needs doing.

**Comment by orangemug** [comment]
Ok I've taken a look, it looks easy I'll have a go at updating and rebuilding binaries for the next version `v1.5.0`

**Comment by Benni5K** [comment]
Thank you very much @orangemug! Looking forward to the next release!

**Comment by gregorywolanski** [comment]
This issue appears in the answers to question “What annoys you about Maputnik?” in the survey (original spelling):

- That there's no CLI *.exe of the latest releases.

**Comment by pathmapper** [comment]
Added some information to https://github.com/maputnik/editor/wiki/Maputnik-CLI.

**Comment by lukaswelte** [comment]
@orangemug do you need/want help here?
I built a new version locally as well and it seems to work pretty well (no code changes).
But one could simplify the make process by pulling the maputnik release instead of building it from source there.

In case you are interested I'm glad to bring maputnik/desktop up to date.

**Comment by orangemug** [comment]
@lukaswelte yes please, I added you to the repo.

Also welcome to Maputnik! Thanks for getting involved

**Comment by pathmapper** [comment]
Thanks to @lukaswelte (https://github.com/maputnik/desktop/pull/3), there are now again Maputnik desktop CLI binaries for Linux, OSX and Windows available for the [latest release](https://github.com/maputnik/editor/releases/tag/v1.5.0).
