### ISSUE TITLE
Proposal: Maputnik-Push MapboxGL Plugin

### ISSUE THREAD

**Issue by chriswhong** [maputnik/editor#362]
Greetings maintainers!  

## Background

As you know, we put together maputnik-dev-server to streamline the integration of maputnik into our mapping development workflow.  The current process requires the following workflow:

0) Set `window.map = map` once your map loads, so that the `map` object is global and can be picked up by the JS code in step 2.
1) run maputnik-dev-server, a local express server that includes a local build of maputnik.  
2) Copy and paste a snippet of javascript code in the console of your website, which POSTs the style to maputnik-dev-server and then redirects to http://{maputnikeditor}?style={locallyhostedstyle}

This is cumbersome, requires a local build of maputnik that gets stale, requires a non-optimal change to the code to expose the map object, and still has too many steps.

## Plugin + Production API

We have experimented with streamlining this process using a production API and a mapboxGL plugin.

1) [`maputnik-push-api`](https://github.com/chriswhong/maputnik-push-api) is currently running at `https://maputnik-push.planningabs.nyc` . It's doing essentially the same thing `maputnik-dev-server` was doing, but it's on a real domain, has https, and can serve a style that can be consumed by `https://maputnik.github.io/editor/#0.89/0/10.2`

2) We built a mapboxgl plugin, [`maputnik-push`](https://github.com/chriswhong/maputnik-push) that does what step 2 above did... because it's a plugin, it has access to the `map`object without any additional code.

You can try it right now!  

`yarn add https://github.com/chriswhong/maputnik-push#v0.0.2`

 ```
import MaputnikPush from 'maputnik-push';

// after the map loads:
 map.addControl(new MaputnikPush(), 'bottom-right');
```

The style as it currently exists will magically appear in maputnik!

## Proposal

In the interest of wider adoption and fewer barriers to entry getting started with maputnik, let's make both of these documented/production parts of Maputnik instead of just ecosystem add-ons that NYC Planning Labs maintains for our internal use.

1) Make `maputnik-push-api` a documented feature of maputnik.  People can manually push styles to it, or use it via the plugin, but let's make it part of the core product offering and maintain the code under `github.com/maputnik`, etc.

2) Make the `maputnik-push` mapboxGL plugin a documented option for using maputnik.  Let's maintain it under `github.com/maputnik`

Thoughts?

**Comment by orangemug** [comment]
Hi @chriswhong sorry for the delay, it's been a busy couple of weeks. I don't think I quite understand the usage, here's a couple of questions 

 1. If a map has a style loaded, that's almost always loaded from a url, why the need for the `maputnik-push-api` couldn't you just load the style from the url directly?
 2. What are the use cases for a person adding a `MaputnikPush` button to their maps?
    - Who would add the button
    - What's their motivation to do so

**Comment by chriswhong** [comment]
Hi, I'll try to answer below.

1.  The entire premise of this use case is that there is a whole lot of dynamic adding of layers and sources to the maps in our applications.  So, we start with a "base" style that came from a url, but have several (even dozens) of layers that are added to the map dynamically based on user interaction.  The combination of base + whatever the user added is what I want to be able to view *now* in maputnik, and it can vary from minute to minute when we are doing development.

2.  The use case here is that it's difficult to load a programmatically assembled style into maputnik, the style on the map is the result of many subsequent addLayer() and addSource() calls that happen in our frontend code. The motivation is that at any point in the development process, if there's a mapboxGL map somewhere in the browser, it's *one click* away from being in Maputnik.

**Comment by klokan** [comment]
Hi @chriswhong !

If I understand you well - you want to add buttons to a website which interactively call "addLayer+addSource" actions in a single already openned instance of Maputnik - right?

I think you don't need a server and push events to do that, as the web browser can interact with a single running instance of Maputnik which is already opened...

Define a new "#" link where you pass the data to be used with some agreed prefix - for example URL-encoded layer snippet.

Use links to maputnik with `<a href`and *with `target="maputnik"`* and with your introduced `#` function to add a layer - then the existing alread openned instance of maputnik is not reloaded in the browser window - but instead you can interact with the instance - so JavaScript can call actions on the hash change event...

See similar demo I have made: https://klokan.github.io/iiiflink/

- If you want to sniff complete JSON styles of maps while browsing - a browser plugin would do it - and you could use the existing `?style=` with URL.

**Comment by orangemug** [comment]
> 2. The use case here is that it's difficult to load a programmatically assembled style into maputnik, the style on the map is the result of many subsequent addLayer() and addSource() calls that happen in our frontend code. The motivation is that at any point in the development process, if there's a mapboxGL map somewhere in the browser, it's one click away from being in Maputnik.

@chriswhong once you've modified the style in Maptunik, what do you then use that style for? Is this used as a way to produce 'one off' maps from your data?

**Comment by chriswhong** [comment]
Usually, we are writing mapboxGL layer configs and committing them to our code.  The workflow proposed allows us to write some style for a layer, have our codebase render the "base map", add X custom layers, and display it on the page.  We then open this "built map" in Maputnik, edit a layer or two, then copy and paste the style's JSON into our code, then repeat.

**Comment by chriswhong** [comment]
These are the kinds of apps we are building: https://zola.planning.nyc.gov/about?C1=false&C2=false&C3=false&C4=false&C5=false&C6=false&C7=false&C8=false&community-districts=true#9.72/40.7125/-73.733

**Comment by orangemug** [comment]
Thanks for explaining @chriswhong, so here's how I think we should proceed.

Lets keep it as an external dependency for now, but link to it in the README. That way we can see if this workflow is more generally useful to users of Maputnik outside of NYC planning labs. That's assuming that you're ok running the server for anybody to use.

Lets collect feedback to see if others are using it, if they are lets maintain it as a part of the Maputnik project.

Sound reasonable, any thoughts?

**Comment by chriswhong** [comment]
Sounds good to me, I'll PR a chunk for the Readme that explains how to use it.
