### ISSUE TITLE
Create a redux API

### ISSUE THREAD

**Issue by loicgasser** [maputnik/editor#369]
Hi, I have been studying Redux for a couple of days and I was telling myself this is exactly what we would need to reduce the complexity in the application. Little did I know mapbox blogged about it [a year ago](https://tighten.co/blog/react-101-using-redux)

Benefits from such an approach
- a unique source of truth
- a clear seperation between actions, reducers and selectors making the code base a whole lot easier to maintain on the long run
- more than easy unit tests
- no need to pass handler over to the children components, no more maze!

This could be created as a third party library, one could integrate on top of mapboxgl or openlayers. So it could be totally agnostic of mapping library and even react in a larger sense.
In orther words, we would only be maintaing the state of the map style.

To sync the map state this what [mapbox  uses.](https://github.com/mapbox/mapbox-gl-redux)
[small app using mapbox redux integratrion](https://github.com/loicgasser/react-mapbox-app)
Now they don't deliver the styling part of mapbox studio.

What do you think @orangemug @oterral ?

[Redux](https://redux.js.org)

**Comment by orangemug** [comment]
Hey @loicgasser this has been raised before, in issue #272. Have a read and let us know your thoughts.

**Comment by orangemug** [comment]
Closing this issue as duplicate

**Comment by loicgasser** [comment]
:+1:
