### ISSUE TITLE
Nested filters

### ISSUE THREAD

**Issue by gregorywolanski** [maputnik/editor#373]
One person mentioned no support for nested filters in their answer to the question “What annoys you about Maputnik?” in the survey.

**Comment by orangemug** [comment]
Can someone explain what 'Nested filters' are, or link to some docs?

**Comment by pathmapper** [comment]
Hmm, there is a [comment in the GL JS code](https://github.com/mapbox/mapbox-gl-js/blob/466162f571881c2d97ad4c666c4a183abac71d47/src/style-spec/feature_filter/index.js#L63-L65) regarding nested arrays. 

Maybe the person meant support for filter [expressions](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions), which is tracked in https://github.com/maputnik/editor/issues/223.

**Comment by pathmapper** [comment]
Example of a nested filter ([commit where they were removed from OSM Liberty](https://github.com/maputnik/osm-liberty/commit/38a95e0d8f852c76279ed8d923e2875757502f5e#diff-ed432438db2de4dd0ecd05b0f3371dc3)):

```
 "filter": [
        "all",
        [
          "==",
          "$type",
          "LineString"
        ],
        [
          "all",
          [
            "==",
            "brunnel",
            "tunnel"
          ],
          [
            "in",
            "class",
            "path",
            "pedestrian"
          ]
        ]
      ]
```

**Comment by orangemug** [comment]
Closing this issue, nested filters would be a difficult UI to get right and as @pathmapper says we're developing support for expressions anyway.
