### ISSUE TITLE
Hidden layers hard to spot on the layers list

### ISSUE THREAD

**Issue by gregorywolanski** [maputnik/editor#375]
**Current behavior**

When you hide a layer and then click another layer to edit it, you can’t see on the layer list which layers are hidden without hovering over every layer.

![1](https://user-images.githubusercontent.com/787518/44947204-ebdf0380-ae09-11e8-8f8f-2c7467d4cd9f.gif)

**Expected behavior**

When you hide a layer and then click another layer to edit it, you can see on the layer list which layers are hidden.

![2](https://user-images.githubusercontent.com/787518/44947207-f0a3b780-ae09-11e8-9ba1-fe8f0dadc974.gif)

Also, I think that we should turn the icons over and show the eye with a line next to hidden layers.

**Comment by orangemug** [comment]
> Also, I think that we should turn the icons over and show the eye with a line next to hidden layers.

Makes sense to me, that's what [GIMP  - GNU Image Manipulation Program](https://www.gimp.org/) does.

I assume photoshop does this also, can someone please confirm?

**Comment by pathmapper** [comment]
> Also, I think that we should turn the icons over and show the eye with a line next to hidden layers.

> Makes sense to me, that's what GIMP - GNU Image Manipulation Program does.

Makes sense to me, too. Now, that I'm thinking about it, I know why I always expect the opposite behavior for show/hide layer :smile: 

With Photoshop the eye without line means also visible:
https://www.youtube.com/watch?v=Jl2VFvdWMFs

**Comment by gregorywolanski** [comment]
@orangemug 

>I've got a branch that always shows the visibility toggle. Is that what you had in mind?

We’re getting there! : D

It’s overwhelming to see all those eyes. I suggest we always show the icons of hidden layers only. 

I should have swapped the icons before making the “Expected behavior” GIF. It would be more clear. Excuse me. :)

**Comment by orangemug** [comment]
Updated demo <https://964-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.36/0/0>
