### ISSUE TITLE
copying a json config from one page to another does not result in the same behaviour

### ISSUE THREAD

**Issue by DominikReinert** [maputnik/editor#381]
I created my own tile config and althought everything went just fine, I wanted to add the white box with the black borders, that you can see in the example config, to my map config.

![image](https://user-images.githubusercontent.com/20775497/45478886-44d16480-b745-11e8-8b94-5b792c63748f.png)
On the left, its my map, on the right its the example map.

I copied over all attributes from right to left, but still, I do not have this box around the street name, and I have no clue why.

Is the box connected to something else? Shouldnt the exact same config result in the exact same result?

Thanks for you help

**Comment by pathmapper** [comment]
Hi @DominikReinert,

> Is the box connected to something else? 

The box on the right map is coming from the [sprite](https://www.mapbox.com/mapbox-gl-js/style-spec#sprite), referenced with ["icon-image"](https://www.mapbox.com/mapbox-gl-js/style-spec#layout-symbol-icon-image)`.

Here is such a sprite used for the [OSM Liberty style](https://github.com/maputnik/osm-liberty):
https://github.com/maputnik/osm-liberty/blob/gh-pages/sprites/osm-liberty.png
https://github.com/maputnik/osm-liberty/blob/gh-pages/sprites/osm-liberty.json

Are you using the same sprite for both maps?

You find the [base URL for retrieving the sprite](https://www.mapbox.com/mapbox-gl-js/style-spec#root-sprite) in the root properties of a style, e.g.
https://github.com/maputnik/osm-liberty/blob/gh-pages/style.json#L22

**Comment by DominikReinert** [comment]
Well, I found out that I use another sprite, but if i export the one on the right side (working), i get a not working export value:
![image](https://user-images.githubusercontent.com/20775497/45685845-fd831380-bb4a-11e8-8da2-ce466447dcdd.png)


and this is the one on the left, thats at least working...:
![image](https://user-images.githubusercontent.com/20775497/45685821-ed6b3400-bb4a-11e8-8662-d055040faeb6.png)

**Comment by pathmapper** [comment]
>  if i export the one on the right side (working), i get a not working export value


Which style are you exporting? OSM Bright?

If you check the _Style Settings_ before exporting the style, are there URLs for sprites and glyphs available?

![auswahl_417](https://user-images.githubusercontent.com/20856381/45697830-eeaa5a00-bb66-11e8-8d46-a8129e1b7ae7.png)

**Comment by DominikReinert** [comment]
Yes, they are set to the values taken from the JSON

**Comment by pathmapper** [comment]
How do you export the style?

**Comment by pathmapper** [comment]
I can't reproduce and for me it's not clear what you are doing exactly.

Are you able to provide a style where the export for the sprite and glyphs values fails?
Or could you please describe exactly how to reproduce the behaviour you are seeing?

**Comment by DominikReinert** [comment]
The following is the result of exporting my **working** configuration:

[my-domain.json.txt](https://github.com/maputnik/editor/files/2397041/my-domain.json.txt)

I am already used to making changes using maputnik (for visual feedback) and re-applying them manually in the file.
In the above json you can see, that the glyphs get `key=undefined` instead of `key={key}`, just to tell you the most obvious export error.

This is the working config:

[my-domain-working.json.txt](https://github.com/maputnik/editor/files/2397055/my-domain-working.json.txt)

Zooming far enough into it, you can see that neither the road signs, nor stuff like railway stations (the example I refer to is this [from older, still working version]):

![2018-09-18](https://user-images.githubusercontent.com/20775497/45753661-d6474780-bc19-11e8-8ca1-aad9411612ba.png)

instead of this (current):

![2018-09-18 1](https://user-images.githubusercontent.com/20775497/45753740-01ca3200-bc1a-11e8-95ac-8fbd984f4f51.png)

**Comment by pathmapper** [comment]
@DominikReinert thanks for the styles and further information.

There are two different issues here:

1. When exporting a glyph URL with `key={key}` the exported style has `key=undefined` instead.
You're right, this is a bug, it should remain `key={key}`. /cc @orangemug 
Until this is fixed, a workaround would be to enter your [Maptiler Cloud](https://www.maptiler.com/cloud/) access key before exporting the style. This way you would be able to open your style again with Maputnik.
![auswahl_419](https://user-images.githubusercontent.com/20856381/45842932-6a023c00-bd1e-11e8-91c8-3e3a78a8c7d9.png)


2. Missing railway stations for `my-domain-working.json` :
This is no issue related to Maputnik. 
The layer `poi-railway` has `"visibility": "none"`. If you change this to `"visibility": "visible"` the railway stations show up again (see [my-domain-working.json.txt](https://github.com/maputnik/editor/files/2402814/my-domain-working.json.txt)):
![auswahl_418](https://user-images.githubusercontent.com/20856381/45842631-8fdb1100-bd1d-11e8-9382-a9a895f034d5.png)


I didn't notice any missing road signs. If this is still the case, could you please provide an example?

**Comment by DominikReinert** [comment]
@pathmapper Thank you for your great help!

1) The road signs magically appeared for me again. Maybe it was a bug on the glyphs side? However, in the original post you see how the missing road sign backgrounds looked like (left). 

2) Okay, I will keep this in mind. 

3) I think I tried turning the railways on, but it didnt work. However, it works now. 

And thank you once more

**Comment by DominikReinert** [comment]
@pathmapper is it possible that you remove the first picture of my third last comment on this, please? I accidentaly put a pic in here with my employers name visible...

**Comment by pathmapper** [comment]
@DominikReinert good to hear that your issues are solved.

I've noticed that you removed the screenshot yourself from the comment.

If you want to delete this screenshot also from the comment history, you are able to do this also yourself:
https://help.github.com/articles/tracking-changes-in-a-comment/#deleting-sensitive-information-from-a-comments-history
