### ISSUE TITLE
"Loading style" modal - not possible to close

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#393]
It is not possible to close the _Loading style_ modal if no URL was inserted before click on _Open URL_:

![loading_style_modal](https://user-images.githubusercontent.com/20856381/45930768-50523600-bf64-11e8-9dc9-6f54ae8fe57f.gif)

**Comment by orangemug** [comment]
@pathmapper can you confirm the merged PR fixes the issue

**Comment by pathmapper** [comment]
@orangemug the behaviour is now the following: 

If no or an invalid URL was inserted before click on _Open URL_, the _Loading style_ modal shows up and immediately closes on its own. So the issue reagrding the stucked modal is fixed, but I wonder if there should be a notification to the user that no style was loaded.

The _Open URL_ button looks now differently compared to the _Upload_ button (white border):

![auswahl_140](https://user-images.githubusercontent.com/20856381/45933464-a7b8cc00-bf8d-11e8-883a-deb1adc7be10.png)

**Comment by orangemug** [comment]
@pathmapper I agree, lets open a new ticket though.
