### ISSUE TITLE
Add /edit layer - Error is missing if multiple layer IDs are an empty string

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#401]
Currently it is possible to add a Layer without ID which is [required and must be unique](https://www.mapbox.com/mapbox-gl-js/style-spec#layer-id).

**Comment by orangemug** [comment]
It turns out that the version of [@mapbox/mapbox-gl-style-spec](https://www.npmjs.com/package/@mapbox/mapbox-gl-style-spec) we're using, doesn't throw an error.

Todo

 1. Check latest version
 2. If still an issue, raise ticket/PR in the [@mapbox/mapbox-gl-style-spec repo](https://github.com/mapbox/mapbox-gl-js)

**Comment by orangemug** [comment]
Ok so the new version of the spec doesn't throw a validation error either. We probably shouldn't go adding in additional checks to the style spec. Maybe we should just disable the 'Add Layer' button if the id attribute is empty.

**Comment by pathmapper** [comment]
I did some testing with [`gl-style-validate`](https://www.npmjs.com/package/@mapbox/mapbox-gl-style-spec#gl-style-validate) and I was wrong with "currently it is possible to add a Layer without ID".

When adding a layer with an empty ID attribute the ID is an empty string: ` "id": ""` and not missing.

The spec only throws an error if the whole `"id"` property is missing (error: `missing required property "id"`).

However, there is still an issue here, because it is possible to add multiples layers with ` "id": ""`. It is also possible to edit/delete layer IDs so that there are multiple layers with ` "id": ""`.

In this case the spec throws an error with `gl-style-validate` (error: `duplicate layer id ""`) but with Maputnik this error is somehow missing.

**Comment by pathmapper** [comment]
This was fixed by @orangemug in https://github.com/maputnik/editor/pull/625.
