### ISSUE TITLE
Inspect Mode - Switching data sources has no effect

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#403]
Empty style: The displayed source remains visible even if it is not an active source anymore.

![source_inspect-mode](https://user-images.githubusercontent.com/20856381/46281110-08d43700-c56e-11e8-87bd-b9f5a6d1f8b2.gif)

**Comment by orangemug** [comment]
This may be related to https://github.com/lukasmartinelli/mapbox-gl-inspect/pull/9, it looks like we only re-render if `Object.keys(sources).length > 0`, see <https://github.com/lukasmartinelli/mapbox-gl-inspect/blob/master/lib/MapboxInspect.js#L161>

**Comment by pathmapper** [comment]
Hmm, this explains why there is no re-render when all current sources are removed, however in the above GIF another source is added (`thunderforest_transport` -> `no source` -> `openmaptiles`) so that `Object.keys(sources).length > 0` should be true in the end.
