### ISSUE TITLE
Adding a layer for a road under construction

### ISSUE THREAD

**Issue by zvukoper** [maputnik/editor#410]
I'm a noob in maputnik. After some time I could style anything I need pretty easily.
But I've found a constructed road - https://www.openstreetmap.org/#map=18/57.15488/65.59681
And I couldn't understand how can I add the construction layer to my style http://editor.openmaptiles.org/?style=https://rawgit.com/openmaptiles/positron-gl-style/master/style.json#16.14/57.154374/65.597906

I probably don't really understand the layer\tag\source\type concept. Sorry.

Can anyone give me a hint on how to add a constructed road layer to my style?

**Comment by pathmapper** [comment]
Hi @zvukoper currently roads under construction are not included in the source you are using  (OpenMapTiles) for the Positron style. 

See https://github.com/openmaptiles/openmaptiles/issues/501, https://github.com/openmaptiles/openmaptiles/issues/321, https://github.com/openmaptiles/openmaptiles/issues/82.

There are several ways how you could achieve what you want. One solution would be to extract the geometry for the road under construction from OSM and add it as GeoJSON line to the map.

You could add the GeoJSON as source in Maputnik and style it or add it with GL JS like in the following example:

https://www.mapbox.com/mapbox-gl-js/example/geojson-line/

**Comment by pathmapper** [comment]
Thanks for your feedback @zvukoper, closing here.
