### ISSUE TITLE
Editing the source field of a layer throws an error causing the cursor to reset in the JSON editor and GUI

### ISSUE THREAD

**Issue by gregorywolanski** [maputnik/editor#421]
As soon as I click “Backspace” on my keyboard, I get:

![1](https://user-images.githubusercontent.com/787518/47253473-85fb1980-d453-11e8-8519-780c0cd260ca.png)

This issue appears in the answers to question “What annoys you about Maputnik?” in the survey (original spelling):

- editing the source field of a layer throws an error causing the cursor to reset in the json editor and gui

- Problems when changing the source of a layer: it has to be done on the json code, the menu crashes the app

**Comment by pathmapper** [comment]
Related: https://github.com/maputnik/editor/issues/353

**Comment by pathmapper** [comment]
This is not an issue anymore with `v1.7.0-beta2` :tada:
