### ISSUE TITLE
Bad JSON after deleting secondary font in the “Text layout properties” section

### ISSUE THREAD

**Issue by gregorywolanski** [maputnik/editor#422]
Current JSON after deleting secondary font:

```
"text-font": [
    "Metropolis Regular",
    ""
],
```

Expected JSON:

```
"text-font": [
    "Metropolis Regular"
],
```

**Comment by pathmapper** [comment]
Related: https://github.com/maputnik/editor/issues/129

**Comment by pathmapper** [comment]
Closing here to concentrate the discussion in https://github.com/maputnik/editor/issues/129.
