### ISSUE TITLE
Symbols: “Image” property low in the “Icon layout properties” section

### ISSUE THREAD

**Issue by gregorywolanski** [maputnik/editor#423]
The “Text layout properties” section begins with the “Field“ (content) property. It makes sense.

The “Icon layout properties” section begins with the “Allow overlap” property. Weird and unfriendly.

Could we move the “Image“ property to the top of the “Icon layout properties” section?

**Comment by orangemug** [comment]
I believe this line needs moving https://github.com/maputnik/editor/blob/master/src/config/layout.json#L147
