### ISSUE TITLE
Layout properties: Icons instead of text in “Cap” and “Join” properties

### ISSUE THREAD

**Issue by gregorywolanski** [maputnik/editor#425]
![1](https://user-images.githubusercontent.com/787518/47254117-c364a480-d45d-11e8-81ba-c5bbe27300f1.png)

Opinions? :)

**Comment by orangemug** [comment]
I'm not so sure I think this is a good idea. I think the text is probably more obvious than the icons would be. Questions

 - Does anybody else have any opinions?
 - What do other graphics/map editors do?

**Comment by pathmapper** [comment]
Agree, let's close this.

It would be also difficult to have small icons which are showing the difference between `Butt` and `Square`.

The style spec has a text description of the different options: 
https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-line-line-cap
https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-line-line-join

Maybe we could make this description with tooltips available. Let's move this discussion to https://github.com/maputnik/editor/issues/567
