### ISSUE TITLE
Layers list: Missing drag & drop handler

### ISSUE THREAD

**Issue by gregorywolanski** [maputnik/editor#426]

**Comment by pathmapper** [comment]
This one? It's not very obvious, some users had a hard time to find it, see https://github.com/maputnik/editor/issues/182:

![drag_and_drop_layers](https://user-images.githubusercontent.com/20856381/47254236-afba3d80-d45f-11e8-85fa-c53cd24cf631.gif)

**Comment by gregorywolanski** [comment]
Hihihi. I meant that there is a need to add a more obvious handler. :)

**Comment by orangemug** [comment]
So I've tried hanging the drag handle off the left hand side, to allow maximum space for the labels.  

<img width="262" alt="screen shot 2018-10-30 at 19 41 01" src="https://user-images.githubusercontent.com/235915/47745530-cd677e00-dc7b-11e8-80e8-1189ce074bfe.png">

 - Branch: <https://github.com/maputnik/editor/compare/master...orangemug:feature/layer-list-ui-handle>
 - Demo: <https://1148-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>

I've seen another UI do this (I can't remember which). Questions

 - Does it look like a drag handle?
 - Does it look ok? Or rather does it look broken with the padding removed from the left hand side?

**Comment by pathmapper** [comment]
> Does it look like a drag handle?

No

> Does it look ok? Or rather does it look broken with the padding removed from the left hand side?

It doesn't look broken, but I find the icons for the layer types harder to spot with the additional icons on the left hand side.

Positive: 
The layers are easier to drag because of the the increased area where the drag handler is available.

Thoughts: 
- Remove the new drag handle icon, keep the increased drag area and center the type icon there.
- What about making the whole layer name draggable (without changing the cursor for simple hover)? 
  I would assume a lot of users are trying to drag and drop the layers with a hold click on the layer name.

**Comment by orangemug** [comment]
> What about making the whole layer name draggable (without changing the cursor for simple hover)?
I would assume a lot of users are trying to drag and drop the layers with a hold click on the layer name.

That sounds sensible to me.

I guess we should probably also take a look at what the other image editing/geo apps do also.

**Comment by pathmapper** [comment]
With QGIS and GIMP the layer name is draggable. 

Both are also using a horizontal line to indicate the position where the layer will be dropped. Such a line is already shown in Maputnik, just noticed it for the first time :smiley: . Maybe we could change the line color to make it more distinguishable from the background. 

**QGIS:**
![qgis](https://user-images.githubusercontent.com/20856381/47775992-98960e00-dcf1-11e8-92ab-f7d7d11f293d.gif)

**GIMP:**
![gimp](https://user-images.githubusercontent.com/20856381/47776004-9df35880-dcf1-11e8-8d9c-937d7786d037.gif)

**Comment by pathmapper** [comment]
Great @orangemug , that's how I would expect it to work.

Very cool and intuitive! :tada:
