### ISSUE TITLE
Export: Filenames

### ISSUE THREAD

**Issue by gregorywolanski** [maputnik/editor#429]
Idea from one of the users:

Today filenames of exported styles are like `61yy7478h.json`.

It would be awesome to get names consisting of simple style name and an incrementing version – for example `my_map_style_v1.json` for “My Map Style”.

**Comment by orangemug** [comment]
I believe we need to change https://github.com/maputnik/editor/blob/master/src/components/modals/ExportModal.jsx#L42 to use the `name` of the style if it exists or the `id` if it doesn't. The `name` should also be turned into a slug via something like <https://www.npmjs.com/package/slugify>

**Comment by pathmapper** [comment]
Done in https://github.com/maputnik/editor/pull/442.
> and an incrementing version

Such a version number could be added to the style name in the _Style Settings_, e.g. “My Map Style v1” results in `my_map_style_v1.json`.

![auswahl_430](https://user-images.githubusercontent.com/20856381/47423617-c9bc8e80-d785-11e8-8c70-77edda3ef35b.png)
