### ISSUE TITLE
Zoom slider

### ISSUE THREAD

**Issue by gregorywolanski** [maputnik/editor#432]
![1](https://user-images.githubusercontent.com/787518/47254587-d3cc4d80-d464-11e8-82c9-48379cff7591.png)

A user suggested to replace “Min Zoom” and “Max Zoom” with two or one slider.

**Comment by orangemug** [comment]
It needs a few styling fixes, but what do people think in general
 
 - Branch: <https://github.com/orangemug/editor/tree/feature/add-range-slider>
 - Demo: <https://1167-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.35/0/0>

<img width="365" alt="screen shot 2018-10-30 at 20 29 23" src="https://user-images.githubusercontent.com/235915/47749203-82059d80-dc84-11e8-819d-e6befb3b881a.png">

**Comment by pathmapper** [comment]
In general it looks good!

The slider handles look different, but OK, with Chrome on Linux:

![auswahl_439](https://user-images.githubusercontent.com/20856381/47793499-ad3ccb00-dd1e-11e8-9d0f-aab522cc2348.png)

Some thoughts:
- It's nearly impossible to hit integer values with the sliders. Could there be some kind of snapping implemented?
- It's not possible to enter decimal places in the box beneath the sliders when you start there with an integer value.
- Maybe one decimal place for the value if it is set with the slider is sufficiant.

**Comment by pathmapper** [comment]
The sliders are non functional with Firefox on Linux.

It is only possible to adjust the value with a click on the slider bar. The slider handle itself is not slideable.

**Comment by orangemug** [comment]
I've changed the range (slider) step to `0.1` in the demo <https://1184-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.35/0/0>

I think the firefox issue is actually to do with #372. I think we're blocking the UI thread for too long which is causing the slider to 'stall'. I'll leave this ticket until I've completed the performance ticket and revisit then.

**Comment by pathmapper** [comment]
I still find it very difficult to hit integer values. 

What about only using integer values as steps for the slider? 

I think most of the time a user wants to use integer values and if not, non-integer values could be added via the box next to the slider or via the JSON editor.

**Comment by orangemug** [comment]
There are a few bugs still with default values, but here's an updated demo <https://1213-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>

**Comment by pathmapper** [comment]
Great, now it's usable :+1:

**Comment by pathmapper** [comment]
@orangemug is there still something to do before you want submit a PR?
