### ISSUE TITLE
Top Issues

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#435]
As the number of issues increases on the issue tracker, I just wanted to mention https://github.com/mapbox/top-issues, which makes it possible to get kind of an issue ranking (as measured by # of interactions, priority labels and age) to prioritize tasks and getting an overview:

https://mapbox.github.io/top-issues/#!maputnik/editor

We could also use custom scoring settings (e.g. based on labels): 
https://github.com/mapbox/top-issues#topissuesrc

It has it's limitations regarding Github reactions like 

> Only reactions on the initial issue comment "count." 

but

> Because anyone may add reactions, these scores represent the will of the community.

If there's an interest in using this tool, I could draft a `.topissuesrc` for the Maputnik repo.

**Comment by orangemug** [comment]
Sounds good @pathmapper lets give it a try, see how it goes. Anything to help prioritise sounds great to me. For context, I personally I try to mix my time between stuff I find interesting and stuff I think is important.

I've also realised you're not a part of the Maputnik organisation. I'll get my head around who has access to what and send you an invite (soonish). Also a big thank you from me for your contributions to the project.

**Comment by orangemug** [comment]
We could also potentially try using GitHub projects again to plan a collection of work a bit better. Any thoughts you have on better management of issues, please let me know. I know I haven't been particularly good at this over my involvement in the project

**Comment by pathmapper** [comment]
Thanks for the feedback, a draft for a custom scoring is in https://github.com/maputnik/editor/pull/438.

Additions and modifications welcome, I just see it as an attempt to get a better overview and not as something authoritative.

While going through the existing issue labels, I noticed there are a lot of them currently and maybe some of them are not needed anymore.

Using GitHub projects again is a good suggestion, maybe for projects like _GitHub integration_ (https://github.com/maputnik/editor/issues/155, https://github.com/maputnik/editor/issues/239, https://github.com/maputnik/editor/issues/269), _Documentation_ (https://github.com/maputnik/editor/issues/337, https://github.com/maputnik/editor/issues/325) and/or _UI redesign_ (https://github.com/maputnik/editor/issues/252, https://github.com/maputnik/editor/issues/82 ,https://github.com/maputnik/editor/issues/202, #109)?

**Comment by pathmapper** [comment]
Thanks @orangemug !
