### ISSUE TITLE
Color Picker Format and Alpha Values

### ISSUE THREAD

**Issue by lukasmartinelli** [maputnik/editor#44]
The Alpha value slider does not work.

![screenshot from 2017-01-04 09-06-40](https://cloud.githubusercontent.com/assets/1288339/21635301/22bef3f4-d25d-11e6-9e53-11f6366b0c91.png)

**Comment by muesliq** [comment]
Also: Color picker doesn't stay within a color format:

1. I click on a color field with **hsl** value.
2. The color picker opens showing the corresponding **HEX** value.
3. I click on a different color
4. The value in the color field is updated with the **rgba** value.

This is confusing. IMO formats should stay consistent (hsl in this case).

**Comment by lukasmartinelli** [comment]
> This is confusing. IMO formats should stay consistent (hsl in this case).

:+1: I agree.

Right now I always request rgba from the color picker.
The main problem is that I don't get the chosen color state from the color picker. So I don't know that you have chosen a HSLA color in the picker - I only get the rgba value.
