### ISSUE TITLE
Building and developing Maputnik works with ...

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#445]
Currently the readme states:

> We ensure building and developing Maputnik works with
> 
> Linux, OSX and Windows
> Node >4

@orangemug is this still valid or should it be updated because we are currently running Linux/OSX tests for Node 6/8/10 and Windows tests for 8/9/10?

**Comment by orangemug** [comment]
Yeah it should be updated, maybe it should say something like

> We ensure building and developing Maputnik works with the [current active LTS and above](https://github.com/nodejs/Release#release-schedule)

We should also add node v11 to the test runners
