### ISSUE TITLE
Show/list available images of a sprite

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#454]
From https://github.com/maputnik/editor/issues/434#issuecomment-434675997:

> there is currently no information available in the editor regarding which images are available in a sprite used by the style and the user therefore needs to know how to get this information elsewhere.
> 
> To show/list the available images of a sprite somewhere in the editor would be a nice feature.

**Comment by orangemug** [comment]
The 'image' field already has an autocomplete dropdown.

<img width="351" alt="screen shot 2018-10-31 at 13 42 40" src="https://user-images.githubusercontent.com/235915/47791980-deaf9980-dd12-11e8-91fe-ed7a0daedcb7.png">

@pathmapper how is this ticket different?

**Comment by pathmapper** [comment]
You're right, didn't notice it.
