### ISSUE TITLE
Bot for posting test build link to PR 

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#456]
From https://github.com/maputnik/editor/pull/449#issuecomment-434446967:

> It'd be great if there was a little bot that posted the link as a comment to the PR.

@orangemug how about this one?

https://www.npmjs.com/package/circle-github-bot

**Comment by pathmapper** [comment]
Here is a project which uses this package for posting to the PRs:

https://github.com/palantir/blueprint

https://github.com/palantir/blueprint/blob/develop/scripts/preview.js

They've created a bot account which is used for posting: https://github.com/blueprint-bot

Useful information:
- https://github.com/themadcreator/circle-github-bot/issues/11

- https://github.com/palantir/blueprint/blob/develop/CONTRIBUTING.md#enable-preview-comments

I've played around with it, the following script works for us:

```
#!/usr/bin/env node

if (!process.env.GH_AUTH_TOKEN) {
    console.error("Missing GH_AUTH_TOKEN env var, refusing to run.");
    process.exit();
}

const bot = require("circle-github-bot").create();

bot.comment(`
<h4>${bot.env.commitMessage}</h4>
Preview: <strong>${bot.artifactLink('../../artifacts/build/index.html', 'Maputnik test build')}</strong>
`);
```

**Comment by pathmapper** [comment]
@orangemug what about the codesandbox bot (https://github.com/orangemug/editor-ci-test/pull/2#issuecomment-632073896) would this work for forks instead of Github Actions?

https://github.com/apps/codesandbox

**Comment by orangemug** [comment]
Did I already solve it... 🤦‍♂️

Yes lets re-eneable codesandbox, thanks @pathmapper
