### ISSUE TITLE
Support for Bengali Unicode Fonts

### ISSUE THREAD

**Issue by azizul-bkash** [maputnik/editor#457]
I am trying to create a design with Maputnik with a custom vector layer. When I am trying to label in Bengali language the font broken. If you see the output in the image there are few problem. I am writing here how it should look like

মুন্সিগঞ্জ
গোপালগঞ্জ
ঝিনাইদহ
যশোহর

Few years ago the same problem occurred in Tilemill. A library called Herfbuzz were used to solve that problem. But How can I render this with client-side visualization?

Here is the Tilemill solution link

https://github.com/mapnik/mapnik/issues/1714

Few other links

https://github.com/mapbox/mapbox-gl-js/issues/5926
https://github.com/mapbox/mapbox-gl-js/issues/4009

![bengali_problem](https://user-images.githubusercontent.com/41333705/47852136-0121df80-de05-11e8-98df-b2019dfa159a.png)

**Comment by pathmapper** [comment]
Hi @azizul-bkash,

Maputnik is a visual editor for the [Mapbox GL styles](https://www.mapbox.com/mapbox-gl-style-spec/) and uses [Mapbox GL JS](https://github.com/mapbox/mapbox-gl-js) as renderer for the map.

I think you linked the relevant issues there.

From https://github.com/mapbox/mapbox-gl-js/issues/5926#issuecomment-354667820

> It's not currently supported, unfortunately. Tracking this in #4009.

Closing here, as there's nothing we can do on Maputnik side to fix this problem
