### ISSUE TITLE
Categorical property value

### ISSUE THREAD

**Issue by tomass** [maputnik/editor#466]
Allow switching to categorical  property setting via UI:
![paveikslas](https://user-images.githubusercontent.com/969513/48310418-8b054180-e597-11e8-876c-71eb5421c3dd.png)
It is currently only possible to change json manually and then continue in UI.
This (together with expressions) is very useful when creatng smaller and faster styles. For example it is possible to have less road layers with this feature. Especially when we need tunnels and bridges.

(As I take it, it is not "expressions" which have a different tracking issue https://github.com/maputnik/editor/issues/223)

**Comment by pathmapper** [comment]
Hi @tomass,

thanks for your suggestion!

You're right, this is not expressions but I think the same (and more) could be achieved with expressions.

Here is a good article which covers also the differences between stop functions and expressions: 
https://blog.mapbox.com/announcing-expressions-in-gl-js-a72b55d0a6af

Like in https://github.com/maputnik/editor/issues/373 it comes down to the question which way we want to go in the future:

- Use only impressions (and, if so, implement suggestions like in this issue until we have expressions?)
- Use [functions](https://www.mapbox.com/mapbox-gl-js/style-spec#other-function) and/or [deprecated filters](https://www.mapbox.com/mapbox-gl-js/style-spec#other-filter) in addition to expressions

Thoughts?

**Comment by pathmapper** [comment]
Expressions are now supported in Maputnik `v1.7.0`:

https://maputnik.github.io/blog/2020/04/23/release-v1.7.0
