### ISSUE TITLE
Custom layer property triggers infinite loop 

### ISSUE THREAD

**Issue by meetar** [maputnik/editor#467]
Hi Maputnik crew – I'm having some trouble running the editor locally.

I have a fork of the apollo-bright style hosted [here](https://meetar.github.io/ap-tilezen-mapbox-styles/src/styles/apollo-bright.json), with the fonts and sprites generated using the instructions in their README and hosted alongside the style, and the `{resource_url}` template expressions in the json replaced by absolute paths.

This can be successfully loaded via url by the current hosted editor: https://maputnik.github.io/editor

I also have a fork of the editor [here]( https://meetar.github.io/maputnik-editor/build/build/), with the `build/build` directory (generated by `npm run build`) pushed to `gh-pages`, which can successfully load all of the example files.

However, when I attempt to load the forked style in my forked editor, the editor gets stuck in an infinite loop of requests, apparently due to continuous `componentDidUpdate` calls, and nothing is drawn. The situation seems to be triggered by an external url included in the json file, eg https://github.com/meetar/ap-tilezen-mapbox-styles/commit/3ea1612b0858c1a64d6f1246e19e8c392dc51440 – when I remove this (and any part of the style which references it) the remainder of the style draws as expected.

`git-bisect` identifies the first commit which exhibits this behavior in this situation as https://github.com/maputnik/editor/commit/26ff9f63bbc5df818ed2ca176277d3376ca63d37 "Merge remote-tracking branch 'upstream/master' into fix/remove-componentWillUpdate".

I have the same trouble when serving the editor locally, whether using `npm start` or the node `http-server` package with the `--cors` flag.

Thanks!

**Comment by meetar** [comment]
I just reran `git bisect`, doing a `rm -rf node_modules && npm install && npm run build` each time, which identified 409f81f0d809a84bd9418c2705f63669c0f245f4 "More componentWillUpdate transition fixes." as the first commit exhibiting this behavior, which I think makes a bit more sense.

**Comment by meetar** [comment]
I have a workaround, using a trick from https://github.com/erikras/redux-form/issues/2629#issuecomment-297268290 – I'll submit a PR as a conversation piece, but this seems like something that shouldn't strictly be necessary :/

**Comment by pathmapper** [comment]
Hi @meetar,

some thoughts:

> This can be successfully loaded via url by the current hosted editor

If your style `https://meetar.github.io/ap-tilezen-mapbox-styles/src/styles/apollo-bright.json` is loaded with https://maputnik.github.io/editor, there are a lot of font loading errors (404) displayed in the console and the map is not displayed correctly:

![auswahl_448](https://user-images.githubusercontent.com/20856381/48661681-3d487780-ea76-11e8-8e10-03941611d77c.png)

> The situation seems to be triggered by an external url included in the json file

This shouldn't be a problem, e.g. https://maputnik.github.io/osm-liberty/style.json is working without problems.

The map is also not displayed correctly using just Mapbox GL JS without Maputnik ([jsbin](https://jsbin.com/kezinuweve/edit?html,output)), so I think the source of the problem could be related to your vector tiles source and/or the font hack you are using (merged fonts).

Do you have a working example where your style is used for rendering a map with Mapbox GL JS?

**Comment by pathmapper** [comment]
@meetar, in the meantime you removed the fonts (https://github.com/meetar/ap-tilezen-mapbox-styles/commit/e378334f36bd11c2392e72ff8b1afcf42f664a29), that's why your style wasn't working.

After replacing

`https://meetar.github.io/ap-tilezen-mapbox-styles/tile_fonts/{fontstack}/{range}.pbf`
with 
`https://maps.tilehosting.com/fonts/{fontstack}/{range}.pbf?key={key}`

and 

`{localization_name}`
with
`{name:en}`

your style works without issues with https://maputnik.github.io/editor/ (`v1.5.0`) and, if using a Maptiler key for the fonts, also with standalone GL JS `v0.51.0` and `v0.50.0-beta.1`.

So this is clearly a bug in Maputnik `master`, maybe related to https://github.com/maputnik/editor/issues/471.

Here is the style which I used to reproduce: 
[apollo.json.zip](https://github.com/maputnik/editor/files/2612587/apollo.json.zip)

**Comment by pathmapper** [comment]
The infinite loop is triggered by these lines of the `path-line` layer of the apollo bright style:
https://github.com/meetar/ap-tilezen-mapbox-styles/blob/e378334f36bd11c2392e72ff8b1afcf42f664a29/src/styles/apollo-bright.json#L665-L666

These lines are duplicated and belong to the layers layout object. If they are removed, the style works also with Maputnik `master`.

Submitted a [PR to the styles repository](https://github.com/apollo-mapping/ap-tilezen-mapbox-styles/pull/6/files), however we should prevent the editor to get stucked in an infinite loop in such cases.
