### ISSUE TITLE
JSON error handling

### ISSUE THREAD

**Issue by muesliq** [maputnik/editor#47]
It's extremely useful to be able to directly edit each layer's JSON code. However, JSON isn't tolerant to errors, so it's really easy to break things. Currently erroneous JSON code seems to be rejected by Maputnik, i.e. not saved. This happens without any visual feedback. This is not optimal. 

I really like the error handling https://github.com/erikandre/mapbox-gl-style-editor does. (Also, I guess there are ready-made error handling libraries out there.)

See the icons and their corresponding tooltips:

![screen shot 2017-01-04 at 16 35 53](https://cloud.githubusercontent.com/assets/1606618/21647830/1ddaa150-d29c-11e6-84a5-34e435047264.png)

![screen shot 2017-01-04 at 16 36 13](https://cloud.githubusercontent.com/assets/1606618/21647840/2586f796-d29c-11e6-9e03-6ddc0258a667.png)

![screen shot 2017-01-04 at 16 36 36](https://cloud.githubusercontent.com/assets/1606618/21647848/2e91dd7e-d29c-11e6-8a5d-2c5fd2537ca2.png)

Maybe also line numbering (lines within whole stylesheet file) would be useful.

**Comment by muesliq** [comment]
I checked, the editor above uses [Ace](https://ace.c9.io/) for syntax highlighting, line numbering and error handling. Should be easy to integrate it into Maputnik.

**Comment by orangemug** [comment]
It looks like codemirror can do this also http://codemirror.net/demo/lint.html. If we're all fine with adding a line number gutter in the json editor I'll probably have time this week.
