### ISSUE TITLE
Hash link to start editing of a JSON style

### ISSUE THREAD

**Issue by klokan** [maputnik/editor#48]
It would be great have a chance to create "Edit" links going to Maputnik instance (in our case on https://editor.openmaptiles.org/ - opening for editing directly a given JSON style (in future GitHub #3, but now at least loading the style from a given HTTP link).

Such a link can be also put into the GitHub repos of our styles.

**Comment by lukasmartinelli** [comment]
Yes I want that too #34. :+1:
