### ISSUE TITLE
Symbol layer: no input element for "Field"

### ISSUE THREAD

**Issue by sk1p** [maputnik/editor#481]
Version: 98ded98

When editing a Symbol layer, no form input is shown for "Field". I tracked this down to [this change in the style spec](https://github.com/mapbox/mapbox-gl-js/commit/b69b928841173fc6412724ee611707fb4ecc52c9), which introduced a new ["formatted" type](https://www.mapbox.com/mapbox-gl-js/style-spec/#types-formatted), which is used for `text-field`.

The doc for `text-field` now reads: ```If a plain `string` is provided, it will be treated as a `formatted` with default/inherited formatting options.```Maybe as a first measure, a `<StringInput />` could be used for `formatted` typed fields to provide the same functionality as before.

**Comment by pathmapper** [comment]
Hi @sk1p,
thanks a lot for reporting and tracking this down!

> Maybe as a first measure, a `<StringInput />` could be used for `formatted` typed fields to provide the same functionality as before.

Makes sense to me, looks like we need https://github.com/maputnik/editor/issues/223 for a complete fix.

**Comment by sk1p** [comment]
Ah, didn't know about expressions. Yeah, I guess the full syntax only makes sense together with expressions.
