### ISSUE TITLE
Style upload doesn't work 

### ISSUE THREAD

**Issue by muesliq** [maputnik/editor#49]
I tried to test style upload on http://maputnik.com/editor/, yet it didn't work. 

- No feedback was visible after upload a style of mine, the "Open Style" window was still there, looking the same as before. 
- The map and the layer list had not been updated.
- Yet the style settings and the sources menu had. The settings of my uploaded style are shown.

Tested in Chrome.

**Comment by lukasmartinelli** [comment]
I can reproduce it when uploading a style - open another style with open and then try to upload a new one.

**Comment by muesliq** [comment]
Does upload work for you in any situation? Doesn't for me.

**Comment by lukasmartinelli** [comment]
Yes it does. 
It might be I throw some errors when validating and additional metadat to the style when first uploaded. I'll figure it out.

**Comment by muesliq** [comment]
Ok. Let me know if you need more information.

**Comment by lukasmartinelli** [comment]
> Yes it does.
> It might be I throw some errors when validating and additional metadat to the style when first uploaded. I'll figure it out.

No I cannot replicate that. I can upload styles, even twice.


Can you look in the console window whether there are any errors? It might also be an issue with the style that Mapbox GL validate of the Mapbox GL version which is in Maputnik then reports.

**Comment by muesliq** [comment]
My bad, header was misconfigured. So just #54.
