### ISSUE TITLE
Remove appveyor for maputnik/desktop

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#493]
With https://github.com/maputnik/desktop/pull/3, Travis cross compiles the binary for windows, mac and linux so appveyor is not needed anymore and should be removed ([failing builds](https://ci.appveyor.com/project/lukasmartinelli/desktop/builds/22245197)).

Ping @orangemug

**Comment by pathmapper** [comment]
@lukasmartinelli could you please have look (your appveyor account is used here)?

**Comment by orangemug** [comment]
Removed the webhook for appveyor
