### ISSUE TITLE
Style by coding (YAML, ...)

### ISSUE THREAD

**Issue by klokan** [maputnik/editor#5]
At SOTM we have discussed a need to be able to write the style by hand as well...

There is the @tmcw codeflow project which demonstrates such approach with YAML, TOML and JSON5 syntax for the GL JSON format.

Details in:
http://www.macwright.org/2015/08/17/mapbox-gl-codeflow.html

The code:
https://github.com/mapbox/mapbox-gl-codeflow-example

**Comment by meekjt** [comment]
I agree, this would be helpful for styling attributes not yet supported by the graphical editor. YAML would be my first choice since it is more compact than JSON.

**Comment by lukasmartinelli** [comment]
I think this has been adressed with both the JSON editor within Maputnik in each layer and
the possibility to edit a JSON locally and have it sync up with Maputnik.

https://youtu.be/vCFsrwocE9s

[![Edit local Style JSON with Maputnik](https://j.gifs.com/JZK8yg.gif)](https://youtu.be/vCFsrwocE9s)
