### ISSUE TITLE
point

### ISSUE THREAD

**Issue by zl142900** [maputnik/editor#503]
The input box cannot enter the decimal point

**Comment by pathmapper** [comment]
Hi @zl142900 ,

could you please provide more details?

- Which version? (e.g. https://maputnik.github.io/editor, `master`, ...)
- Which input box exactly? (maybe you could mark it on a screenshot)

**Comment by zl142900** [comment]
I don't want the web side, I want to deploy the server side.I'm downloading the latest version of git, and then NumberInput doesn't allow you to enter the decimal point

**Comment by zl142900** [comment]
Copy and paste can add decimal point, but the keyboard input is not good, I hope you can give a solution, thank you very much!

**Comment by pathmapper** [comment]
Thanks, this bug is tracked in https://github.com/maputnik/editor/issues/488, closing here.

Until there is a solution you could use the [v1.5.0 release](https://github.com/maputnik/editor/releases/tag/v1.5.0).

**Comment by zl142900** [comment]
还有一个问题，我设置字体的url用本地的就行，然后用服务器上的字体就不行(本地和服务器的字体一样)，用服务器url它的报错：Failed prop type: Invalid prop `fonts` of type `object` supplied to `FontInput`, expected `array`.  这是我的字体文件缺少什么配置嘛？

**Comment by zl142900** [comment]
![image](https://user-images.githubusercontent.com/42824619/54105068-e3950000-440c-11e9-8715-4a8cd685a569.png)

**Comment by zl142900** [comment]
There is a problem, I set the font url with local line, then using the font is not on the server (local and server font), use server url it error: Failed prop type: Invalid prop ` fonts ` of type ` object ` supplied to ` FontInput `, expected ` array `. This is what is missing my font file configuration?

**Comment by pathmapper** [comment]
@zl142900 sorry, it's not clear what you are asking. If the error persists, please open a new issue with detailed information (e.g. the style you are using, font URL).
