### ISSUE TITLE
Regression: Map doesn't update when fill-pattern is changed

### ISSUE THREAD

**Issue by zl142900** [maputnik/editor#507]

**Comment by zl142900** [comment]
![image](https://user-images.githubusercontent.com/42824619/55392712-6faec900-556e-11e9-9de4-5a60b3c45961.png)
hi.Why are attributes removed,The icon is still there,What's the solution? thank you

**Comment by pathmapper** [comment]
Hi @zl142900 , 

thanks for reporting.

I guess you are seing this in `master` because in `v1.5.0` it works as espected, right?

This regression might be also related to #358.

**Comment by pathmapper** [comment]
As a workaround you may refresh the tab with the editor (`F5`).

**Comment by zl142900** [comment]
![image](https://user-images.githubusercontent.com/42824619/55466256-663a6500-5631-11e9-93e5-19863db84321.png)
I found that as long as this property is removed completely, the icon will disappear.But this is working in a JSON file, and what I'm thinking is that as soon as I clear the icon in the input box, this property disappears.
In addition, I also found that when I switch the icon for the second time, it will not change, only use the editor (F5) refresh TAB will take effect, this is what problem, I hope you can answer

**Comment by pathmapper** [comment]
It's a bug in `master`, it is currently not working as expected.

Have a look at the [`v1.5.0` release](https://github.com/maputnik/editor/releases/tag/v1.5.0), there it is working like it should.

The online version uses this `v1.5.0` release:
https://maputnik.github.io/editor/

**Comment by zl142900** [comment]
I've seen the v1.5.0 release, but it still doesn't solve my problem.What I want is if "fill-pattern" is null, can we just delete the "fill-pattern" attribute in JSON?

**Comment by zl142900** [comment]
![image](https://user-images.githubusercontent.com/42824619/55535478-f4722200-56e9-11e9-9d01-0f12e2b44e18.png)

**Comment by pathmapper** [comment]
> What I want is if "fill-pattern" is null, can we just delete the "fill-pattern" attribute in JSON?

Yes, `fill-pattern` is an optional paint property:
https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-fill-fill-pattern

With `v1.5.0` you may use the JSON editor (the one which is visible on your screenshot).

With `master` this is currently not possible because of https://github.com/maputnik/editor/issues/484. 
As a workaround, you could download the style, delete the property with the editor of your choice and upload it again to Maputnik.

**Comment by zl142900** [comment]
Thank you for your solution, but I think it is too troublesome.Can you modify it in the source code and add a judgment "if fill-pattern is null, delete the" fill-pattern "attribute

**Comment by pathmapper** [comment]
The are cases where the `fill-pattern` property should/must not be deleted even if the value is `null`.

An additional functionality to delete properties completely is tracked in #509.
