### ISSUE TITLE
UI feedback: Information hierarchy

### ISSUE THREAD

**Issue by muesliq** [maputnik/editor#51]
I like the UI, yet I think there is room for improvement. Status quo:

<img width="370" alt="screen shot 2017-01-04 at 21 28 26" src="https://cloud.githubusercontent.com/assets/1606618/21658069/52c56fac-d2c5-11e6-91eb-1320267480e5.png">

I recommend a stronger hierarchy between parents and children using size, indents and contrast:

<img width="371" alt="screen shot 2017-01-04 at 21 28 00" src="https://cloud.githubusercontent.com/assets/1606618/21658076/5bf1475e-d2c5-11e6-9887-8a64a7d21b5d.png">

(I forgot to make the header background color lighter, please imagine that, too ;-)

The same is true for the selected row in the layer list: Here higher contrast and maybe a bold font would help.

**Comment by lukasmartinelli** [comment]
It is at first sight indeed very difficult to orient yourself since everything looks the same.

**Comment by muesliq** [comment]
Yep. The perfect way would be to work on a really good color palette with good contrasts. The pragmatic way would be to simply use significantly lighter greys for headers, mouse-over and the active layer ;-) Plus bigger/stronger text for headers.

BTW, the fact that all CSS is inline and not in an external CSS file makes editing quite hard.

**Comment by lukasmartinelli** [comment]
I also found out that on bad contrast monitors the different shades of gray are probably too close to each other.

> BTW, the fact that all CSS is inline and not in an external CSS file makes editing quite hard.
 
I am also no longer so convinced from the React inline style approach as of the beginning of the project.
It is great for components that are used in other projects - but if it is mostly components for the same app stylesheets make sense again.

**Comment by muesliq** [comment]
Replaced by #64.
