### ISSUE TITLE
Ease of use for novice users

### ISSUE THREAD

**Issue by muesliq** [maputnik/editor#53]
Maputnik is easy to use for anybody really familiar with Mapbox GL. Novice users however will run into a range of road bumps:

1. **Macro: Questions related to how stylesheet, vector tile sources, fonts and sprites play together**
Less important to novice users, as they rarely start with blank styles. However links to documentation and/or tutorials may help here.
2. **Mini: Questions related to Mapbox GL Style properties**
This is currently solved with tooltips on some places. I believe this should be done with a deep link to each property within the [Mapbox GL Style Spec](https://www.mapbox.com/mapbox-gl-style-spec/). Mapbox is constantly improving the spec, this should not be replicated in my view.  
3. **Micro: Understanding of the concrete meaning of interface components**
This is where I would use tooltips. 

Let's look at the example of stops functions: 
<img width="363" alt="screen shot 2017-01-04 at 22 57 06" src="https://cloud.githubusercontent.com/assets/1606618/21661047/768c952a-d2d2-11e6-818a-22edfa18316d.png">

Here I would do the following:

- Add a deep link to the style spec beside "Width", maybe as a little "i" icon.
- Put a tooltip "Remove stop" to the delete icon.
- Put a tooltip "Zoom level" to the first text field
- Put a tooltip "Width" to the second

I _really_ would love to see some help sentences such as 

> Value of first stop will be used from lowest zoom level to zoom level indicated, value of last stop from zoom level indicated until highest zoom level. Between zoom levels values will be interpolated where possible. To avoid interpolation define two adjacent stops like 8.99 and 9.

Yet I'm afraid that's unrealistic. Let's hope Mapbox improve their style spec, and let's link there.

**Comment by lukasmartinelli** [comment]
I also thought about this.

Maputnik is a pro tool (as is Mapbox Studio and Tangram play etc..). It is quite hard to make it usable for style makers and the "just tweak the color" user.

The most effective way to make this easier for novice user would be to limit the amount of properties. Because when you are starting out you probably can deal with the color fields and text fields but everything else is too much at the beginning.

I try to counteract this by making videos/docs to educate users!

@muesliq Adding tooltips everyhwere is a great idea! I started adding some to the icons.
I think the most confusing parts are filters and zoom level functions for people who are not familiar with the GL style spec.

**Comment by muesliq** [comment]
Great! With "novice users" I actually meant those not fully familiar with the style spec, and less "just tweak the color"-users.

**Comment by orangemug** [comment]
Collapsing the JSON panel by default might help make it a little more friendly also.

**Comment by orangemug** [comment]
@muesliq @lukasmartinelli where are we with this ticket? It looks like we have tooltips in the UI, do we want to collapse the JSON editor by default, also is there anything else required?

**Comment by pathmapper** [comment]
For adding optional fallback font(s) for a layer, it seems like one has to use the JSON editor. Maybe it would be possible to implement it directly in "Text layout properties".

**Comment by muesliq** [comment]
> where are we with this ticket?

Tooltips are implemented, deep links into the GL style spec are not. They would be nice to have I think but the general usability for novice users is a lot better now. I am closing this ticket for now.

> do we want to collapse the JSON editor by default

Matter of taste. I would leave it open.

**Comment by orangemug** [comment]
> For adding optional fallback font(s) for a layer, it seems like one has to use the JSON editor. Maybe it would be possible to implement it directly in "Text layout properties".

@pathmapper that sounds like a new ticket, feel free to open one.
