### ISSUE TITLE
"type": "exponential" not found

### ISSUE THREAD

**Issue by toton6868** [maputnik/editor#536]
I am trying to create roads width increased exponentially. But there is no exponential option in UI. What should I do to add this?

**Comment by pathmapper** [comment]
Hi @toton6868 ,

what about using the JSON editor to add `"type": "exponential"`?

![Auswahl_589](https://user-images.githubusercontent.com/20856381/60386150-b474ce00-9a91-11e9-922d-5810fe3f6f26.png)

**Comment by toton6868** [comment]
I was using a version where I was unable to paste JSON. Updated and done. Thanks. Closing
