### ISSUE TITLE
Add support for text-rotate property functions

### ISSUE THREAD

**Issue by catarina7** [maputnik/editor#538]
I want to use text-rotate property functions.
We tried it on Maputnik, but it didn't apply.
It didn't seem to be able to read the property.
As a solution to this, the mapbox gl puts forward
text-rotate : {
      "type" : "identity",
      "property" : "rotation-attribute"
} 
but it didn't work neither.
I want a solution to this.

**Comment by pathmapper** [comment]
Hi @catarina7,

with `v1.5.0` it isn't working, but in `master` this is fixed.`

You may try it out here: https://1605-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html

![image](https://user-images.githubusercontent.com/20856381/60427974-27985480-9bf8-11e9-8426-290ecf69d6b5.png)

**Comment by catarina7** [comment]
thank you for your answer.
Is it OK to ask more questions? because the problem has not been resolved.
my project has lots of diffirent value rotate to String type. 
can i use rotate to one layer property value?
Filed : { } <-- like this.

**Comment by pathmapper** [comment]
> my project has lots of diffirent value rotate to String type.

Please be aware that `text-rotate` requires a number input:
https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-rotate

So in your example

```
text-rotate : {
"type" : "identity",
"property" : "rotation-attribute"
}
```

`rotation-attribute` must be of type number.

Does this help?

For questions about the use of Mapbox GL JS / Style Spec I recommend to post your question on https://gis.stackexchange.com/.

**Comment by catarina7** [comment]
I changed the type of data and confirmed that it was applied.
Thank you for your help!!
