### ISSUE TITLE
Editor shows nothing

### ISSUE THREAD

**Issue by zvukoper** [maputnik/editor#541]
Open http://maputnik.github.io/editor/
Only background color. No other visuals. Some relief features are visible in lowest zoom.
Google Chrome, latest. No blocking, no vpn.
![image](https://user-images.githubusercontent.com/511118/61690611-2cf24600-ad43-11e9-9f6e-569bd3ce334b.png)
![image](https://user-images.githubusercontent.com/511118/61690649-41364300-ad43-11e9-8c3e-36cfc32452ae.png)

**Comment by giumarzo** [comment]
I've got the same problem

**Comment by pathmapper** [comment]
@zvukoper @giumarzo thanks for reporting, looks like the default key for Maptiler Cloud is not valid anymore.

As a workaround you may create your own key on https://www.maptiler.com/cloud/ and insert it here:

![Auswahl_611](https://user-images.githubusercontent.com/20856381/61701104-e4845980-ad3d-11e9-810c-7e8708800127.png)

@klokan any idea why the default key is not valid anymore?

**Comment by pathmapper** [comment]
The reason the key was invalid was that we reached the limit of requests (100k requests). This old key is temporarily re-enabled for one week and we were asked to start using the new key (https://github.com/maputnik/editor/pull/542) as soon as possible.

**Comment by pathmapper** [comment]
@orangemug the key is invalid again, we should release `v1.6.0` now.

**Comment by pathmapper** [comment]
Maputnik v1.6.0 is released and available on: https://maputnik.github.io/editor/
