### ISSUE TITLE
Feature: scollable inspect popups

### ISSUE THREAD

**Issue by Lewik** [maputnik/editor#547]
Let just show it (black bottom stripe is the end of the browser screen, it's my taskbar)
Please make popups scrollable. And maybe accordion style.
![image](https://user-images.githubusercontent.com/1853182/62487027-702fc880-b7c9-11e9-814f-b1fde0cc66d5.png)

**Comment by pathmapper** [comment]
Thanks @Lewik, fix available for testing in https://github.com/maputnik/editor/pull/548

**Comment by Lewik** [comment]
@pathmapper Should I make any move?

**Comment by pathmapper** [comment]
@Lewik if you like, you could try out the fix
https://1724-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html
and give us a feedback.

**Comment by Lewik** [comment]
![image](https://user-images.githubusercontent.com/1853182/63331460-6ae08b00-c33e-11e9-97be-8e66b3a95f21.png)
As you see, there are still elements below the screen.

**Comment by pathmapper** [comment]
This is because at his zoom level you can't pan the map enough. If you zoom further in, you are able to make the popup fully visible if you pan the map.

**Comment by pathmapper** [comment]
@Lewik here is an updated version where the popup should be fully visible without the need to pan the map: https://1732-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html

**Comment by Lewik** [comment]
@pathmapper Looks ok

**Comment by Lewik** [comment]
What I need to do to make this thing merged?

**Comment by pathmapper** [comment]
It's merged now @Lewik
