### ISSUE TITLE
I cann't load style

### ISSUE THREAD

**Issue by HeiYanjing** [maputnik/editor#550]
![image](https://user-images.githubusercontent.com/42837853/64242667-88197a00-cf38-11e9-9c3a-818ffc5a5800.png)
![image](https://user-images.githubusercontent.com/42837853/64242678-8bad0100-cf38-11e9-8bb2-f95385a9f5e0.png)

![image](https://user-images.githubusercontent.com/42837853/64242740-a97a6600-cf38-11e9-9765-d114080edf6a.png)
these 4 types of style cann't be load.
this has happened before

**Comment by pathmapper** [comment]
This is a known issue, see https://github.com/maputnik/editor/issues/541 and https://github.com/maputnik/editor/pull/549

You may use https://maputnik.github.io/releases/v1.6.0-beta in the meantime.

Closing as duplicate.
