### ISSUE TITLE
Update OMT styles

### ISSUE THREAD

**Issue by michalkozak** [maputnik/editor#552]
Editor of Positron map does not work today:
Open https://editor.openmaptiles.org/ and choose Positron style.

The style is not loading ad the following error occurs in the console:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://free.tilehosting.com/data/v3.json?key=KDhMfHvorAFkFe64wlZb. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by orangemug** [comment]
Hi @michalkozak unfortunately that's nothing to do with the maputnik organisation. That's owned by https://www.klokantech.com/ so you'll have to ask them. You can load styles in the editor we hosted at https://maputnik.github.io/editor/ though

**Comment by pathmapper** [comment]
This effects all OpenMapTiles styles with https://free.tilehosting.com source URLs, also if you load them with https://maputnik.github.io/editor/ (yesterday they worked).

@klokan looks like there are no tiles delivered anymore via https://free.tilehosting.com and there is a need to update the source URLs for the various OMT styles, e.g. https://github.com/openmaptiles/positron-gl-style/blob/master/style.json#L27 .

@michalkozak here is the repo where you could report issues with https://editor.openmaptiles.org/:
https://github.com/openmaptiles/www.openmaptiles.org/

And here is the repo for the Positron style: https://github.com/openmaptiles/positron-gl-style

**Comment by pathmapper** [comment]
> here is the repo where you could report issues with https://editor.openmaptiles.org/:
> https://github.com/openmaptiles/www.openmaptiles.org/

That's not true anymore, https://editor.openmaptiles.org/ now redirects to https://cloud.maptiler.com/customize/ .

Submitted a PR to avoid confusion in the future: https://github.com/openmaptiles/www.openmaptiles.org/pull/37
