### ISSUE TITLE
Icon selection not working

### ISSUE THREAD

**Issue by petrsloup** [maputnik/editor#588]
For some reason, it is not possible to select an icon for certain properties (`icon-image`, `line-pattern`, ... ?) (tested in v1.6.1).

Looks like the `IconInput` does not get rendered at all and there is just an empty space:
![image](https://user-images.githubusercontent.com/707817/69627674-61587480-104b-11ea-9659-1ec7ad6b246d.png)

**Comment by pathmapper** [comment]
Thanks for reporting @petrsloup, confirmed also with `master`.
