### ISSUE TITLE
FeatureLayerPopup - Layer selection doesn't work

### ISSUE THREAD

**Issue by reallydamngood** [maputnik/editor#589]
Selecting layers from the sidebar works perfectly but: 

When I click on the map on an object and I choose a layer from the popup NOTHING happens. It's not highlighting any layer on the sidebar nor activating details panel...

Tool not usable at the moment. Tested on Safari/Chrome

**Comment by orangemug** [comment]
Thanks for the issue report. You can use a previous version while you wait for a fix https://maputnik.github.io/releases/v1.5.0

**Comment by pathmapper** [comment]
Layer selection from Popup isn't working since https://github.com/maputnik/editor/pull/483/commits/8f391d7d523c5f8df6d0d048d59ef09889269d0f .

@sk1p would you mind taking a look?

**Comment by sk1p** [comment]
@pathmapper Thanks for letting me know, I'll try to find time this weekend

**Comment by pathmapper** [comment]
From https://github.com/maputnik/editor/issues/594#issuecomment-573537487:

> When I have about 300 layers [...] I cannot choose proper layers – and it’s impossible to do it manually scrolling that big list.

**Comment by sk1p** [comment]
Thanks @orangemug for taking care of this - the time didn't materialize on my end sadly :(

**Comment by orangemug** [comment]
No problem @sk1p
