### ISSUE TITLE
import mapbox streets style?

### ISSUE THREAD

**Issue by quade1664** [maputnik/editor#590]
I've been struggling to get enough detail on zoomed in levels on the styles provided on the editor
I've seen mapbox streets zoomed in level has lots of nice detail like restaurants etc

Can I import the mapbox streets style on maptunik?
If not is there any style I can import that has more detail and is similar to the liberty skin (this skin is close to my final desired style)

**Comment by pathmapper** [comment]
> I've been struggling to get enough detail on zoomed in levels on the styles provided on the editor

Hi @quade1664, I wonder for which area you are missing the POIs? Here is the unmodified `OSM Liberty` style showing an area with lots of restaurants.

https://maputnik.github.io/editor/?style=https://maputnik.github.io/osm-liberty/style.json#17.77/50.780091/6.079869

> Can I import the mapbox streets style on maptunik?

In general it is possible to open Mapbox styles in Maputnik, but you must comply with their [Terms of Service](https://www.mapbox.com/legal/tos) and the licence for the specific style.

**Comment by quade1664** [comment]
Thanks @pathmapper 

That was super helpful, I can see where I was going wrong
My other question (zoom level/ detail related) is related to roads that appear at different zoom levels
Basically I want more roads to appear at certain zoom levels, currently they only appear when zoomed in quite far, however mapbox has more roads appearing when zoomed out.

This is best explained with pics
For example, this is what i'm trying to achieve (the minor roads on this zoom level)
![mapbox1](https://user-images.githubusercontent.com/7437372/70784426-aa722d80-1d9a-11ea-9e67-3983b5a7d7b1.png)


However, i'm noticing these roads do not appear at the same zoom levels on maputnik, if you zoom in a lot further they will show
For example, they dont show here https://maputnik.github.io/editor/#11.96/-1.27775/36.7635
If you zoom in one more level they show.
I need minor roads to show on same/similar zoom levels as mapbox.

On mapbox they show when you are zoomed out quite far 
https://api.mapbox.com/styles/v1/mapbox/streets-v11.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#11.3/-1.2873/36.8146


This is an example of the area without the minor roads
![Maputnik1](https://user-images.githubusercontent.com/7437372/70785243-4439da80-1d9b-11ea-8545-7f806ddd0257.png)

When I switch from Inspect to Map view they are also not present
![Maputnik2](https://user-images.githubusercontent.com/7437372/70785282-561b7d80-1d9b-11ea-9e34-4e5678b535aa.png)


However when I zoom in they are present
![Maputnik3](https://user-images.githubusercontent.com/7437372/70785316-66335d00-1d9b-11ea-865f-bf0dce697560.png)


Is there anything i'm doing wrong or that can be done to get these minor roads to show at zoom levels similar to mapbox?

**Comment by pathmapper** [comment]
The `OSM Liberty` style uses OpenMapTiles vector tiles as source for these minor roads, and these are included in the tiles starting with zoom level 12:
https://openmaptiles.org/schema/#transportation
https://github.com/openmaptiles/openmaptiles/tree/master/layers/transportation

If you want them to be included sooner, you could modify the OpenMapTiles code and generate your own tiles or you create a custom tileset just for the roads using OpenStreetMap data.
If you have further questions about this matter, I suggest to have a look at the issues at the OpenMapTiles repository or post a question on https://gis.stackexchange.com/.

Closing here, as this is not a question regarding Maputnik.

**Comment by quade1664** [comment]
thanks!
