### ISSUE TITLE
.json doesn't work - values are blocked

### ISSUE THREAD

**Issue by reallydamngood** [maputnik/editor#594]
Hi, I have problem with editing particural .json - I get errors while editing anything. Every value I enter resets automatically (it's blocked)

Some of the errors:
layers[2031].paint.line-color.stops[1][0]: integer expected, found 0.01
layers[2031].paint.line-color.stops[2][0]: integer expected, found 0.8

I added flow layers to the map with the source, maybe I messed things up.

**Comment by pathmapper** [comment]
Hi @reallydamngood, 

could you share a `style.json` which allows to reproduce the issue?

**Comment by reallydamngood** [comment]
I’m not sure if I can do that because of the policy rules. Weird thing is that it works perfectly without any error in our inner tool powered by maputnik v.1.5.0. – and I’m using the same file.

> Adrian Dąbrowski  /  UX/UI Designer  /  TomTom Traffic and Travel Information  /  adrian.dabrowski@tomtom.com  / www.tomtom.com​​

**Comment by pathmapper** [comment]
https://maputnik.github.io/editor/ uses `v1.6.1` so this could be a regression since `v1.5.0` .

Maybe you could modify https://maputnik.github.io/osm-liberty/style.json, so that it produces the error you are seeing.

**Comment by pathmapper** [comment]
You could also try your style with Maputnik `master` to find out if the issue still exists there:
https://2026-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html

**Comment by reallydamngood** [comment]
Master version works fine! :) But is useless because selecting a layer from the map tooltip doesn’t work.

> Adrian Dąbrowski  /  UX/UI Designer  /  TomTom Traffic and Travel Information  /  adrian.dabrowski@tomtom.com  / www.tomtom.com​​

**Comment by pathmapper** [comment]
Thanks for your feedback - I wouldn't say useless. 

You know that the tooltip issue is tracked in https://github.com/maputnik/editor/issues/589. Feel free to submit a PR to fix this.

**Comment by reallydamngood** [comment]
When I have about 300 layers, well yes, it’s useless because I cannot choose proper layers – and it’s impossible to do it manually scrolling that big list.

> Adrian Dąbrowski  /  UX/UI Designer  /  TomTom Traffic and Travel Information  /  adrian.dabrowski@tomtom.com  / www.tomtom.com​​

**Comment by pathmapper** [comment]
Thanks for the information regarding your use case, now I can understand why the tooltip issue is a blocker for you. 

Added this information to https://github.com/maputnik/editor/issues/589.
