### ISSUE TITLE
Layer tooltips should be clickable

### ISSUE THREAD

**Issue by muesliq** [maputnik/editor#60]
It would be a big improvement if layers were clickable, opening the corresponding layer in the sidebar. 

![screen shot 2017-01-10 at 14 19 45](https://cloud.githubusercontent.com/assets/1606618/21807671/38f5a748-d740-11e6-82cc-5ad14578a417.png)

(Better even: Highlight the layer in the sidebar already on hover.)

**Comment by klokan** [comment]
+1

**Comment by gregorywolanski** [comment]
I'm working on it. I need to get https://github.com/lukasmartinelli/mapbox-gl-inspect/pull/8 merged to finish this enhancement. :)

**Comment by orangemug** [comment]
Released in [v1.1.0-beta2](https://maputnik.github.io/releases/v1.1.0-beta2)
