### ISSUE TITLE
Filter buildings by ID or type

### ISSUE THREAD

**Issue by biocom** [maputnik/editor#608]
I've been reviewing all related issues in regard to filtering specific features. I'm trying to apply different colors to different types of buildings.

With Maputnik and Openmaptiles I'm currently only able to apply different colors to buildings by:
- using the `render_height` values. But these are not always present or very similar (e.g. apartments with a render_height of 5).

I'm aware of the `landuse` property, but that doesn't target the building polygon on its own.

Is there a way at the moment to filter buildings (and apply a specific color) based on the type of building or even its type ID?

<img width="241" alt="Screenshot 2020-01-24 at 11 42 54" src="https://user-images.githubusercontent.com/31534717/73063484-2c2b9f80-3e9f-11ea-8939-98427cd3b7b2.png">

**Comment by pathmapper** [comment]
Hi @biocom,

if you're using the default OpenMapTiles (OMT) as source, you could only use the fields to filter building which are available there.

Here is the OMT schema for the building layer:
https://openmaptiles.org/schema/#building

As you can see, there is no field indicating the type of a building or a unique ID.

There is a `colour` field which is derived from https://wiki.openstreetmap.org/wiki/Key:building:colour but this field indicates the colour of the facade of a building or building part and is not available for all buildings.

![image](https://user-images.githubusercontent.com/20856381/73117015-f68ac300-3f3f-11ea-9f86-2fa9089d18c1.png)

If you need type or ID of a building included in the source, you could modify the OpenMapTiles code and generate your own tiles or you could create a custom tileset just for the buildings using OpenStreetMap data.

If you are having further questions about this matter, I suggest to have a look at the [issues at the OpenMapTiles repository](https://github.com/openmaptiles/openmaptiles/issues) (there are similar questions) or post a question on https://gis.stackexchange.com/.

Closing here, as this is not a question regarding Maputnik.

**Comment by biocom** [comment]
Thank you for your answer. I'll try to look for additional building data.
