### ISSUE TITLE
[bug] Inspect layer from map stage

### ISSUE THREAD

**Issue by Jinkwon** [maputnik/editor#623]
I clicked layer (**road_minor**) from this popup, but does not indicate what I chosen a layer. 
Is this bug or not?
(even cursor has been changed to pointer)

<img width="327" alt="스크린샷 2020-03-24 오후 6 33 12" src="https://user-images.githubusercontent.com/1798916/77410232-ef781800-6dfd-11ea-8734-c061d2048cab.png">

I tested this site https://maputnik.github.io/editor/#1.52/0/0

**Comment by pathmapper** [comment]
Hi @Jinkwon,

thanks for reporting, this was already fixed in https://github.com/maputnik/editor/pull/600.

You may use Maputnik `master` until the next release:
https://2216-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html
