### ISSUE TITLE
Sprite and glyph url not working

### ISSUE THREAD

**Issue by yaras-phoenix** [maputnik/editor#631]
I'm a newbee to mapbox and vector tiles (...and github too) and have some issues with using my own sprite nd glyph.

 Using spritezero-cli I created a test sprite (JSON and png), uploaded it on server and got a url I needed. I pasted it it Sprite URL and tried to apply a pattern to a fill-layer but it was disabled.  Chrome devtools shows that both sprite files are fetched with code 200.

Next, using this tutorial: https://developer.tomtom.com/maps-sdk-web/tutorials-advanced/creating-custom-glyphs I created a glyph pbf resource containing 2 fonts. I provided a url to it and tried to choose any available font in my symbol-layer for labels but no font shows.

Any help would be appreciated, I have no idea what I am doing wrong. 

Glyphs and sprite urls lead to our company's server so I cannot publish them here. Is there any resource where I can share them in public?

**Comment by pathmapper** [comment]
Hi @yaras-phoenix,

without a reproducible test case we can't diagnose the issue.

You may take a look a the [OSM Liberty](https://github.com/maputnik/osm-libertyl) style to see how sprite and glyphs are working there:

https://github.com/maputnik/osm-liberty/blob/gh-pages/style.json#L22-L23

**Comment by yaras-phoenix** [comment]
> Hi @yaras-phoenix,
> 
> without a reproducible test case we can't diagnose the issue.
> 
> You may take a look a the [OSM Liberty](https://github.com/maputnik/osm-libertyl) style to see how sprite and glyphs are working there:
> 
> https://github.com/maputnik/osm-liberty/blob/gh-pages/style.json#L22-L23

Implementing urls in style.json doesn't seem to be a problem.

To reproduce my case, I could attach here glyphs and sprite files. Will it be enough?

**Comment by pathmapper** [comment]
This issue tracker is for bug reporting and feature requests regarding Maputnik.
If it's a problem about your glyphs and sprites and not an issue with Maputnik, I recommend to ask at https://gis.stackexchange.com/. 

If you think it is a problem with Maputnik, please submit a style file which allows to reproduce the issue.

**Comment by yaras-phoenix** [comment]
Got it! Will try stackexchange.
