### ISSUE TITLE
Design brushup proposal

### ISSUE THREAD

**Issue by muesliq** [maputnik/editor#64]
I drafted a quick proposal how to make the UI clearer and easier to use. Feel free to use it or not ;-)

![maputnik2](https://cloud.githubusercontent.com/assets/1606618/21817767/9cbc2764-d765-11e6-87d9-c9d5b21e8e69.png)

### Colors:

- White: 
Section title font
Active layer font
Button font + stroke 1px
Active input field
- 666666
All other fonts
Scrollbars
- 262626
Active layer background
Hover layer background
Section header background
- 1a1a1a
Header background
First sidebar background
- 212121
Second sidebar background
- 353535
Input field + dropdown background
- 505050
Input field + dropdown stroke 1px

### Font sizes:
- 14px: Section Titles
- 11px: Form controls + buttons
- 12px: Layer list, form labels

### Left margins:
- 10px: Layer list, Section titles
- 20px: Form labels

**Comment by lukasmartinelli** [comment]
Very nice I like it. Thanks a lot, appreciate it.
Will track progress on it on this ticket.

**Comment by orangemug** [comment]
You may want to increase the contrast slightly for accessibility reasons. For example `#262626` on a `#666666` background fails _Web Content Accessibility Guidelines contrast ratio_ see http://leaverou.github.io/contrast-ratio/#%23666666-on-%23262626

**Comment by muesliq** [comment]
You are right @orangemug.

I updated the mockup, also with some color changes and checkboxes added.

![maputnik3](https://cloud.githubusercontent.com/assets/1606618/21844692/e5d75286-d7ef-11e6-8193-575165b9ea5e.png)

### Colors:

- White: 
Section title font
Active layer font
Button font + stroke 1px
Input field font
Selected checkbox button font
Active input field background
- 666666
All other fonts
Scrollbars
- 353535
Active layer background
Hover layer background
Section header background
Input field + dropdown background
- 1a1a1a
Header background
First sidebar background
Mouse over checkbox button background
- 212121
Second sidebar background
- 505050
Selected checkbox button background
Input field + dropdown stroke 1px

### Font sizes:
- 14px: Section Titles
- 11px: Form controls + buttons
- 12px: Layer list, form labels

### Left margins:
- 10px: Layer list, Section titles
- 20px: Form labels

**Comment by muesliq** [comment]
Alternative "Add filter" styling:

![screen shot 2017-01-11 at 11 47 20](https://cloud.githubusercontent.com/assets/1606618/21845665/ca9f3d4a-d7f3-11e6-83ca-ac2359c3d057.png)

**Comment by lukasmartinelli** [comment]
Migrated all inline-styles to CSS (larger effort than i thought - but also helped to clean up).

I already implemented some of the suggestions.
**Styles can now be directly tweaked at https://github.com/maputnik/editor/tree/master/src/styles**

**Comment by lukasmartinelli** [comment]
The colors all depend on the variables in https://github.com/maputnik/editor/blob/master/src/styles/index.scss.
So there is one place to tweak colors.

**Comment by muesliq** [comment]
One more thing: With a section header "Layers" in the first sidebar the "Add Layer" button can be moved from the page header to the sidebar. (I find the original position a little bit odd.)

![screen shot 2017-01-11 at 14 01 40](https://cloud.githubusercontent.com/assets/1606618/21850097/456c0f16-d809-11e6-877b-1b436a5e0ac6.png)

**Comment by lukasmartinelli** [comment]
> One more thing: With a section header "Layers" in the first sidebar the "Add Layer" button can be moved from the page header to the sidebar. (I find the original position a little bit odd.)

Yes sidebar is more suitable!!
Feedback on modals and the menu is welcome as well. 

Sources icon is not ideal  but the name "Sources" indicates the right thing I think.
Download will probably in the future change to "Export" to open a modal.

**Comment by muesliq** [comment]
I thought about the menu and the modals and found only two more (minor) issues:

1. The "Inspect" Button is actually an on/off button, so it should visibly change state. Either by conveying on/off (colors?) or by switching the wording (Inspect mode / Map mode or X-Ray view / Map view).
2. In the "Sources" modal I find "Choose public sources" more important than "Add new source". Would move it up.

**Comment by lukasmartinelli** [comment]
![screenshot from 2017-01-11 16-33-47](https://cloud.githubusercontent.com/assets/1288339/21854676/e792f3ba-d81b-11e6-9503-f04416daca29.png)


- [ ] Try out how Lucida Sans looks

**Comment by lukasmartinelli** [comment]
> Lucida Sans Regular: Everything else

@muesliq After some Google searches I don't think that's a free font..

**Comment by muesliq** [comment]
Lucida Sans Unicode is a "web safe font", so you don't need to embed it or worry about licensing, you just reference it. Like, you know, in the old days ;-)

**Comment by muesliq** [comment]
Most of the points have been implemented, I'm closing this now.
