### ISSUE TITLE
Add support for identity functions

### ISSUE THREAD

**Issue by orangemug** [maputnik/editor#640]
First raised by @pathmapper in https://github.com/maputnik/editor/issues/629#issuecomment-609777086

We don't currently have support for [identity functions](https://docs.mapbox.com/mapbox-gl-js/style-spec/other/#function-type) 

![image](https://user-images.githubusercontent.com/20856381/78560537-87bac780-7816-11ea-9922-60e6e07e9a56.png)

So I think we can add it to the data functions UI, we'll add another option to the `<select/>` box labeled `identity` and it'll just have a property value, like the following (but with `identity` instead of `exponential`)

<img width="370" alt="Screenshot 2020-04-06 at 20 07 07" src="https://user-images.githubusercontent.com/235915/78595692-64a60d00-7842-11ea-8ea9-495d479064b2.png">

Thoughts?

**Comment by pathmapper** [comment]
Sounds like a good idea @orangemug
