### ISSUE TITLE
Inspect mode: this.paint / t.paint is undefined

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#648]
Steps to reproduce:
1. Use https://maputnik.github.io/releases/v1.7.0-beta2/
2. Open the `OSM Liberty` style
3. Switch to inspect mode
4. Pan and zoom to the center of London and move the mouse pointer over the map
5. See errors in browser console

![grafik](https://user-images.githubusercontent.com/20856381/79096310-0f478f80-7d5d-11ea-97db-a4da81400d10.png)

**Comment by orangemug** [comment]
Looking at this issue locally I can see it's in mapbox-gl-inspect

<img width="502" alt="Screenshot 2020-04-13 at 11 05 07" src="https://user-images.githubusercontent.com/235915/79112608-d7e5dc80-7d76-11ea-83ae-48ba478100e2.png">

<img width="487" alt="Screenshot 2020-04-13 at 11 07 15" src="https://user-images.githubusercontent.com/235915/79112699-0cf22f00-7d77-11ea-841a-44085266e0f9.png">

It doesn't appear to cause an UI issue, @pathmapper can you confirm, if so I suggest we leave this until after v1.7.0

Also note: Appears to only be an issue in Firefox

**Comment by pathmapper** [comment]
> It doesn't appear to cause an UI issue, @pathmapper can you confirm

Right, I don't see any UI issues. 
I think these errors are emitted  because `queryRenderedFeatures` queries the features before the tiles are fully loaded. If this is correct, there might be failing `queryRenderedFeatures` request but the user won't notice them because 
- `queryRenderedFeatures` requests are fired constantly by moving the mouse pointer so the popup is updated very often
- It's hard to tell if a `queryRenderedFeatures` request fails, it could be also that the mouse pointer is pointing closely aside a feature.

>  suggest we leave this until after v1.7.0

Yeah, sure. Not everything that comes across while testing the `v1.7.0-betas` needs to be fixed for  `v1.7.0` :smile: 

> Appears to only be an issue in Firefox

Exactly these errors I'm seeing only in Firefox, but in Chrome I get different errors which could be related:

![grafik](https://user-images.githubusercontent.com/20856381/79120548-6f592880-7d93-11ea-8167-4d176af88695.png)
