### ISSUE TITLE
Sources Modal: Multiple tile source URLs for sources with XYZ URLs

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#656]
For sources with XYZ URLs the field label states `1st Tile URL` while the tooltip from the spec says it could be "an array of one **or more** tile source URLs":

![grafik](https://user-images.githubusercontent.com/20856381/79128488-e4ccf500-7da3-11ea-93f8-403a55f1c978.png)

@orangemug is there a special reason why it is currently not possible to enter multiple tile source URLs? Or is it possible and only the label is not correct? Is https://github.com/maputnik/editor/issues/234 related?

**Comment by orangemug** [comment]
@pathmapper I think it's just never been implemented to allow multiple urls. I think we should make it an aim to be 'spec complete' on the data sources for `v1.8.0`. Lets put a plan together after `v1.7.0`

**Comment by pathmapper** [comment]
All right @orangemug, created a `v1.8.0` milestone and added this task.
