### ISSUE TITLE
feature id in Inspection Mode

### ISSUE THREAD

**Issue by Caahlo** [maputnik/editor#657]
In the past weeks, I've been using Maputnik a lot to create and play with some styles. It worked really well so far.

Some days ago I've added a [feature id](https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/#ids) to the vector tiles. When I open Inspection mode this feature id is not displayed.

I'm using [Tegola](https://tegola.io/) to serve the vector tiles. I've checked the tiles there and I can see the feature id there.

It would be very useful if it would be displayed in the Inspection Mode of Maputnik. It would make styling maps more convenient and it would help with some debugging.

**Comment by pathmapper** [comment]
Hi @Caahlo thanks for your feedback and the suggestion.

I also think this is very useful. You may try it out in https://github.com/maputnik/editor/pull/658.
