### ISSUE TITLE
[v1.7.0-beta3] inline GeoJson support broken

### ISSUE THREAD

**Issue by moodstubos** [maputnik/editor#660]
in current beta of version 1.7 the inline GeoJson is tried to be validaded against mapbox style json

for me this makes no sense

![image](https://user-images.githubusercontent.com/5072232/79730674-76cb8500-82f1-11ea-92b5-9a4285adeed1.png)

**Comment by orangemug** [comment]
Thanks for the report @moodstubos fixed in #661
