### ISSUE TITLE
"newStyle" not found when building Desktop CLI

### ISSUE THREAD

**Issue by nspringer-trimble** [maputnik/editor#662]
https://github.com/maputnik/editor/blob/184bfeeaf85313cfa780d653bd2dad52b4942baf/src/libs/apistore.js#L70

Should be `style.replaceAccessTokens(mapStyle)`

**Comment by orangemug** [comment]
Thanks @nspringer-trimble, so when I said in #606

> Merging, I will give it a proper test in v1.7.0-beta3
https://github.com/maputnik/editor/pull/606#issuecomment-616067485

It turns out I forgot... Any interest in raising a PR and giving desktop a test with the fixes mentioned above?

**Comment by nspringer-trimble** [comment]
I tried publishing a branch but no permissions

**Comment by nspringer-trimble** [comment]
PR sent

**Comment by orangemug** [comment]
Closed by #663
