### ISSUE TITLE
Zoomstack style: Wrong name for water feature

### ISSUE THREAD

**Issue by mzu** [maputnik/editor#664]
Hi, I am new to OSM and Mapbox style, so I hope this is the right place to bring this up.

I came across an issue with the Zoomstack Outdoor style. 
Some of the`Water names` are labelled the wrong way. 

On the following map the lake shows up as 'River Derwent':
https://maputnik.github.io/editor/#13.27/54.65557/-3.20851

when in fact the name is 'Bassenthwaite Lake'
https://www.openstreetmap.org/query?lat=54.6513&lon=-3.2145

I assume this is not based on OSM and they use their own data. 

Is this something you would forward to ordnancesurvey.co.uk since they provided the style?

**Comment by pathmapper** [comment]
Hi @mzu, 

you're right that this is related to the Zoomstack Outdoor style (or the corresponding source).

We just published Maputnik `v1.7.0` and this brings Zoomstack `v2` (see https://github.com/maputnik/editor/pull/575).

Looks like this fixed the naming issue you mentioned:

![grafik](https://user-images.githubusercontent.com/20856381/80280547-fcda3800-8704-11ea-8a75-e75646339c05.png)

> Is this something you would forward to ordnancesurvey.co.uk since they provided the style?

@snodnipper, for similar issues, is the best way to report them via the OS website as shown below?

https://www.ordnancesurvey.co.uk/contact-us
![grafik](https://user-images.githubusercontent.com/20856381/80280770-7c1c3b80-8706-11ea-8620-be445c60ea24.png)

**Comment by snodnipper** [comment]
> @snodnipper, for similar issues, is the best way to report them via the OS website as shown below?

Hi @pathmapper, yes, those are the official channels so if you haven't done so already then please send your feedback.  External feedback is highly valued and can lead to resource being allocated to meet customer demand.

I have just downloaded the OS Open Rivers data and I note the omission.  I believe this is _because such data falls outside of the "open data specification" for rivers_ and may only be available in the premium datasets.

In terms of informal communication I would recommend getting in contact with [Charley Glynn](https://twitter.com/charley_glynn) or [Paul Naylor](https://twitter.com/cartocraftsman) via Twitter.  Both spend a lot of time with startups and collate a lot of data points for OS.

@charleyglynn

**Comment by snodnipper** [comment]
@mzu thanks for the feedback.  Sadly this is a data issue rather than a style issue.

**Comment by pathmapper** [comment]
Hi @snodnipper, thanks for your feedback and providing all these contact options, very helpful.

I think in the future we'll provide some information along with the data sources available in Maputnik (https://github.com/maputnik/editor/issues/643), so it would be easier for users to learn about the official feedback channels to report issues.

@mzu closing here, if you are still seeing naming issues, you now know where you could report them :-)
