### ISSUE TITLE
Add issue template(s)

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#670]
For a bug report or question it happens quite often that it's not clear which Maputnik version is used and also how to reproduce the case.

We could add issue template(s) to ask for these kind of information:

https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by orangemug** [comment]
Sounds good to me. The 'bug report' seems most useful to me, so what info do we need?

 - Description of the bug + steps to reproduce the bug
 - Maputnik version
 - Browser version

Maybe also mention about adding screenshots somewhere, because they're usually super useful.

**Comment by pathmapper** [comment]
> Maybe also mention about adding screenshots somewhere, because they're usually super useful.

Yep, and also providing a style file or style URL if it's related or makes reproducing the issue easier.

- OS (Windows, macOS, Linux)

**Comment by orangemug** [comment]
> Yep, and also providing a style file or style URL if it's related or makes reproducing the issue easier.

Good call, that's really useful.

> OS (Windows, macOS, Linux)

👍

**Comment by pathmapper** [comment]
Issue templates are now available (#689, #690).
