### ISSUE TITLE
Show source name in inspect popup

### ISSUE THREAD

**Issue by nspringer-trimble** [maputnik/editor#672]
We use multiple MBTile sources and when I inspect there are sometimes `source-layer` IDs with same name from different sources.  I propose adding the source name prepended to the source-layer name.
![image](https://user-images.githubusercontent.com/7513188/80413045-c9caac80-889c-11ea-9930-123743d88de9.png)

I have a branch with this change locally.

**Comment by orangemug** [comment]
Makes sense to me @nspringer-trimble, please make the pull request.

**Comment by nspringer-trimble** [comment]
It's not letting me push my branch

**Comment by pathmapper** [comment]
@nspringer-trimble did you try to push your local branch to your fork https://github.com/nspringer-trimble/editor? This should be possible and then the GitHub UI should should show you an option to make a PR.
