### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#679]
For the upcoming release we are having a few issues related to our workflow on our list:

- Automate desktop builds (https://github.com/maputnik/editor/issues/668)
- Automate deployments (#173)
- Bot for posting test build link to PR (#456)
- Provide docker images for releases on dockerhub (#489)

We could investigate if it's possible and suitable to use Github Actions for all these tasks:
https://github.com/features/actions

OpenMapTiles is now using the GitHub Actions Bot to post performance evaluation results for PRs, e.g. https://github.com/openmaptiles/openmaptiles/pull/841#issuecomment-621738878.

It should be also possible to automate publishing docker images with GitHub Actions for GitHub Packages:

https://help.github.com/en/packages

https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages

**Comment by orangemug** [comment]
The one thing that's missing from GitHub actions is demo URLs, CircleCI seems a little unique in being able to render html page artifacts without a download (correct me if I'm wrong). So I think we'd need CircleCI for demo URLs still.

GitHub actions seems good for everything else to me though, although I've only played about with it. 

> It should be also possible to automate publishing docker images with GitHub Actions for GitHub Packages:

That's a good shout since we haven't got access to the dockerhub account we can just publish to GitHub packages instead.

**Comment by pathmapper** [comment]
> The one thing that's missing from GitHub actions is demo URLs, CircleCI seems a little unique in being able to render html page artifacts without a download (correct me if I'm wrong). 

I think you're right @orangemug.

> So I think we'd need CircleCI for demo URLs still.

What about uploading the build artifacts to `gh-pages` using the PR number as name and linking them from the PR? 

https://github.com/marketplace/actions/deploy-to-github-pages

**Comment by orangemug** [comment]
> What about uploading the build artifacts to gh-pages using the PR number as name and linking them from the PR?

Possibly, I guess the down side of that is that we'll need to deal with expiry of artifacts over time as they can get quite large

```
# du -h v1.7.0
660K	v1.7.0/fonts
 13M	v1.7.0
```

Although I guess the repo compression _might_ limit the negative effect of that with files not changing that much. Does anybody else do this publishing of builds to `gh-pages` at the moment do you know? Also trying to think if there are any security concerns with that... 🤔

**Comment by pathmapper** [comment]
> Does anybody else do this publishing of builds to gh-pages at the moment do you know?

No, I'm not aware of anybody.

> if there are any security concerns with that...

Right, after thinking more about it I think we shouldn't do that.

**Comment by orangemug** [comment]
Hey @pathmapper so continuing with our discussion on GitHub actions I've been playing about with CI tooling. I'm currently messing around with some changes in a copy of the maputnik/editor repo. You can find that at https://github.com/orangemug/editor-ci-test

My initial aims are

 - Cross platform builds mac/windows/linux
 - A single job to test against selenium-standalone outputting the code coverage, as we have currently with CircleCI (I'm most of the way there with this)
 - Docker image deployment to the GitHub registry
 - I've also just signed up to browserstack which gives us free cross browser automation for webdriver tests.

With regards to PR demo links, codesandbox is looking pretty promising for this. With the following link it fetches the code at `orangemug/editor-ci-test` on the branch `demo/codesandbox-pr-2` builds, installs the deps and runs the server
https://codesandbox.io/embed/github/orangemug/editor-ci-test/tree/demo/codesandbox-pr-2?view=preview. I'm really impressed by it. I was thinking we could fetch the user/branch for a given PR in a GitHub action and post that to a PR comment (also via the same GitHub action).

Note that the loading of preview links via codesandbox is currently a little slow. So I guess the question is @pathmapper, do you think it's too slow initially? Long term the JS community has made some good steps at improving dev setup recently. If we improve the dev setup time then we'll improve both development and our preview links within codesandbox.

**Comment by orangemug** [comment]
So yesterday I got the following working in my sandbox

Cross platform builds (ubuntu, mac & linux)

![Screenshot 2020-05-23 at 12 26 18](https://user-images.githubusercontent.com/235915/82729598-ba4e5000-9cf0-11ea-9829-33b8c8673bfd.png)

Build comments added by github action

 - https://github.com/orangemug/editor-ci-test/runs/700271984?check_suite_focus=true
 - https://github.com/orangemug/editor-ci-test/pull/2#issuecomment-632790332

![Screenshot 2020-05-23 at 12 23 49](https://user-images.githubusercontent.com/235915/82729625-ec5fb200-9cf0-11ea-95df-cc1d309f7091.png)

Publishing of docker image via GitHub action https://github.com/orangemug/editor-ci-test/packages

Selenium test running within a github action https://github.com/orangemug/editor-ci-test/runs/700272012?check_suite_focus=true

![Screenshot 2020-05-23 at 12 30 31](https://user-images.githubusercontent.com/235915/82729676-452f4a80-9cf1-11ea-9509-45b7cf71315e.png)

It seems to work pretty well the entire suite is running in about ~3m30s and it seems stable 🤞

I'm going to make a tidy pull request with all the currently functionality into `maputnik/editor`, there are a few _GitHub action_ specific hacks with the webdriver tests that I need to fix for local development. This PR should resolve the following issues

 - https://github.com/maputnik/editor/issues/456
 - https://github.com/maputnik/editor/issues/489

Let me know any thoughts/feedback.

**Comment by pathmapper** [comment]
Wow, this looks great @orangemug :tada:  

> do you think it's too slow initially?

No, I think it's fine for our purpose.

> I'm going to make a tidy pull request with all the currently functionality into maputnik/editor

:+1:
