### ISSUE TITLE
Improve Property Groups

### ISSUE THREAD

**Issue by lukasmartinelli** [maputnik/editor#68]
This is a good task for a first commit of external contributors.

The properties in Maputnik are grouped together in the editor.
These groups are defined in `src/config/layout.json` https://github.com/maputnik/editor/blob/master/src/config/layout.json and can be tweaked very easily.

- [ ] Look at existing groups
- [ ] Think about how to best group Mapbox GL properties together so it makes sense contextually

![screenshot from 2017-01-11 20-52-34](https://cloud.githubusercontent.com/assets/1288339/21863986/e681b1b8-d83f-11e6-80f7-bd44242328f2.png)

**Comment by muesliq** [comment]
I gave it a shot: https://github.com/maputnik/editor/pull/71
The idea was to match the Mapbox GL Style Spec structure and wording as close as possible.

Note also #72. (I didn't add them as I'm guessing this would break things, yet I reserved an empty property group for them.)

**Comment by muesliq** [comment]
One more example to illustrate my approach: Now there's the "Color" field in the "Basic" group within a symbol layer. It is unclear what the color is for. Icons? It's mentioned nowhere that that's just the text color.

In my approach the field "Color" would appear in a group named "Text paint properties". Now it's clear that is is for text. (Furthermore the user would understand that he could get help in the section "Paint properties" in the Style Spec.)

**Comment by lukasmartinelli** [comment]
> One more example to illustrate my approach: Now there's the "Color" field in the "Basic" group within a symbol layer. It is unclear what the color is for. Icons? It's mentioned nowhere that that's just the text color.

The names are extracted from the property name. Perhaps allowing the naming to be configured could help?

> The idea was to match the Mapbox GL Style Spec structure and wording as close as possible. Now it would be possible to add a Spec deep link to headers. For example the symbol header "Icon paint properties" could get this deep link (using a help icon for example).

I am very fond of this!

> Note also #72. (I didn't add them as I'm guessing this would break things, yet I reserved an empty property group for them.)

No let's add this! Shouldn't break anything.

> I gave it a shot: #71

I guess this is the drawback as using the same ordering as the spec - but I think the groups are now too large for finding things. Especially in the symbol layer.

![screenshot from 2017-01-12 17-31-20](https://cloud.githubusercontent.com/assets/1288339/21898397/0913fd3c-d8ed-11e6-8c50-2a4cad4f820b.png)

**Comment by muesliq** [comment]
#73 would fix the "too large" problem ;-)
Sorry btw for the quotes error. I used the wrong text editor..

**Comment by lukasmartinelli** [comment]
I guess https://github.com/maputnik/editor/pull/71 makes a good effort out of this. Refactoring is always welcome by future users looking at it.
