### ISSUE TITLE
road rendered error from zoom 16

### ISSUE THREAD

**Issue by phainv88** [maputnik/editor#688]
Hi all,
I have roads which are splitted when i zoom over 16(my raw data have no splits at the splitted point)
I need your support from this issue(please view attached images)

Thanks alot
![error-render2](https://user-images.githubusercontent.com/40235807/82978644-44f3bf80-a00f-11ea-8090-cdd64eed4487.png)
![error-render](https://user-images.githubusercontent.com/40235807/82978648-4624ec80-a00f-11ea-83db-ee36847c76a9.png)

**Comment by pathmapper** [comment]
Hi @phainv88,

there are not enough information to replicate and diagnose the issue. Also it looks like the screenshots are from different locations.

I suggest that you try your style with this example:
https://docs.mapbox.com/mapbox-gl-js/example/simple-map/

If you are seeing the issue also with this official Mapbox example, it's not related to Maputnik.
If you think it's a bug with Mapbox GL JS you could open an issue at https://github.com/mapbox/mapbox-gl-js/issues.

If you still think this is a bug with Maputnik, please provide a style file and lat/lon to allow us to replicate the issue and also the following information:

- Maputnik version
- Browser version
- OS (Windows, macOS, Linux)

**Comment by kateler** [comment]
Are those breaks happening at tile boundaries? If so (and you're making your own tiles), you probably need to increase the tile buffer. 

https://docs.mapbox.com/help/troubleshooting/tileset-recipe-reference/#tile-configurations

**Comment by pathmapper** [comment]
Yep, as @kateler pointed out it looks like it happen at tile boundaries.

You could show the tile boundaries in Maputnik via the checkbox in the debug modal (to open the debug modal press the `ESC` key and afterwards the `?` key):

<img src="https://user-images.githubusercontent.com/20856381/83101897-a79e9700-a0b3-11ea-8c75-bb5382a261ad.png" width="300" />

**Comment by pathmapper** [comment]
@phainv88 not sure if you are related to @tuannvavm, but as this issue seems not related to Maputnik, I'm closing here. 

If you think it's related to Maputnik, please leave a comment with further information and we'll reopen.
