### ISSUE TITLE
OL3 Support

### ISSUE THREAD

**Issue by lukasmartinelli** [maputnik/editor#7]
_Brainstorming and links about OL3 support.._

An example of how to use vector tiles with OL3 has been given at FOSS4G: http://ahocevar.net/whats-new-and-cool-in-openlayers/examples/vector-tiles.html

Links to code:
- https://github.com/ahocevar/whats-new-and-cool-in-openlayers/blob/gh-pages/examples/vector-tiles.html
- http://openlayers.org/en/v3.17.1/examples/resources/mapbox-streets-v6-style.js

The plugin to convert the Mapbox GL style to OL3:
https://github.com/boundlessgeo/ol-mapbox-gl-style

One way how I want to keep the architecture pluggable for future different clients is to solely rely on a given style spec for displaying the layer editor (the different properties for fill, line, symbol, circle..).

**Comment by lukasmartinelli** [comment]
Wow that was easy. Replaced Mapbox GL with OL3 in https://github.com/maputnik/editor/commit/5faa9716b45a67bbcb7b4ff39aacba9b7e1699ba.

Obviously far from perfect - but by just calling a new map render each time 
we can already do some basic editing... this is really doable with OL3. Very excited.

/cc @jj0hns0n @klokan

![jovoc7xgxi](https://cloud.githubusercontent.com/assets/1288339/18847382/57515228-842a-11e6-85e5-484ec3ec2a78.gif)

GIF is using OL3 with the Basic style and OSM2VectorTiles CDN.

**Comment by jj0hns0n** [comment]
:)

**Comment by lukasmartinelli** [comment]
Should OL3 support be alongside Mapbox GL or should it be compiled separately.
I don't like to ship huge JavaScript files with two renderes but I think even worse is having
two versions of Maputnik.

If both render engines are shiped then 
in the editor one would then be able to choose the renderer for the style.

![new_mockup_3](https://cloud.githubusercontent.com/assets/1288339/20608409/fe5e1332-b281-11e6-84aa-00e21c716591.png)

If OL3 is included in that way I ensure during development that it will work in both renderers and is not just an afterthought.

**Comment by pathmapper** [comment]
Experimental OpenLayers support was added again in https://github.com/maputnik/editor/pull/397.
