### ISSUE TITLE
Export as HTML

### ISSUE THREAD

**Issue by pathmapper** [maputnik/editor#705]
From https://github.com/maputnik/editor/pull/680#issuecomment-640047546:

> With regards to export maybe we should add an option to export as html?

This sounds like a good idea to share a preview file for a style.

We had something similar before with gist export and bl.ocks.org (https://bl.ocks.org/anonymous/1e97f8d9cf35cdff8f9181ddd39abf76, note: this is just for showing the structure we had).

First draft of such an HTML:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>**Style Name**</title>
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
<script src="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.js"></script>
<link href="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.css" rel="stylesheet" />
<style>
	body { margin: 0; padding: 0; }
	#map { position: absolute; top: 0; bottom: 0; width: 100%; }
</style>
</head>
<body>
<div id="map"></div>
<script>
    mapboxgl.accessToken = 'access_token';
    var map = new mapboxgl.Map({
       container: 'map',
       style: **inline_style**,
       center: [lon, lat],
       zoom: zoom_level
    });
</script>

</body>
</html>
```

- title = style name
- GL JS version could be taken from `package.json`
- center/zoom could be taken from the current map view at the time of exporting or from the style settings modal

**Comment by orangemug** [comment]
Moved to v1.8.0 release because it was a quick win. PR open ready for review.
