### ISSUE TITLE
"Add Value" button is pressed and then the delete button is pressed, an empty array is generated.

### ISSUE THREAD

**Issue by anagura00** [maputnik/editor#707]
**Maputnik version**:v1.7.0

**Description of the bug**:
"Add Value" button is pressed and then the delete button is pressed, an empty array is generated.

For example, perform the above operation with `text-variable-anchor`, `"text-variable-anchor": []`  is generated and displayed letters will disappear.

To revert `text-variable-anchor` to initial state, it cannot be solved by GUI, the only solution is to edit the editor directly.

**Comment by pathmapper** [comment]
Hi @anagura00,

thanks for the report, agree that the property should be deleted entirely if the delete button is pressed.

We are doing this also for other properties like `text-max-angle` when a custom value is deleted (and the default value is used).
