### ISSUE TITLE
Add toggle for displaying label collision rectangles

### ISSUE THREAD

**Issue by nspringer-trimble** [maputnik/editor#720]
Mapbox GL JS has a map property for showCollisionBoxes. This is super useful when trying to test performance and other labeling issues. Maybe a switch or button in the top bar?

https://docs.mapbox.com/mapbox-gl-js/api/map/#map#showcollisionboxes

![image](https://user-images.githubusercontent.com/7513188/91308975-0c828f80-e77e-11ea-841e-af2e6d85c098.png)

**Comment by orangemug** [comment]
See https://github.com/maputnik/editor/issues/721#issuecomment-680934254

**Comment by nspringer-trimble** [comment]
Nice! Found it, thanks
