### ISSUE TITLE
Add toggle for map tile grid

### ISSUE THREAD

**Issue by nspringer-trimble** [maputnik/editor#721]
Mapbox GL JS has a map property for showTileBoundaries. This helps when trying to debug sources or look for potential issues if rendering raster tiles. Maybe a switch or button in the top bar?

https://docs.mapbox.com/mapbox-gl-js/api/map/#map#showtileboundaries

**Comment by orangemug** [comment]
Hey @nspringer-trimble this is possible via a hidden modal at the moment, see https://github.com/maputnik/editor/pull/519 for details.

**Comment by nspringer-trimble** [comment]
Nice! Found it, thanks
