### ISSUE TITLE
How to deal with unused fields / default values? 

### ISSUE THREAD

**Issue by muesliq** [maputnik/editor#73]
A usability disadvantage of visual editors of this kind is that all fields must be shown, regardless if they are in use or not. Take this extreme example - this minimal layer definition..

![screen shot 2017-01-12 at 14 55 10](https://cloud.githubusercontent.com/assets/1606618/21892622/02db8846-d8d8-11e6-95e1-9eab2d67b4c2.png)

is currently being displayed like this:

![screen shot 2017-01-12 at 14 55 51 copy](https://cloud.githubusercontent.com/assets/1606618/21892639/1182a046-d8d8-11e6-926a-9f34a5e9708d.png)

All fields are there, although none of them is in use.

I'm not sure how to solve this. A couple of ideas come to mind:

### A. Collapse sections, when unused

![screen shot 2017-01-12 at 15 04 24](https://cloud.githubusercontent.com/assets/1606618/21892728/72d54f1a-d8d8-11e6-93cf-b1c5f6bbc763.png)

Advantage: Easy. Disadvantage: As soon as one field within a section is used, the whole section will load open. 

Option: The section header could contain a subtitle such as "defaults in use in all fields".

 ### B. Remove unused fields

A more radical approach: Why not remove "unused" fields altogether? (Maybe without a small defined set of important fields, such as the color of a fill layer.) We'd need a control to open a set of available fields and add them to the view.

The available fields could be just hidden in a collapsed list, or could be selected a modal menu, or could be added by drag & drop in a third sidebar hovering over the map. Interface examples: [1](https://www.wufoo.com/form-builder/), [2](https://www.drupal.org/node/2393181), [3](https://formbuilder.online/)

Follow-up questions: 

- What happens with unused sections, i.e. sections with no field used? Hide them and automatically add them as soon as one field is added? 
- What happens with a field that I have added but don't use? Will it disappear again at next reload?

 ### C. Style unused fields differently
  
A compromise could be to leave the fields there but style them differently: Grey them out or so.

**Comment by lukasmartinelli** [comment]
> A. Collapse sections, when unused

That's an idea that is technically possible. It collides with the feature that once you've collapsed a section it stays open for other layers as well but that could be solved.

In general if there are more smaller sections this becomes more useful.
:+1: 

> B. Remove unused fields

> A more radical approach: Why not remove "unused" fields altogether? (Maybe without a small defined set of important fields, such as the color of a fill layer.) We'd need a control to open a set of available fields and add them to the view.

This is only viable if you use the JSON Editor. I am not sure if everyone is as comfortable with the spec as we are.

> The available fields could be just hidden in a collapsed list, or could be selected a modal menu, or could be added by drag & drop in a third sidebar hovering over the map. Interface examples: 1, 2, 3

I have the gut feeling that this will complicate things even more.
:confused:

> C. Style unused fields differently

That's perhaps the most straightforward to deal with this short term. Really make these properties less important. And group the properties not often used together.

:+1:

**Comment by muesliq** [comment]
> This is only viable if you use the JSON Editor. I am not sure if everyone is as comfortable with the spec as we are.

Of course this would only make sense with some kind of control to add the fields needed. In fact we already have such a function: The "Enable zoom functions control". It adds fields not needed previously.

Anyway, imagine the following scenario for B.: 

A section just contains the used fields. Below those fields there is a big, centered Dropdown. It contains all names of unused fields for that section. Select one and it will be added above the dropdown (plus in the JSON), containing the default value. Easy.

**Comment by lukasmartinelli** [comment]
> A section just contains the used fields. Below those fields there is a big, centered Dropdown. It contains all names of unused fields for that section. Select one and it will be added above the dropdown (plus in the JSON), containing the default value. Easy.

True - but then you need to know what kind of property of the spec you need?
I also liked the exploratory nature of it when starting out - choose a feature and layer type and change all the values to learn what the properties can do.

I want to continue discuss/improve this. But I guess this won't make it into v1.0 but afterwards a v1.1 or so.

**Comment by lukasmartinelli** [comment]
I implemented a version of your proposal C (lowest hanging fruit).
There is a bit a drawback with the opacity styling that when you focus on the field now it will only be highlighted when it is no longer the default value.

![screenshot from 2017-01-15 17-09-55](https://cloud.githubusercontent.com/assets/1288339/21964075/a594fa1c-db45-11e6-8a88-edf5ee575bae.png)
