### ISSUE TITLE
Some icons are not rendered 

### ISSUE THREAD

**Issue by pyrog** [maputnik/editor#740]
**Maputnik version**: v1.7.0, master
**Browser**: Chrome, Firefox, Safari
**OS**: macOS (client)

**Description of the bug**:
i.e. `library` icon is displayed but not `town_hall`
See https://github.com/vdct/ProjetDuMois/issues/109

**Steps to reproduce the behavior**:
1. Open https://maputnik.github.io/editor/#19.15/46.576261/5.7509783

**Style file or style URL**:
OSM Liberty

**Screenshots**:
<img width="806" alt="Console" src="https://user-images.githubusercontent.com/2158081/97776198-6af53100-1b66-11eb-8eff-55918032a72f.png">
<img width="981" alt="Console" src="https://user-images.githubusercontent.com/2158081/97776228-a859be80-1b66-11eb-8c20-7a190dca65c3.png">

<img width="504" alt="Map view" src="https://user-images.githubusercontent.com/2158081/97776209-79dbe380-1b66-11eb-9d8e-6e318c0a67bd.png">
<img width="558" alt="Inspect view" src="https://user-images.githubusercontent.com/2158081/97776206-76e0f300-1b66-11eb-9fdf-520f1cdd1021.png">

**Comment by pathmapper** [comment]
Hi @pyrog, thanks for this detailed report :+1: 

This is not an issue with Maputnik, this is related to the `OSM Liberty` style - there are some POIs in the vectortile source (OpenMapTiles) for which there are currently no icons available.

Here is the related ticket in the https://github.com/maputnik/osm-liberty/ repository: https://github.com/maputnik/osm-liberty/issues/64

Please feel free to have a look at the ticket, continue the discussion there or submit a PR to improve the situation - closing here.
