### ISSUE TITLE
Print server port when starting up

### ISSUE THREAD

**Issue by stevage** [maputnik/editor#751]
This is the output you get when running `yarn run start`:

```
yarn run v1.22.10
$ webpack-dev-server --progress --profile --colors --config config/webpack.config.js
10% building 2/2 modules 0 active(node:40151) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(Use `node --trace-deprecation ...` to show where the warning was created)
<w> [webpack.Progress] 6981ms building
<i> [webpack.Progress] 18ms finish module graph
<i> [webpack.Progress] 13ms chunk graph
<i> [webpack.Progress] 33ms hashing
<i> [webpack.Progress] 97ms chunk assets processing
<i> [webpack.Progress] 299ms after chunk asset optimization
<i> [webpack.Progress] 346ms emitting
```

Confusingly, it doesn't print out the port, so it's hard to find how to access your Maputnik instance without digging through config files.

Would be great to add a simple:

> Server listening at http://localhost:8888

**Comment by pathmapper** [comment]
> so it's hard to find how to access your Maputnik instance without digging through config files

.. or reading the [docs](https://github.com/maputnik/editor#develop) :wink: 

But joking aside, thanks for bringing this up @stevage, makes sense, PR in #752
