### ISSUE TITLE
mapbox is outdated

### ISSUE THREAD

**Issue by JannikGM** [maputnik/editor#775]
Maputnik v1.7.0 (as hosted on https://maputnik.github.io/editor) runs using mapbox Version 1.9.1.
https://github.com/maputnik/editor/blob/v1.7.0/package.json#L44

This is an old version of mapbox that doesn't support expressions such as `slice`: https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#slice
I'd consider this so limiting, that a new maputnik release should occur after the mapbox upgrade, so these new styling features can be used.

In master, this has been upgraded to 1.11.0 (in https://github.com/maputnik/editor/commit/24327541c5c61389c54484396e404689b48fca92), but that's also outdated by now.
Please consider upgrading mapbox 1.x to the latest 1.13.x + potentially additional support for maplibre in the future.

**Comment by pathmapper** [comment]
With @propheel's PR, `master` is now using mapbox-gl `1.13.2`.

Opened #781 to start a discussion about maplibre support.

**Comment by sebisteiner** [comment]
Any plans on building and deploying a new release?
