### ISSUE TITLE
Editor UX Comparison

### ISSUE THREAD

**Issue by lukasmartinelli** [maputnik/editor#8]
Some screenshots of other map editors.
I left out QGIS because imho how you need to style in QGIS doesn't translate to the web well.
## Google Style Wizard

I quite like the 3-drawer thing on the Google Wizard with "Layers > Properties > Editor"

<img width="986" alt="wizard_choose" src="https://cloud.githubusercontent.com/assets/1288339/18902672/bbd678ba-8554-11e6-82f1-9ad332c5a76d.png">

<img width="986" alt="wizard_type_styles" src="https://cloud.githubusercontent.com/assets/1288339/18902675/be8ef1f4-8554-11e6-8e9e-b1a5fb4ce9e8.png">
## Mapbox Studio Classic

<img width="955" alt="classic_code" src="https://cloud.githubusercontent.com/assets/1288339/18902677/c4073baa-8554-11e6-9399-a0650103b355.png">

<img width="961" alt="classic_configure" src="https://cloud.githubusercontent.com/assets/1288339/18902682/c7a430c4-8554-11e6-9417-e5a11fdad13d.png">

<img width="961" alt="classic_layers" src="https://cloud.githubusercontent.com/assets/1288339/18902685/cb04ad0c-8554-11e6-9449-a7d8ac78eb30.png">
## Mapbox Studio

<img width="1023" alt="studio_choose_data" src="https://cloud.githubusercontent.com/assets/1288339/18902689/cfc32e22-8554-11e6-9aa9-e679c08a8ad6.png">

<img width="1022" alt="studio_layer_editor" src="https://cloud.githubusercontent.com/assets/1288339/18902691/d324cada-8554-11e6-9d88-b94c82960d62.png">

**Comment by lukasmartinelli** [comment]
So we just had a meeting with Jeffrey Johnsan and Gretchen Peterson.

Aspects mentioned:

- Make sure users can start right away. Give them a base map to edit. Not first choose the data
- Grouping of layers indeed useful to modify attributes together
- Having data there to style is just as important (luckily OSM2VectorTiles helps us here)
- Collapsing layers not necessarily bad - since it doesn't disturb the map as it stays all in the same column
- XRay mode useful to detect things that gone missing in styling. Hover over data to get info. (Like you style highways and forgot the trunks)
- Often times customers want to style lot's of point symbols. Choose the glyph and label for a given data

Our approach  will be

1. Draw some wireframes for the editor
2. Review does from a cartographer standpoint of view (Gretchen Peterson) to check whether flow makes sense
3. Terranodo can produce a nice looking design based on that
4. Implement it

**Comment by tmcw** [comment]
> XRay mode useful to detect things that gone missing in styling. Hover over data to get info. (Like you style highways and forgot the trunks)

If you do implement something similar, please don't call it X-Ray mode - it is, as far as I know, something that folks at Mapbox created the first implementation of and have consistently named since. It's not really a generic term as much as a specific feature from Studio Classic & Studio.

**Comment by lukasmartinelli** [comment]
> If you do implement something similar, please don't call it X-Ray mode - it is, as far as I know, something that folks at Mapbox created the first implementation of and have consistently named since. It's not really a generic term as much as a specific feature from Studio Classic & Studio.
>  👍 1

Will do. Absolutely understand.

We will take care to make our own decisions and naming in building the editor. The current state is the initial prototype.

**Comment by almccon** [comment]
@lukasmartinelli Also checkout Mapzen's Tangram Play GUI editor: https://github.com/tangrams/tangram-play

![screenshot](https://cloud.githubusercontent.com/assets/1212178/18969021/3cf37632-8640-11e6-851e-75e04a9d5210.png)

**Comment by ThomasG77** [comment]
Less visual, but when I maintain Shift + drawing a rectangle to zoom on the extend, I want to see a rectangle whereas it works, it's far from being obvious.
To use rotation, drag + maintaining Ctrl works.
In both case, hidden behaviour to explain somewhere IMO.

I would also like to know how do you want to manage scales/zoom levels styles. No opinion ATM, just didn't see it in the demo.

**Comment by meekjt** [comment]
I like how the Maputnik demo has the attribute editor extend below the layer label. The other examples all have drawers that extend to cover a lot of the map content. It might be unavoidable to cover some content with the editor, but I think it should be minimized if possible.

I also think the use of the Material Design icons, I think they are becoming quite familiar to users in general.

**Comment by lukasmartinelli** [comment]
> I like how the Maputnik demo has the attribute editor extend below the layer label. The other examples all have drawers that extend to cover a lot of the map content. It might be unavoidable to cover some content with the editor, but I think it should be minimized if possible.

I also like the accordion style and that it only uses vertical screen real estate.
The only limitation I see with it is that it prevents/makes difficult future styling of multiple layers at the same time. So selecting multiple layers and editing a property in all of them. But don't know whether we will implement this in foreseeable future.

**Comment by pka** [comment]
For the sake of completeness, a screenshot ot [Carto Builder](https://carto.com/builder/):

![cartobuilder](https://cloud.githubusercontent.com/assets/19007/20248878/7b1d7644-a9ed-11e6-86ce-58b7dcd11ad0.jpg)

**Comment by jingsam** [comment]
Google Style Wizard is great. We could start from there. However, some issues should be concerned during designing  the UX:
1. The UI of editor should be disparity from mapbox-studio style. As Mapbox is watching this project and OSM2Vectortiles, we should make efforts to avoid any illegal issues.
2. The viewport of map should be maximize. If the style panel overlaps half of the screen, it is hard for users to check the change of map style.
3. Most configuration of style parameters should make map react instantly.  For example, when users set color of water fill, selecting a color could take effects instantly. Do not popup a modal dialog and require users to press the confirm button to take effects.

**Comment by lukasmartinelli** [comment]
I think I found my UX style now (design has been the most difficult part actually - the rest is very straightforward).

![screenshot from 2017-01-04 20-51-56](https://cloud.githubusercontent.com/assets/1288339/21656802/deb994d0-d2bf-11e6-9ff0-e260e2e11ca1.png)
![screenshot from 2017-01-04 20-52-16](https://cloud.githubusercontent.com/assets/1288339/21656804/dec0ae14-d2bf-11e6-84ba-20f2c2599375.png)
![screenshot from 2017-01-04 20-53-04](https://cloud.githubusercontent.com/assets/1288339/21656803/debcb43a-d2bf-11e6-9515-a0461d375124.png)
