### ISSUE TITLE
[wish] inspect mode - link to OpenStreetMap.org same area

### ISSUE THREAD

**Issue by ImreSamu** [maputnik/editor#82]
Thank you for working on this!  

[not critical] 
Sometimes  I want to check the original OpenStreetMap data and now this is not so easy ( as I know ) 
 
my current workflow ..
* find an interesting object  and ask myself :  What is this? No  osm_id, so How I find  the real osm_id ? 
http://maputnik.com/editor/#11.81/41.3611/-105.7342 
* So I copy the coordinate `11.81/41.3611/-105.7342`  from the  URL   
* And paste to the new browser tab  - and create a  new osm URL  
http://www.openstreetmap.org/#map=11.81/41.3611/-105.7342
* And switch on "Map Data" overlay and find an osm_id ( Way: 399981724  )
![image](https://cloud.githubusercontent.com/assets/2217320/21938490/e275719a-d9bb-11e6-91ee-c1acf2d360cc.png)

so my wish :  
*  Is it possible to add a simple  "Open in OpenStreetMap.org in a new window "  link/icon somewhere ?

**Comment by lukasmartinelli** [comment]
You're feedback is very welcome Imre. Also if you have inputs to other parts of the editor.

> Is it possible to add a simple "Open in OpenStreetMap.org in a new window " link/icon somewhere ?

You know what - that could actually be a cool additional Mapbox GL plugin we can just include and show as map control (like https://github.com/lukasmartinelli/mapbox-gl-inspect).

But perhaps we are replicating - doesn't Mapbox already solve this as well (for giving feedback - not going to the data layer).

![screenshot from 2017-01-13 18-58-56](https://cloud.githubusercontent.com/assets/1288339/21939963/6b22b9ca-d9c2-11e6-9e84-55822e4407cf.png)





Something completly different - one could also pull in the OSM GeoJSON file as source in the editor perhaps. Would be an interesting hack.

**Comment by ImreSamu** [comment]
anything that helps debugging vectortiles is  Welcome!     

> You know what - that could actually be a cool additional Mapbox GL plugin we can just include 
> and show as map control (like https://github.com/lukasmartinelli/mapbox-gl-inspect).

it would be perfect   :)

**Comment by stirringhalo** [comment]
Either would be awesome, I've had to go back and forth many times to figure out why something is rendering as it is...

Another option is generating direct Overpass queries and returning those...

**Comment by orangemug** [comment]
So to clarify do we just want a link to the following in the UI somewhere?

```
https://www.openstreetmap.org/#map={ZOOM}/{LAT}/{LON}
```

**Comment by gregorywolanski** [comment]
@ImreSamu? :)

**Comment by ImreSamu** [comment]
>So to clarify do we just want a link to the following in the UI somewhere?

yes,

AND/OR  a split screen?  http://bl.ocks.org/sigdeletras/8e14a1599d0ba5393d668c808f2b8061

**Comment by gregorywolanski** [comment]
@ImreSamu 

I can add the link.

Split screen seems to me to be a too specific feature for Maputnik.

What do you think, @orangemug?

**Comment by orangemug** [comment]
@gregorywolanski yeah split screen is too specific in my opinion also. I think we should add the link, do you have an idea of where you'd put it in the UI.

Might be worth holding off for a couple of days until I have proposed my ideas for a new UI.

**Comment by gregorywolanski** [comment]
I’m holding off then. I’m curious about your ideas. :)

**Comment by orangemug** [comment]
Fixed via #604
