### ISSUE TITLE
info -  OSM QA TILES - support ( extreme use case )

### ISSUE THREAD

**Issue by ImreSamu** [maputnik/editor#83]
Mapbox QA tiles is very special, because 
* it is  for QA and not for rendering  
* and `minzoom: 12` and `maxzoom: 12` 

see more: 
* https://www.mapbox.com/blog/osm-qa-tiles/
* http://osmlab.github.io/osm-qa-tiles/

My question:  
* Anybody tried designing - the QA tiles  with maputnik ? 

### my workflow 
I can create a TileJSON service via `tileserver-gl` `http://localhost:8080/data/01142017052801.planet.json`

simple code for `iceland` . If you want other see ["country extracts"](http://osmlab.github.io/osm-qa-tiles/country.html) 
```
mkdir qatiles
cd ./qatiles
wget https://s3.amazonaws.com/mapbox/osm-qa-tiles/latest.country/iceland.mbtiles.gz
gunzip iceland.mbtiles.gz
docker run -it --rm -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl
```

and I can add this service file to the http://maputnik.com/editor/  "Sources" 
* `TileJSON url`:  `http://localhost:8080/data/01142017052801.planet.json`

But from here not so easy ...  
* I have to clear manually -  the all default layers from the left layers side ..  
* I have to find the Iceland QA tiles data [ only in zoom level=12 ]  sometimes this is not so easy ! 
* ...

**Comment by ImreSamu** [comment]
# Filter 

![image](https://cloud.githubusercontent.com/assets/2217320/21956505/d6b1baea-da82-11e6-924f-b1cb4078c480.png)

* I have tried to create a filter for `@Version`
    *    and I got `Layers[1].filter[1][1]: filter key cannot be a constant`
* other variables.  without a `@`  -  probably ok , no error .. 

Theory:   Probably don't like the  '@xxxxxx'  variables ??

**Comment by ImreSamu** [comment]
# Filter 

QA tiles has probably more than 500 variables ..  
* and not abc ordered in the list  ..  
so It is very hard to choose  or find a name  
![image](https://cloud.githubusercontent.com/assets/2217320/21956567/479fed84-da84-11e6-9909-46730c137b85.png)

**Comment by ImreSamu** [comment]
The `@`  filtering ( `filter key cannot be a constant`) is a known style-spec validator problem : https://github.com/mapbox/mapbox-gl-style-spec/issues/654

**Comment by lukasmartinelli** [comment]
> I have to clear manually - the all default layers from the left layers side ..

You can start from a new empty style.

> QA tiles has probably more than 500 variables ..

It's an interesting use case - but I don't think that this is something we need to support.
QA Tiles vector tile schema is really not meant for this.

> The @ filtering ( filter key cannot be a constant) is a known style-spec validator problem : mapbox/mapbox-gl-style-spec#654

Good to have this documented here :+1:

**Comment by ImreSamu** [comment]
>You can start from a new empty style.

thanks! 
it was new info for me.  
![image](https://cloud.githubusercontent.com/assets/2217320/21962186/f92cb69a-db1f-11e6-98cd-e8a1f1653166.png)

imho: 
*  If we have more than 20  styles it is not so easy to find  ...

**Comment by lukasmartinelli** [comment]
> If we have more than 20 styles it is not so easy to find ...

Looking forward to the problem of 20 styles :grinning: 
But should perhaps be the second/third option. Even though for most use cases you never want to start empty.
