### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by snodnipper** [maputnik/editor#88]
Using the CLI (maputnik_darwin / v1.0.1) we get CORS issues using OpenMapTiles.  Mapbox Streets works fine. 
![screen shot 2017-01-18 at 11 14 03](https://cloud.githubusercontent.com/assets/576719/22061954/3ce0f3d2-dd6f-11e6-841b-edfbfa373d9f.png)

**Comment by klokan** [comment]
The free.tilehosting.com server has CORS set correctly to "access-control-allow-origin:*", but the server redirects, because your key is invalid.

You you have your own access key?
You can generate one for free at https://openmaptiles.com/hosting/ and set it up in the Maputnik Settings, the same way you set the Mapbox keys.

**Comment by lukasmartinelli** [comment]
Ah the access token in the "Add Source" of OpenMapTiles is obsolete..

**Comment by snodnipper** [comment]
Sure, so I got that done correctly.  I also noted the "OpenMapTilesAccessToken" under style settings.  Perhaps being able to set arbitrary parameters for a source would be nice (e.g. clicking a source and setting 'key', 'token' etc. that will be sent per request).

<img width="678" alt="screen shot 2017-01-18 at 12 03 34" src="https://cloud.githubusercontent.com/assets/576719/22063346/374bb3b0-dd76-11e6-806e-eb1909cc802a.png">

**Comment by lukasmartinelli** [comment]
> Sure, so I got that done correctly. I also noted the "OpenMapTilesAccessToken" under style settings. Perhaps being able to set arbitrary parameters for a source would be nice (e.g. clicking a source and setting 'key', 'token' etc. that will be sent per request).

You are right but in the end you can always change the source URL. Which you will also do if you host your own tiles somewhere. Having configurable query string params would probably be too much.

I know the token for OpenMapTiles is handled a bit special - same goes for Mapbox Streets.
All other sources (like Mapzen) need to have the access key or any other url params in the source TileJSON/XYZ url.

**Comment by lukasmartinelli** [comment]
Default style now contains access token https://github.com/maputnik/editor/commit/e4850805fbfbfafd15808b11fab468444aaf44f1
