### ISSUE TITLE
Can't add layer under Safari

### ISSUE THREAD

**Issue by pyrog** [maputnik/editor#89]
Tested on Safari Version 10.0.2 (12602.3.12.0.1) under macOS Sierra 10.12.2 (16C67)
Work fine on Chrome and Firefox.

See #37

**Comment by lukasmartinelli** [comment]
Since Maputnik uses some fairly recent HTML features I do know that Safari does have problems with it. I cannot however test it with Safari on Linux - therefore it is likely that I won't be fixing it soon but I'll leave it open.

**Comment by orangemug** [comment]
I believe the issue was simply that the modal isn't breaking out of the `overflow: hidden;` on the `.maputnik-layer-list` in safari. Removing it doesn't seem to cause any issues, although I'm not 100% sure about this. See https://github.com/maputnik/editor/compare/master...orangemug:fix/issue-89 for the fix.

@pyrog would you like to test the fix?

**Comment by pyrog** [comment]
@orangemug the maputnik-modal div is not visible 😞

**Comment by orangemug** [comment]
@pyrog did you try it on my branch? You'll have to clone the repo and run it locally (sorry should have mentioned that earlier)

**Comment by pyrog** [comment]
> @pyrog did you try it on my branch?

No 

> You'll have to clone the repo and run it locally

OK. How to run it ? (I don't see any index.html page)

**Comment by orangemug** [comment]
Hey @pyrog if you're interested in working out how to run/test it, take a look at the [README.md](https://github.com/maputnik/editor#develop).

Glad to see removing `overflow: hidden;` fixed it for you. I just need to double check it doesn't break anything else, then I'll raise a PR so we can get this released.

**Comment by orangemug** [comment]
The fix for this has been merged, closing issue
