### ISSUE TITLE
Show Tooltip only on Click in Map Mode

### ISSUE THREAD

**Issue by flp-gpc** [maputnik/editor#90]
Would it be possible to add an option to switch the tooltip off from the map ? It slows down the display and zooming, and it is often annoying when we look at the map. Once you know your map's properties, this tooltip is not really useful anymore in my opinion.

**Comment by lukasmartinelli** [comment]
I think I should switch back to the click model of before. Only show the tooltip when you actually click while in map mode - not on hover.

**Comment by flp-gpc** [comment]
Or another option could be to keep the on hover feature only in inspect mode, where it has more sense.

**Comment by lukasmartinelli** [comment]
My Mapbox GL Inspect plugin now supports it https://github.com/lukasmartinelli/mapbox-gl-inspect/commit/e26c255cba7ee1e8861ff8000ee5bea75a59ef9a and it is integrated in maputnik with 2458d4b
