### ISSUE TITLE
projection

### ISSUE THREAD

**Issue by Fil** [maputnik/editor#94]
Is there a way to use another projection? It would be fantastic to be able to integrate any [d3-geo-projection](https://github.com/d3/d3-geo-projection) as an option.

(With vector tiles we can be free from the tyranny of WebMercator!)

**Comment by orangemug** [comment]
It doesn't look like it's possible in [mapbox/mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js) see https://github.com/mapbox/mapbox-gl-js/issues/3184. I'm not sure about OpenLayers though...

**Comment by orangemug** [comment]
Closing this issue, when/if its supported in mapbox-gl-js (mapbox/mapbox-gl-js#3184) we'll reopen.
