### ISSUE TITLE
Inspect Mode doesn't work after style change

### ISSUE THREAD

**Issue by muesliq** [maputnik/editor#95]
Steps to reproduce bug:

1. Load Maputnik with Mapbox based style
1. Click "Open" and select Openmaptiles based style
1. Click "Inspect Mode"

Console error message:
`Error: layers: source "mapbox" not found `

(On a side note maybe the other menu buttons should be greyed out when in Inspect Mode.)

**Comment by gregorywolanski** [comment]
I’m working on it.

**Comment by orangemug** [comment]
@gregorywolanski fixed this in #222
