### ISSUE TITLE
Is it possible to do data-driven styling?

### ISSUE THREAD

**Issue by chriswhong** [maputnik/editor#96]
Maputnik is awesome, it perfectly fits our use case here at the NYC Department of City Planning where we are consuming MVTs from a self-hosted carto instance, but do not have an editor!  

Is is possible to do data-driven styles?  I am only seeing the option to pick a single color for a given layer.  Thanks, and thanks for making this tool!

**Comment by muesliq** [comment]
To my knowledge it is not, yet you can always edit a layer's JSON by hand, adding those missing features by hand.

**Comment by chriswhong** [comment]
Thanks!

**Comment by orangemug** [comment]
This is a feature I'd also be interested in. Out of interest has anybody thought about what the UI might look like for this?

**Comment by muesliq** [comment]
Probably similar to the stop functions which look like this:
![screen shot 2017-03-15 at 15 26 22](https://cloud.githubusercontent.com/assets/1606618/23953050/c64fe4ca-0993-11e7-885f-053c51d26036.png)

Just that
- A field "property" above the stop lines would be needed
- The "stops" fields wouldn't be numbers only 

So it would look something like this:

```
Color              Property: [____________]
        [DEL] [____________] [____________]
        [DEL] [____________] [____________]
                                 [Add stop]
```

What makes things really complicated is the need to be able to combine zoom functions and data driven styling, as in this example:

```
'line-offset': {
  	  'property': 'NAME',
  	  'type': 'categorical',
  	  'stops': [
  	    [{zoom: 10, value: 'LineA'}, 3],
  	    [{zoom: 10, value: 'LineB'}, 0],
  	    [{zoom: 10, value: 'LineC'}, -3],
  	    [{zoom: 14, value: 'LineA'}, 6],
  	    [{zoom: 14, value: 'LineB'}, 0],
  	    [{zoom: 14, value: 'LineC'}, -6]
  	  ]
  	}
```

I'm not sure what the ideal UI for such complexity would be. Maybe JSON is best for that, anyway.

**Comment by orangemug** [comment]
@pjsier added this as a part of #161
