### ISSUE TITLE
layer list cutoff / prevents scrolling further

### ISSUE THREAD

**Issue by jonahadkins** [maputnik/editor#97]
using `maputnik_darwin 1.01` in a chrome browser - i have a long layer list and the location of the add layer dialog cuts off the dropdown at my the edge of my browser window - in the screen-cap below, there are several entries after the last entry shown...sorry if this has been addressed or brought up already .

![maputnik_bug](https://cloud.githubusercontent.com/assets/5178200/22671084/70ea04c2-ec9a-11e6-82e1-8b5abcfb7919.png)

**Comment by orangemug** [comment]
Working branch is here <https://github.com/orangemug/editor/compare/orangemug:fix/source-layer-autocomplete...orangemug:fix/issue-97-layer-list-cutoff> seems to work ok. I'll tidy up and make a PR once the other pull requests this relies on are merged.
