### ISSUE TITLE
SetCenter() SetZoom()?

### ISSUE THREAD

**Issue by ARolek** [maputnik/editor#99]
I'm using Maputnik for some debugging and it would be helpful to be able to move the map to a specific center and zoom. Though it would be nice to have this as a feature, I'm also fine accessing the map instance from the debug console. Is there an easy way to get a reference to the map instance?

**Comment by lukasmartinelli** [comment]
You can specify lat/lon and zoom in the URL afaik. If you move around in the editor you will see as it updates the location.
Does that help?

**Comment by ARolek** [comment]
That works great. Thanks.
